// Ders 20 verisi — CORE 2000 (1-72)
const L20 = {
  words:[
    {id:'c1',ro:'sa-wat-dii',tr:'Merhaba',en:'Hello',tip:'',ctx:'',examples:[]},
    {id:'c5',ro:'yin-dii',tr:'Tanıştığıma memnun oldum',en:'Nice to meet you',tip:'',ctx:'',examples:[]},
    {id:'c6',ro:'sa-baai',tr:'nasılsın',en:'How are',tip:'',ctx:'',examples:[]},
    {id:'c7',ro:'chai',tr:'Evet',en:'Yes',tip:'',ctx:'',examples:[]},
    {id:'c8',ro:'mai',tr:'HAYIR',en:'No',tip:'',ctx:'',examples:[]},
    {id:'c9',ro:'khaawp-khun',tr:'Teşekkür ederim',en:'Thank you',tip:'',ctx:'',examples:[]},
    {id:'c10',ro:'chan',tr:'Ben',en:'I\'m',tip:'',ctx:'',examples:[]},
    {id:'c11',ro:'a-gaawn',tr:'elveda',en:'oodbye',tip:'',ctx:'',examples:[]},
    {id:'c12',ro:'mai-dii',tr:'kötü',en:'bad',tip:'',ctx:'',examples:[]},
    {id:'c13',ro:'dii',tr:'iyi',en:'good',tip:'',ctx:'',examples:[]},
    {id:'c16',ro:'ngaai',tr:'kolay',en:'easy',tip:'',ctx:'',examples:[]},
    {id:'c19',ro:'glai',tr:'uzak',en:'far',tip:'',ctx:'',examples:[]},
    {id:'c21',ro:'wan-nfi',tr:'Bugün',en:'today',tip:'',ctx:'',examples:[]},
    {id:'c24',ro:'sap-daa',tr:'hafta',en:'week',tip:'',ctx:'',examples:[]},
    {id:'c26',ro:'wf-naa-thii',tr:'ikinci',en:'second',tip:'',ctx:'',examples:[]},
    {id:'c27',ro:'naa-thii',tr:'dakika',en:'minute',tip:'',ctx:'',examples:[]},
    {id:'c30',ro:'moong',tr:'saat',en:'o\'clock',tip:'',ctx:'',examples:[]},
    {id:'c31',ro:'bpa-dti-thin',tr:'takvim',en:'calendar',tip:'',ctx:'',examples:[]},
    {id:'c33',ro:'wan',tr:'Salı',en:'Tuesday',tip:'',ctx:'',examples:[]},
    {id:'c34',ro:'wan',tr:'Çarşamba',en:'Wednesday',tip:'',ctx:'',examples:[]},
    {id:'c35',ro:'baaw-dii',tr:'Perşembe',en:'Thursday',tip:'',ctx:'',examples:[]},
    {id:'c36',ro:'wan',tr:'Cuma',en:'Friday',tip:'',ctx:'',examples:[]},
    {id:'c37',ro:'wan',tr:'Cumartesi',en:'Saturday',tip:'',ctx:'',examples:[]},
    {id:'c38',ro:'wan',tr:'Pazar',en:'Sunday',tip:'',ctx:'',examples:[]},
    {id:'c40',ro:'bpai',tr:'Gitmek',en:'go',tip:'',ctx:'',examples:[]},
    {id:'c42',ro:'a-raauy',tr:'lezzetli',en:'delicious',tip:'',ctx:'',examples:[]},
    {id:'c43',ro:'nam',tr:'su',en:'water',tip:'',ctx:'',examples:[]},
    {id:'c44',ro:'chaa',tr:'çay',en:'tea',tip:'',ctx:'',examples:[]},
    {id:'c45',ro:'gaa-faae',tr:'Kahve',en:'coffee',tip:'',ctx:'',examples:[]},
    {id:'c47',ro:'waai',tr:'şarap',en:'wine',tip:'',ctx:'',examples:[]},
    {id:'c48',ro:'nuuea-wuua',tr:'biftek',en:'beef',tip:'',ctx:'',examples:[]},
    {id:'c49',ro:'gai',tr:'tavuk',en:'chicken',tip:'',ctx:'',examples:[]},
    {id:'c51',ro:'bplaa',tr:'balık',en:'fish',tip:'',ctx:'',examples:[]},
    {id:'c52',ro:'nuuea-gae',tr:'kuzu',en:'lamb',tip:'',ctx:'',examples:[]},
    {id:'c54',ro:'jao-naa-thfi-dtam-ruuat',tr:'polis memuru',en:'police officer',tip:'',ctx:'',examples:[]},
    {id:'c55',ro:'khruu',tr:'Öğretmen',en:'teacher',tip:'',ctx:'',examples:[]},
    {id:'c57',ro:'maa',tr:'Gelmek',en:'come',tip:'',ctx:'',examples:[]},
    {id:'c58',ro:'hen',tr:'Görmek',en:'see',tip:'',ctx:'',examples:[]},
    {id:'c60',ro:'chai',tr:'f\'se',en:'f\'se',tip:'',ctx:'',examples:[]},
    {id:'c61',ro:'saa-maat',tr:'olabilmek',en:'can',tip:'',ctx:'',examples:[]},
    {id:'c62',ro:'sewn',tr:'sıfır',en:'zero',tip:'',ctx:'',examples:[]},
    {id:'c63',ro:'nueng',tr:'bir',en:'one',tip:'',ctx:'',examples:[]},
    {id:'c64',ro:'saawng',tr:'iki',en:'two',tip:'',ctx:'',examples:[]},
    {id:'c65',ro:'saam',tr:'üç',en:'three',tip:'',ctx:'',examples:[]},
    {id:'c66',ro:'sii',tr:'dört',en:'four',tip:'',ctx:'',examples:[]},
    {id:'c68',ro:'hok',tr:'altı',en:'six',tip:'',ctx:'',examples:[]},
    {id:'c69',ro:'jet',tr:'Yedi',en:'seven',tip:'',ctx:'',examples:[]},
    {id:'c70',ro:'bpaaet',tr:'sekiz',en:'eight',tip:'',ctx:'',examples:[]},
    {id:'c71',ro:'gao',tr:'dokuz',en:'nine',tip:'',ctx:'',examples:[]},
    {id:'c72',ro:'sip',tr:'on',en:'ten',tip:'',ctx:'',examples:[]},
  ]
};

LESSONS[20] = L20;
