// === DERS11.JS START ===
// Ders 11 verisi — tayca-v3
// =================== VERİ: DERS 11 — Hastane ve Eczane ===================
const L11 = {
  tones:[],
  words:[
    {id:'w1',th:'โรงพยาบาล',ro:'rong-pha-yaa-baan',tr:'Hastane',
     tip:'"Rong" = bina, "pha-yaa-baan" = hastane/tedavi evi. Uzun ama sık gerekli.',
     ctx:'Phuket\'te en iyi hastane: Bangkok Hospital Phuket ve Vachira Hospital.',
     examples:[
       {th:'โรงพยาบาลอยู่ที่ไหนครับ',ro:'rong-pha-yaa-baan yuu thii-nai khrap',tr:'Hastane nerede?',bd:[{ro:'rong-pha-yaa-baan yuu thii-nai',tr:'hastane nerede',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'พาไปโรงพยาบาลด้วยครับ',ro:'phaa pai rong-pha-yaa-baan duay khrap',tr:'Beni hastaneye götürün lütfen.',bd:[{ro:'phaa pai rong-pha-yaa-baan duay',tr:'hastaneye götür lütfen',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'โรงพยาบาลเปิดตลอด 24 ชั่วโมงครับ',ro:'rong-pha-yaa-baan poet ta-lot yii-sip-sii chua-mong khrap',tr:'Hastane 24 saat açık.',bd:[{ro:'rong-pha-yaa-baan poet ta-lot',tr:'hastane 24 saat açık',role:'V - Yuklem'},{ro:'yii-sip-sii chua-mong',tr:'24 saat',role:'Zaman'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ต้องไปโรงพยาบาลครับ',ro:'tong pai rong-pha-yaa-baan khrap',tr:'Hastaneye gitmeliyim.',bd:[{ro:'tong pai rong-pha-yaa-baan',tr:'hastaneye gitmeliyim',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'โรงพยาบาลรัฐหรือเอกชนครับ',ro:'rong-pha-yaa-baan rat rue ek-ka-chon khrap',tr:'Devlet hastanesi mi özel mi?',bd:[{ro:'rong-pha-yaa-baan rat',tr:'devlet hastanesi',role:'Kelime'},{ro:'rue ek-ka-chon',tr:'yoksa özel',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w2',th:'ร้านขายยา',ro:'raan-khaai-yaa',tr:'Eczane',
     tip:'"Raan" = dükkan, "khaai" = satmak, "yaa" = ilaç. Phuket\'te 7-Eleven yakınında eczane çok.',
     ctx:'Basit hastalıklarda önce eczaneye git, Tayca "mii yaa ... mai?" ile ilaç sor.',
     examples:[
       {th:'ร้านขายยาอยู่ที่ไหนครับ',ro:'raan-khaai-yaa yuu thii-nai khrap',tr:'Eczane nerede?',bd:[{ro:'raan-khaai-yaa yuu thii-nai',tr:'eczane nerede',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ร้านขายยาเปิดไหมครับ',ro:'raan-khaai-yaa poet mai khrap',tr:'Eczane açık mı?',bd:[{ro:'raan-khaai-yaa poet mai',tr:'eczane açık mı',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ร้านขายยาใกล้ที่สุดอยู่ที่ไหนครับ',ro:'raan-khaai-yaa glai-thii-sut yuu thii-nai khrap',tr:'En yakın eczane nerede?',bd:[{ro:'raan-khaai-yaa glai-thii-sut',tr:'en yakın eczane',role:'S - Ozne'},{ro:'yuu thii-nai',tr:'nerede',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ซื้อยาที่ร้านขายยาได้ครับ',ro:'sue yaa thii raan-khaai-yaa dai khrap',tr:'Eczaneden ilaç alabilirsin.',bd:[{ro:'sue yaa thii raan-khaai-yaa dai',tr:'eczaneden ilaç alınabilir',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w3',th:'เจ็บ',ro:'jep',tr:'Agri / Aci duymak',
     tip:'"Jep" = ağrı, acı hissi. "Jep maak" = çok acıyor. Vücut bölgesiyle birlikte kullanılır.',
     ctx:'Doktora tam olarak neresi ağrıdığını anlatmak için şart.',
     examples:[
       {th:'เจ็บมากครับ',ro:'jep maak khrap',tr:'Çok acıyor.',bd:[{ro:'jep maak',tr:'çok acıyor',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'เจ็บตรงไหนครับ',ro:'jep trong-nai khrap',tr:'Neresi ağrıyor?',bd:[{ro:'jep trong-nai',tr:'neresi ağrıyor',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'คอเจ็บครับ',ro:'kho jep khrap',tr:'Bogazım ağrıyor.',bd:[{ro:'kho jep',tr:'boğaz ağrıyor',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'เจ็บมาสองวันแล้วครับ',ro:'jep maa song wan laeo khrap',tr:'Iki gündür acıyor.',bd:[{ro:'jep maa song wan laeo',tr:'iki gündür acıyor',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ไม่เจ็บแล้วครับ',ro:'mai jep laeo khrap',tr:'Artık acımıyor.',bd:[{ro:'mai jep laeo',tr:'artık acımıyor',role:'Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w4',th:'หมอ',ro:'moo',tr:'Doktor',
     tip:'"Moo" kısa ve kolay. "Phop moo" = doktoru gör. "Moo yaa" = doktor ve ilaç anlamına da gelir.',
     ctx:'Phuket\'te Bangkok Hospital\'da İngilizce konuşan doktor bulunur.',
     examples:[
       {th:'ต้องพบหมอครับ',ro:'tong phop moo khrap',tr:'Doktoru görmem lazım.',bd:[{ro:'tong phop moo',tr:'doktor görmek lazım',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'หมออยู่ไหมครับ',ro:'moo yuu mai khrap',tr:'Doktor var mı?',bd:[{ro:'moo yuu mai',tr:'doktor var mı',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'หมอพูดภาษาอังกฤษได้ไหมครับ',ro:'moo phuut phaa-saa ang-grit dai mai khrap',tr:'Doktor Ingilizce konuşabiliyor mu?',bd:[{ro:'moo phuut phaa-saa ang-grit dai mai',tr:'doktor İngilizce konuşabilir mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'หมอบอกว่าต้องพักผ่อนครับ',ro:'moo bok waa tong phak-phon khrap',tr:'Doktor dinlenmem gerektiğini söyledi.',bd:[{ro:'moo bok waa tong phak-phon',tr:'doktor dinlen dedi',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'นัดหมอไว้พรุ่งนี้ครับ',ro:'nat moo wai phrung-nii khrap',tr:'Yarın doktor randevum var.',bd:[{ro:'nat moo wai phrung-nii',tr:'yarın doktor randevusu var',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w5',th:'ยา',ro:'yaa',tr:'Ilac',
     tip:'"Yaa" = ilaç/ilaçlar. "Gin yaa" = ilaç içmek. "Yaa gae puat" = ağrı kesici.',
     ctx:'Eczanede ilaç adını bilmiyorsan belirtini anlat: "puat hua" = baş ağrısı.',
     examples:[
       {th:'มียาไหมครับ',ro:'mii yaa mai khrap',tr:'Ilaç var mı?',bd:[{ro:'mii yaa mai',tr:'ilaç var mı',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'กินยาวันละสามครั้งครับ',ro:'gin yaa wan-la saam khrang khrap',tr:'Günde üç kez ilaç iç.',bd:[{ro:'gin yaa wan-la saam khrang',tr:'günde üç kez ilaç',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ยานี้มีผลข้างเคียงไหมครับ',ro:'yaa nii mii phon-khaang-khiang mai khrap',tr:'Bu ilacın yan etkisi var mı?',bd:[{ro:'yaa nii mii phon-khaang-khiang mai',tr:'bu ilacın yan etkisi var mı',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ลืมกินยาครับ',ro:'luem gin yaa khrap',tr:'Ilaç içmeyi unuttum.',bd:[{ro:'luem gin yaa',tr:'ilaç içmeyi unuttum',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ยาหมดแล้วครับ',ro:'yaa mot laeo khrap',tr:'Ilaç bitti.',bd:[{ro:'yaa mot laeo',tr:'ilaç bitti',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w6',th:'ปวด',ro:'puat',tr:'Agrimak (ic agri)',
     tip:'"Puat" = içten gelen ağrı, sızı. "Jep" daha keskin, "puat" daha sürekli/künt ağrıdır.',
     ctx:'"Puat hua" = baş ağrısı, "puat thong" = mide ağrısı, "puat lang" = sırt ağrısı.',
     examples:[
       {th:'ปวดหัวครับ',ro:'puat hua khrap',tr:'Basım ağrıyor.',bd:[{ro:'puat hua',tr:'baş ağrısı',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ปวดท้องมากครับ',ro:'puat thong maak khrap',tr:'Midem çok ağrıyor.',bd:[{ro:'puat thong maak',tr:'mide çok ağrıyor',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ปวดหลังครับ',ro:'puat lang khrap',tr:'Sırtım ağrıyor.',bd:[{ro:'puat lang',tr:'sırt ağrısı',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ปวดฟันครับ',ro:'puat fan khrap',tr:'Disim ağrıyor.',bd:[{ro:'puat fan',tr:'diş ağrısı',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ยาแก้ปวดมีไหมครับ',ro:'yaa gae puat mii mai khrap',tr:'Agri kesici var mı?',bd:[{ro:'yaa gae puat',tr:'ağrı kesici',role:'S - Ozne'},{ro:'mii mai',tr:'var mı',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w7',th:'ไข้',ro:'khai',tr:'Ates (hastalık)',
     tip:'"Khai" = ateş (hastalık). "Pen khai" = ateşim var. "Khai khuen" = ateş yükseldi.',
     ctx:'Tropikal iklimde ateş olursa doktora git. Dengue ateşi Phuket\'te görülür.',
     examples:[
       {th:'ผมเป็นไข้ครับ',ro:'pom pen khai khrap',tr:'Atesim var.',bd:[{ro:'pom',tr:'ben',role:'S - Ozne'},{ro:'pen khai',tr:'ateş var',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ไข้สูงไหมครับ',ro:'khai sung mai khrap',tr:'Ates yüksek mi?',bd:[{ro:'khai sung mai',tr:'ateş yüksek mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ไข้สามสิบแปดองศาครับ',ro:'khai saam-sip-paet ong-saa khrap',tr:'Ates 38 derece.',bd:[{ro:'khai saam-sip-paet ong-saa',tr:'ateş 38 derece',role:'Kelime'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ยาลดไข้มีไหมครับ',ro:'yaa lot khai mii mai khrap',tr:'Ates düsürücü var mı?',bd:[{ro:'yaa lot khai mii mai',tr:'ateş düşürücü var mı',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ไข้ลดแล้วครับ',ro:'khai lot laeo khrap',tr:'Ates düstü.',bd:[{ro:'khai lot laeo',tr:'ateş düştü',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w8',th:'แพ้',ro:'phae',tr:'Alerji / Alerjik olmak',
     tip:'"Phae" = alerji, alerjik tepki. "Phae yaa" = ilaca alerjim. "Phae aa-haan" = yiyeceğe alerjim.',
     ctx:'Hastanede veya eczanede ilaç alırken alerjini mutlaka söyle.',
     examples:[
       {th:'ผมแพ้เพนนิซิลินครับ',ro:'pom phae pen-ni-si-lin khrap',tr:'Penisiline alerjim var.',bd:[{ro:'pom phae pen-ni-si-lin',tr:'penisiline alerjim',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'แพ้ยาอะไรบ้างครับ',ro:'phae yaa a-rai bang khrap',tr:'Hangi ilaçlara alerjisiniz?',bd:[{ro:'phae yaa a-rai bang',tr:'hangi ilaçlara alerji',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'แพ้อาหารทะเลครับ',ro:'phae aa-haan ta-lee khrap',tr:'Deniz ürünlerine alerjim var.',bd:[{ro:'phae aa-haan ta-lee',tr:'deniz ürünlerine alerji',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ไม่แพ้ยาอะไรครับ',ro:'mai phae yaa a-rai khrap',tr:'Hiçbir ilaca alerjim yok.',bd:[{ro:'mai phae yaa a-rai',tr:'hiçbir ilaca alerji yok',role:'Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'มีอาการแพ้ครับ',ro:'mii aa-gaan phae khrap',tr:'Alerjik belirtim var.',bd:[{ro:'mii aa-gaan phae',tr:'alerjik belirti var',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w9',th:'นัด',ro:'nat',tr:'Randevu',
     tip:'"Nat" = randevu. "Nat moo" = doktor randevusu. "Nat wai" = randevu ayarladım.',
     ctx:'Bangkok Hospital Phuket\'te telefon veya online randevu alınabilir.',
     examples:[
       {th:'ขอนัดหมอครับ',ro:'khor nat moo khrap',tr:'Doktor randevusu almak istiyorum.',bd:[{ro:'khor nat moo',tr:'doktor randevusu istiyorum',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'นัดกี่โมงครับ',ro:'nat gii-mong khrap',tr:'Randevu saat kaçta?',bd:[{ro:'nat gii-mong',tr:'randevu saat kaç',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ผมมีนัดบ่ายสองครับ',ro:'pom mii nat baai-song khrap',tr:'Saat 14:00\'te randevum var.',bd:[{ro:'pom mii nat baai-song',tr:'saat 14\'te randevum var',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'เปลี่ยนนัดได้ไหมครับ',ro:'plian nat dai mai khrap',tr:'Randevuyu değiştirebilir miyim?',bd:[{ro:'plian nat dai mai',tr:'randevuyu değiştirebilir mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ยกเลิกนัดครับ',ro:'yok-loek nat khrap',tr:'Randevuyu iptal ediyorum.',bd:[{ro:'yok-loek nat',tr:'randevuyu iptal et',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w10',th:'ท้อง',ro:'thong',tr:'Karin / Mide',
     tip:'"Thong" = karın veya mide. "Puat thong" = karın/mide ağrısı. "Tong sia" = ishal.',
     ctx:'Tropikal yiyecekler mideni bozabilir. "Puat thong" eczanede duyurulunca anlayacaklar.',
     examples:[
       {th:'ปวดท้องครับ',ro:'puat thong khrap',tr:'Karin/midem ağrıyor.',bd:[{ro:'puat thong',tr:'karın ağrısı',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ท้องเสียครับ',ro:'thong sia khrap',tr:'Ishalim var.',bd:[{ro:'thong sia',tr:'ishal',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ท้องอืดครับ',ro:'thong uet khrap',tr:'Karin şişkinligim var.',bd:[{ro:'thong uet',tr:'karın şişkinliği',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ยาแก้ท้องเสียมีไหมครับ',ro:'yaa gae thong-sia mii mai khrap',tr:'Ishal ilacı var mı?',bd:[{ro:'yaa gae thong-sia',tr:'ishal ilacı',role:'S - Ozne'},{ro:'mii mai',tr:'var mı',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ท้องปกติแล้วครับ',ro:'thong pok-ka-ti laeo khrap',tr:'Midem normale döndü.',bd:[{ro:'thong pok-ka-ti laeo',tr:'mide normale döndü',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
  ],
  grammar:[
    {
      title:'1. MII ... MAI = ... var mı?',
      formula:'MII + [ŞEY/KONU] + MAI = ... var mı?',
      explain:'"Mii" = var, "mai" = soru eki. Birlikte "... var mı?" sorusu oluşturur. Eczanede ve hastanede ilaç, hizmet veya doktor sormak için çok kullanılır.',
      tips:['"mii" = var (olumlu)','mai mii = yok (olumsuz)','Cevap: mii = var | mai mii = yok','"mii ... mai" her türlü şeyin varlığını sorabilir','Formülde soru sözcügü sona gelir'],
      examples:[
        {th:'มียาแก้ปวดไหมครับ',ro:'mii yaa gae puat mai khrap',tr:'Agri kesici var mı?',bd:[{ro:'mii',tr:'var',role:'V - Yuklem'},{ro:'yaa gae puat',tr:'ağrı kesici',role:'O - Nesne'},{ro:'mai',tr:'soru eki',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
        {th:'มีหมออยู่ไหมครับ',ro:'mii moo yuu mai khrap',tr:'Doktor var mı?',bd:[{ro:'mii moo yuu mai',tr:'doktor var mı',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
        {th:'มียาลดไข้ไหมครับ',ro:'mii yaa lot khai mai khrap',tr:'Ates düsürücü var mı?',bd:[{ro:'mii',tr:'var',role:'V - Yuklem'},{ro:'yaa lot khai',tr:'ateş düşürücü',role:'O - Nesne'},{ro:'mai',tr:'soru eki',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
        {th:'มีนัดว่างไหมครับ',ro:'mii nat waang mai khrap',tr:'Bos randevu var mı?',bd:[{ro:'mii nat waang mai',tr:'boş randevu var mı',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
        {th:'มีล่ามภาษาตุรกีไหมครับ',ro:'mii laam phaa-saa tu-ra-gii mai khrap',tr:'Türkce tercüman var mı?',bd:[{ro:'mii laam phaa-saa tu-ra-gii mai',tr:'Türkçe tercüman var mı',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
      ]
    },
    {
      title:'2. PEN ... = ... olmak / ... hastaliginiz var',
      formula:'[ÖZNE] + PEN + [HASTALIK/DURUM] = ... var / ... olmuş',
      explain:'"Pen" = olmak/sahip olmak (hastalık bağlamında). "Pom pen khai" = ateşim var. Hastalıkları anlatmak için kullanılır.',
      tips:['"pen" hastalık/durum kelimesinin önüne gelir','Olumsuz: mai pen = olmak degil / önemli değil','pen a-rai = ne oldu? / ne var?','pen yang-ngai bang = nasılsın?','"mai pen rai" = önemli değil (yaygın ifade)'],
      examples:[
        {th:'ผมเป็นไข้ครับ',ro:'pom pen khai khrap',tr:'Atesim var.',bd:[{ro:'pom',tr:'ben',role:'S - Ozne'},{ro:'pen khai',tr:'ateş var / ateşim var',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
        {th:'เป็นหวัดครับ',ro:'pen wat khrap',tr:'Nezlem var.',bd:[{ro:'pen wat',tr:'nezle var',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
        {th:'คุณเป็นอะไรครับ',ro:'khun pen a-rai khrap',tr:'Neyin var / ne oldu?',bd:[{ro:'khun',tr:'siz/sen',role:'S - Ozne'},{ro:'pen a-rai',tr:'ne var / ne oldu',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
        {th:'ผมเป็นโรคความดันครับ',ro:'pom pen rok khwaam-dan khrap',tr:'Tansiyon hastasıyım.',bd:[{ro:'pom',tr:'ben',role:'S - Ozne'},{ro:'pen rok khwaam-dan',tr:'tansiyon hastası',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
        {th:'ไม่เป็นไรครับ',ro:'mai pen rai khrap',tr:'Önemli degil / sorun yok.',bd:[{ro:'mai pen rai',tr:'önemli değil',role:'Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
      ]
    },
    {
      title:'3. TONG + fiil = ... lazım / ... zorunda',
      formula:'TONG + [FİİL] = ... yapmak zorundayım / ... lazım',
      explain:'"Tong" = zorunda/lazım. Zorunluluk ifadesi. Doktorun talimatlarını aktarmak veya zorunlu durumları anlatmak için kullanılır.',
      tips:['"tong" fiilden önce gelir','mai tong = gerekmez/zorunda değilim','tong pai = gitmem lazım','tong phak-phon = dinlenmem lazım','tong gin yaa = ilaç içmem lazım'],
      examples:[
        {th:'ต้องพบหมอครับ',ro:'tong phop moo khrap',tr:'Doktoru görmem lazım.',bd:[{ro:'tong phop moo',tr:'doktor görmem lazım',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
        {th:'ต้องพักผ่อนครับ',ro:'tong phak-phon khrap',tr:'Dinlenmem lazım.',bd:[{ro:'tong phak-phon',tr:'dinlenmem lazım',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
        {th:'ต้องกินยาทุกวันครับ',ro:'tong gin yaa thuk wan khrap',tr:'Her gün ilaç içmem lazım.',bd:[{ro:'tong gin yaa thuk wan',tr:'her gün ilaç içmem lazım',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
        {th:'ไม่ต้องเข้าโรงพยาบาลครับ',ro:'mai tong khao rong-pha-yaa-baan khrap',tr:'Hastaneye kaldırılmama gerek yok.',bd:[{ro:'mai tong khao rong-pha-yaa-baan',tr:'hastaneye girmek gerekmez',role:'Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
      ]
    },
  ],
  speaking:[
    {task:'Hastanede doktor var mı diye sor',th:'มีหมออยู่ไหมครับ',ro:'mii moo yuu mai khrap',tr:'Doktor var mı?',bd:[{ro:'mii moo yuu mai',tr:'doktor var mı',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Atesinin oldugunu söyle',th:'ผมเป็นไข้ครับ',ro:'pom pen khai khrap',tr:'Atesim var.',bd:[{ro:'pom pen khai',tr:'ateşim var',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Midem agriyor de',th:'ปวดท้องครับ',ro:'puat thong khrap',tr:'Midem ağrıyor.',bd:[{ro:'puat thong',tr:'mide ağrısı',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Agri kesici iste',th:'มียาแก้ปวดไหมครับ',ro:'mii yaa gae puat mai khrap',tr:'Agri kesici var mı?',bd:[{ro:'mii yaa gae puat mai',tr:'ağrı kesici var mı',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'En yakın eczane nerede diye sor',th:'ร้านขายยาใกล้ที่สุดอยู่ที่ไหนครับ',ro:'raan-khaai-yaa glai-thii-sut yuu thii-nai khrap',tr:'En yakın eczane nerede?',bd:[{ro:'raan-khaai-yaa glai-thii-sut yuu thii-nai',tr:'en yakın eczane nerede',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Basın agridigini söyle',th:'ปวดหัวครับ',ro:'puat hua khrap',tr:'Basım ağrıyor.',bd:[{ro:'puat hua',tr:'baş ağrısı',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Penisiline alerjin oldugunu söyle',th:'ผมแพ้เพนนิซิลินครับ',ro:'pom phae pen-ni-si-lin khrap',tr:'Penisiline alerjim var.',bd:[{ro:'pom phae pen-ni-si-lin',tr:'penisiline alerjim var',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Doktor randevusu almak istedigini söyle',th:'ขอนัดหมอครับ',ro:'khor nat moo khrap',tr:'Doktor randevusu almak istiyorum.',bd:[{ro:'khor nat moo',tr:'doktor randevusu',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Ates düsürücü var mı diye sor',th:'มียาลดไข้ไหมครับ',ro:'mii yaa lot khai mai khrap',tr:'Ates düsürücü var mı?',bd:[{ro:'mii yaa lot khai mai',tr:'ateş düşürücü var mı',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Doktoru görmem lazım de',th:'ต้องพบหมอครับ',ro:'tong phop moo khrap',tr:'Doktoru görmem lazım.',bd:[{ro:'tong phop moo',tr:'doktor görmem lazım',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Ishalin oldugunu söyle',th:'ท้องเสียครับ',ro:'thong sia khrap',tr:'Ishalim var.',bd:[{ro:'thong sia',tr:'ishal',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Doktor ingilizce biliyor mu diye sor',th:'หมอพูดภาษาอังกฤษได้ไหมครับ',ro:'moo phuut phaa-saa ang-grit dai mai khrap',tr:'Doktor Ingilizce konuşabilir mi?',bd:[{ro:'moo phuut phaa-saa ang-grit dai mai',tr:'doktor İngilizce konuşabilir mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
  ],
  dialogues:[
    {title:'🏥 Hastane Kayit',
     lines:[
       {s:'Tom',th:'สวัสดีครับ ผมปวดหัวและเป็นไข้ครับ',ro:'sa-wat-dee khrap pom puat-hua lae pen khai khrap',tr:'Merhaba, basım ağrıyor ve atesim var.',bd:[{ro:'sa-wat-dee',tr:'merhaba',role:'Kelime'},{ro:'pom puat-hua lae pen khai',tr:'baş ağrısı ve ateş var',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {s:'Lucy',th:'มีนัดไหมคะ',ro:'mii nat mai kha',tr:'Randevunuz var mı?',bd:[{ro:'mii nat mai',tr:'randevu var mı',role:'Soru/Olumsuz'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
       {s:'Tom',th:'ไม่มีครับ ขอพบหมอได้ไหมครับ',ro:'mai mii khrap khor phop moo dai mai khrap',tr:'Yok, doktoru görebilir miyim?',bd:[{ro:'mai mii',tr:'yok',role:'Olumsuz'},{ro:'khor phop moo dai mai',tr:'doktoru görebilir miyim',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {s:'Lucy',th:'ได้ค่ะ รอประมาณสามสิบนาทีนะคะ',ro:'dai kha ro pra-maan saam-sip naa-thii na kha',tr:'Tabii, yaklasik 30 dakika bekleyin.',bd:[{ro:'dai',tr:'olur',role:'Kelime'},{ro:'ro pra-maan saam-sip naa-thii',tr:'30 dakika bekleyin',role:'V - Yuklem'},{ro:'na kha',tr:'onay eki',role:'Kibar'}]},
       {s:'Tom',th:'ขอบคุณครับ',ro:'khob-khun khrap',tr:'Tesekkür ederim.',bd:[{ro:'khob-khun',tr:'teşekkür',role:'Kelime'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {title:'💊 Eczanede Ilaç Almak',
     lines:[
       {s:'Tom',th:'มียาแก้ปวดหัวไหมครับ',ro:'mii yaa gae puat-hua mai khrap',tr:'Bas ağrısı ilacı var mı?',bd:[{ro:'mii yaa gae puat-hua mai',tr:'baş ağrısı ilacı var mı',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {s:'Lucy',th:'มีค่ะ พาราเซตามอลเป็นไงคะ',ro:'mii kha phaa-raa-set-aa-mon pen ngai kha',tr:'Var, parasetamol olur mu?',bd:[{ro:'mii',tr:'var',role:'Kelime'},{ro:'phaa-raa-set-aa-mon pen ngai',tr:'parasetamol olur mu',role:'Soru/Olumsuz'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
       {s:'Tom',th:'ได้ครับ และยาลดไข้ด้วยครับ',ro:'dai khrap lae yaa lot khai duay khrap',tr:'Tamam, bir de ates düsürücü lütfen.',bd:[{ro:'dai',tr:'tamam/olur',role:'Kelime'},{ro:'lae yaa lot khai duay',tr:'bir de ateş düşürücü',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {s:'Lucy',th:'กินวันละสามครั้ง หลังอาหารนะคะ',ro:'gin wan-la saam khrang lang aa-haan na kha',tr:'Günde üç kez, yemekten sonra alın.',bd:[{ro:'gin wan-la saam khrang',tr:'günde üç kez al',role:'V - Yuklem'},{ro:'lang aa-haan',tr:'yemekten sonra',role:'Zaman'},{ro:'na kha',tr:'onay eki',role:'Kibar'}]},
     ]},
    {title:'🤒 Doktor Muayenesi',
     lines:[
       {s:'Lucy',th:'เป็นอะไรบ้างคะ',ro:'pen a-rai bang kha',tr:'Ne sikayet var?',bd:[{ro:'pen a-rai bang',tr:'ne şikayet',role:'Soru/Olumsuz'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
       {s:'Tom',th:'ปวดท้องและท้องเสียครับ เป็นสองวันแล้วครับ',ro:'puat thong lae thong sia khrap pen song wan laeo khrap',tr:'Karin agrim ve ishalim var, iki gündür.',bd:[{ro:'puat thong lae thong sia',tr:'karın ağrısı ve ishal',role:'V - Yuklem'},{ro:'pen song wan laeo',tr:'iki gündür',role:'Zaman'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {s:'Lucy',th:'แพ้ยาอะไรบ้างคะ',ro:'phae yaa a-rai bang kha',tr:'Hangi ilaçlara alerjisiniz?',bd:[{ro:'phae yaa a-rai bang',tr:'hangi ilaçlara alerji',role:'Soru/Olumsuz'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
       {s:'Tom',th:'ไม่แพ้ยาอะไรครับ',ro:'mai phae yaa a-rai khrap',tr:'Hiçbir ilaca alerjim yok.',bd:[{ro:'mai phae yaa a-rai',tr:'hiçbir ilaca alerji yok',role:'Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {s:'Lucy',th:'ต้องพักผ่อนและดื่มน้ำมากๆ นะคะ',ro:'tong phak-phon lae duem naam maak-maak na kha',tr:'Dinlenin ve bol su için.',bd:[{ro:'tong phak-phon',tr:'dinlen lazım',role:'V - Yuklem'},{ro:'lae duem naam maak-maak',tr:'ve bol su iç',role:'V - Yuklem'},{ro:'na kha',tr:'onay eki',role:'Kibar'}]},
     ]},
    {title:'📅 Randevu Almak',
     lines:[
       {s:'Tom',th:'ขอนัดหมอได้ไหมครับ',ro:'khor nat moo dai mai khrap',tr:'Doktor randevusu alabilir miyim?',bd:[{ro:'khor nat moo dai mai',tr:'doktor randevusu alabilir miyim',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {s:'Lucy',th:'ได้ค่ะ วันพรุ่งนี้บ่ายสองได้ไหมคะ',ro:'dai kha wan phrung-nii baai-song dai mai kha',tr:'Tabii, yarın saat 14:00 olur mu?',bd:[{ro:'dai',tr:'olur',role:'Kelime'},{ro:'wan phrung-nii baai-song dai mai',tr:'yarın 14:00 olur mu',role:'Soru/Olumsuz'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
       {s:'Tom',th:'ได้ครับ ขอบคุณครับ',ro:'dai khrap khob-khun khrap',tr:'Tamam, tesekkürler.',bd:[{ro:'dai',tr:'tamam',role:'Kelime'},{ro:'khob-khun',tr:'teşekkür',role:'Kelime'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {s:'Lucy',th:'นัดไว้เรียบร้อยค่ะ ชื่ออะไรคะ',ro:'nat wai riap-roi kha chue a-rai kha',tr:'Randevu ayarlandi. Adınız ne?',bd:[{ro:'nat wai riap-roi',tr:'randevu ayarlandı',role:'V - Yuklem'},{ro:'chue a-rai',tr:'adı ne',role:'Soru/Olumsuz'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
     ]},
  ],
  listening:[
    {th:'ผมเป็นไข้ครับ',ro:'pom pen khai khrap',tr:'Atesim var.',bd:[{ro:'pom pen khai',tr:'ateşim var',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {th:'ปวดหัวมากครับ',ro:'puat hua maak khrap',tr:'Basım çok ağrıyor.',bd:[{ro:'puat hua maak',tr:'baş çok ağrıyor',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {th:'มียาแก้ปวดไหมครับ',ro:'mii yaa gae puat mai khrap',tr:'Agri kesici var mı?',bd:[{ro:'mii yaa gae puat mai',tr:'ağrı kesici var mı',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {th:'โรงพยาบาลอยู่ที่ไหนครับ',ro:'rong-pha-yaa-baan yuu thii-nai khrap',tr:'Hastane nerede?',bd:[{ro:'rong-pha-yaa-baan yuu thii-nai',tr:'hastane nerede',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {th:'ท้องเสียครับ สองวันแล้ว',ro:'thong sia khrap song wan laeo',tr:'Ishalim var, iki gündür.',bd:[{ro:'thong sia',tr:'ishal',role:'V - Yuklem'},{ro:'song wan laeo',tr:'iki gündür',role:'Zaman'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {th:'ผมแพ้เพนนิซิลินครับ',ro:'pom phae pen-ni-si-lin khrap',tr:'Penisiline alerjim var.',bd:[{ro:'pom phae pen-ni-si-lin',tr:'penisiline alerjim var',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {th:'กินยาวันละสามครั้งหลังอาหารค่ะ',ro:'gin yaa wan-la saam khrang lang aa-haan kha',tr:'Günde üç kez, yemekten sonra alın.',bd:[{ro:'gin yaa wan-la saam khrang lang aa-haan',tr:'günde üç kez yemekten sonra',role:'V - Yuklem'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
    {th:'ต้องพักผ่อนครับ',ro:'tong phak-phon khrap',tr:'Dinlenmem lazım.',bd:[{ro:'tong phak-phon',tr:'dinlenmem lazım',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {th:'ขอนัดหมอครับ',ro:'khor nat moo khrap',tr:'Doktor randevusu istiyorum.',bd:[{ro:'khor nat moo',tr:'doktor randevusu istiyorum',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {th:'ไข้ลดแล้วครับ รู้สึกดีขึ้น',ro:'khai lot laeo khrap ruu-suek dii khuen',tr:'Ates düstü, daha iyi hissediyorum.',bd:[{ro:'khai lot laeo',tr:'ateş düştü',role:'V - Yuklem'},{ro:'ruu-suek dii khuen',tr:'daha iyi hissediyorum',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
  ],
  quiz:[
    {q:'"rong-pha-yaa-baan" ne demek?',opts:['Eczane','Klinik','Hastane','Doktor odası'],c:2},
    {q:'"raan-khaai-yaa" ne demek?',opts:['Market','Eczane','Hastane','Berber'],c:1},
    {q:'"jep" ne demek?',opts:['Kaşıntı','Ates','Agri/aci duymak','Öksürmek'],c:2},
    {q:'"moo" ne demek?',opts:['Hemşire','Hasta','Doktor','Eczacı'],c:2},
    {q:'"yaa" ne demek?',opts:['Enjeksiyon','Ilaç','Muayene','Bandaj'],c:1},
    {q:'"puat hua" ne demek?',opts:['Mide ağrısı','Diş ağrısı','Sırt ağrısı','Baş ağrısı'],c:3},
    {q:'"khai" ne demek?',opts:['Öksürük','Ates','Ishal','Baş dönmesi'],c:1},
    {q:'"phae" ne demek?',opts:['Ağrı','Kaşıntı','Alerji','Sekillik'],c:2},
    {q:'"nat" ne demek?',opts:['Fatura','Randevu','Muayene','Recete'],c:1},
    {q:'"thong sia" ne demek?',opts:['Karın şişkinliği','Mide ağrısı','Ishal','Bulantı'],c:2},
    {q:'"mii yaa gae puat mai" ne demek?',opts:['Ilaç aldım','Agri kesici var mı','Ilaç pahalı mı','Ates düsürücü nerede'],c:1},
    {q:'"pom pen khai" ne demek?',opts:['Doktorum var','Hastaneye gidiyorum','Atesim var','Ilaç içiyorum'],c:2},
    {q:'"tong phop moo" ne demek?',opts:['Doktor arıyorum','Doktoru gördüm','Doktoru görmem lazım','Doktor geldi'],c:2},
    {q:'"thong" ne demek?',opts:['Baş','Gögs','Sırt','Karın/mide'],c:3},
    {q:'"gin yaa wan-la saam khrang" ne demek?',opts:['Günde bir kez ilaç','Günde iki kez ilaç','Günde üç kez ilaç','Haftada üç kez'],c:2},
    {q:'"mai phae yaa a-rai" ne demek?',opts:['Ilaca alerjim var','Hiçbir ilaca alerjim yok','Penisiline alerjim','Alerji testim var'],c:1},
    {q:'Phuket en iyi özel hastanesi hangisidir?',opts:['Vachira Hospital','Bangkok Hospital Phuket','Samitivej Hospital','Bumrungrad Hospital'],c:1},
    {q:'"lang aa-haan" ne demek?',opts:['Yemekten önce','Aç karnına','Yemekten sonra','Geceleri'],c:2},
    {q:'"yaa lot khai" ne demek?',opts:['Agri kesici','Antibiyotik','Ates düsürücü','Vitamin'],c:2},
    {q:'"mai pen rai" ne demek?',opts:['Çok ağrıyor','Önemli degil/sorun yok','Ilaç içmiyorum','Hastane istemiyorum'],c:1},
  ],
};

LESSONS[11] = L11;
