// Ders 29 verisi — CORE 2000 (644-710)
const L29 = {
  words:[
    {id:'c644',ro:'chaan-muueang',tr:'banliyö',en:'suburb',tip:'',ctx:'',examples:[]},
    {id:'c645',ro:'hawng',tr:'oda',en:'room',tip:'',ctx:'',examples:[]},
    {id:'c646',ro:'phlaae',tr:'yakmak',en:'burn',tip:'',ctx:'',examples:[]},
    {id:'c647',ro:'maak-ruk',tr:'satranç',en:'chess',tip:'',ctx:'',examples:[]},
    {id:'c648',ro:'phaa-saa',tr:'dil',en:'language',tip:'',ctx:'',examples:[]},
    {id:'c649',ro:'bpao',tr:'çok kuru',en:'ow-dry',tip:'',ctx:'',examples:[]},
    {id:'c650',ro:'bpawng-gan-dtuua',tr:'dövüş sanatları',en:'martial arts',tip:'',ctx:'',examples:[]},
    {id:'c651',ro:'phaaw-jai',tr:'memnun',en:'satisfied',tip:'',ctx:'',examples:[]},
    {id:'c652',ro:'sa-ngop',tr:'sakinlik',en:'calm',tip:'',ctx:'',examples:[]},
    {id:'c654',ro:'gluua',tr:'gargara',en:'gargle',tip:'',ctx:'',examples:[]},
    {id:'c655',ro:'mai',tr:'memnun değil',en:'dissatisfied',tip:'',ctx:'',examples:[]},
    {id:'c657',ro:'saam-phan',tr:'üç bin',en:'three thousand',tip:'',ctx:'',examples:[]},
    {id:'c658',ro:'hok-phan',tr:'altı bin',en:'six thousand',tip:'',ctx:'',examples:[]},
    {id:'c660',ro:'gao-phan',tr:'dokuz bin',en:'nine thousand',tip:'',ctx:'',examples:[]},
    {id:'c661',ro:'gu-taap',tr:'gül',en:'rose',tip:'',ctx:'',examples:[]},
    {id:'c662',ro:'daawk-mai',tr:'çiçek ben',en:'flower I',tip:'',ctx:'',examples:[]},
    {id:'c664',ro:'daawk-thaan-dta-wan',tr:'ayçiçeği',en:'sunflower',tip:'',ctx:'',examples:[]},
    {id:'c665',ro:'daawk-daaen-di-lai',tr:'ah karahindiba',en:'aawn dandelion',tip:'',ctx:'',examples:[]},
    {id:'c666',ro:'gaan',tr:'seyahat',en:'traveling',tip:'',ctx:'',examples:[]},
    {id:'c667',ro:'aawk-gam-lang-gaai',tr:'egzersiz yapmak',en:'exercising',tip:'',ctx:'',examples:[]},
    {id:'c668',ro:'gaai',tr:'antrenman yapmak',en:'workout',tip:'',ctx:'',examples:[]},
    {id:'c669',ro:'gaan',tr:'okuma',en:'reading',tip:'',ctx:'',examples:[]},
    {id:'c672',ro:'sauy-khaaw',tr:'kolye',en:'necklace',tip:'',ctx:'',examples:[]},
    {id:'c673',ro:'waaen',tr:'yüzük',en:'ring',tip:'',ctx:'',examples:[]},
    {id:'c674',ro:'gaang-geeng',tr:'boxer külot',en:'boxer shorts',tip:'',ctx:'',examples:[]},
    {id:'c675',ro:'gra-bproong',tr:'etek',en:'skirt',tip:'',ctx:'',examples:[]},
    {id:'c678',ro:'phft-saa',tr:'pizza',en:'pizza',tip:'',ctx:'',examples:[]},
    {id:'c679',ro:'hawt-dawk',tr:'sosisli sandviç',en:'hot dog',tip:'',ctx:'',examples:[]},
    {id:'c680',ro:'thfp',tr:'uç',en:'tip',tip:'',ctx:'',examples:[]},
    {id:'c682',ro:'phaa-yu-dtai-fun',tr:'tayfun',en:'typhoon',tip:'',ctx:'',examples:[]},
    {id:'c683',ro:'phaa-yu-hooe-rf-kheen',tr:'kasırga',en:'hurricane',tip:'',ctx:'',examples:[]},
    {id:'c685',ro:'phai',tr:'kuraklık',en:'drought',tip:'',ctx:'',examples:[]},
    {id:'c686',ro:'saat-sa-naa',tr:'İslâm',en:'Islam',tip:'',ctx:'',examples:[]},
    {id:'c687',ro:'gaai',tr:'veri Protestanlık',en:'dtaen Protestantism',tip:'',ctx:'',examples:[]},
    {id:'c688',ro:'gaai',tr:'thaaw-lik Katoliklik',en:'thaaw-lik Catholicism',tip:'',ctx:'',examples:[]},
    {id:'c689',ro:'saat-sa-naa',tr:'Hinduizm',en:'Hinduism',tip:'',ctx:'',examples:[]},
    {id:'c690',ro:'saat-sa-naa',tr:'Budizm',en:'Buddhism',tip:'',ctx:'',examples:[]},
    {id:'c691',ro:'khaaw-thaao',tr:'bilek',en:'ankle',tip:'',ctx:'',examples:[]},
    {id:'c692',ro:'khaaw-saawk',tr:'dirsek',en:'elbow',tip:'',ctx:'',examples:[]},
    {id:'c693',ro:'khaaw-muue',tr:'bilek',en:'wrist',tip:'',ctx:'',examples:[]},
    {id:'c696',ro:'goon',tr:'tıraş olmak',en:'shave',tip:'',ctx:'',examples:[]},
    {id:'c697',ro:'phaaw-khruua',tr:'şef',en:'chef',tip:'',ctx:'',examples:[]},
    {id:'c701',ro:'tham-dtaaek',tr:'kırmak',en:'break',tip:'',ctx:'',examples:[]},
    {id:'c702',ro:'phlaae',tr:'kesmek',en:'cut',tip:'',ctx:'',examples:[]},
    {id:'c703',ro:'tham',tr:'burkulma',en:'sprain',tip:'',ctx:'',examples:[]},
    {id:'c704',ro:'weep',tr:'mikrodalga fırın',en:'microwave oven',tip:'',ctx:'',examples:[]},
    {id:'c707',ro:'nguuea',tr:'ter',en:'sweat',tip:'',ctx:'',examples:[]},
    {id:'c708',ro:'chek',tr:'giriş',en:'check in',tip:'',ctx:'',examples:[]},
    {id:'c709',ro:'hawng-phak',tr:'oda numarası',en:'room number',tip:'',ctx:'',examples:[]},
    {id:'c710',ro:'gun-jaae',tr:'oda anahtarı',en:'room key',tip:'',ctx:'',examples:[]},
  ]
};

LESSONS[29] = L29;
