// Ders 32 verisi — CORE 2000 (838-895)
const L32 = {
  words:[
    {id:'c838',ro:'bpiia-noo',tr:'piyano',en:'piano',tip:'',ctx:'',examples:[]},
    {id:'c839',ro:'thfiao-bin',tr:'uçuş numarası',en:'flight number',tip:'',ctx:'',examples:[]},
    {id:'c840',ro:'ga-seet-dtra-gam',tr:'tarım',en:'agriculture',tip:'',ctx:'',examples:[]},
    {id:'c841',ro:'gaan',tr:'enfeksiyon',en:'infection',tip:'',ctx:'',examples:[]},
    {id:'c843',ro:'thram-bpet',tr:'trompet',en:'trumpet',tip:'',ctx:'',examples:[]},
    {id:'c844',ro:'bpra-dtuu',tr:'kalkış kapısı',en:'departure gate',tip:'',ctx:'',examples:[]},
    {id:'c845',ro:'sang-khom-wft-tha-yaa',tr:'sosyoloji',en:'sociology',tip:'',ctx:'',examples:[]},
    {id:'c846',ro:'dtaawn-rap',tr:'uçuş görevlisi',en:'flight attendant',tip:'',ctx:'',examples:[]},
    {id:'c847',ro:'thfi-nang',tr:'koltuk',en:'seat',tip:'',ctx:'',examples:[]},
    {id:'c848',ro:'yaa',tr:'ilaç',en:'medicine',tip:'',ctx:'',examples:[]},
    {id:'c849',ro:'chan-bpra-yat',tr:'ekonomi sınıfı',en:'economy class',tip:'',ctx:'',examples:[]},
    {id:'c850',ro:'thfiaa-bin',tr:'uçuş',en:'flight',tip:'',ctx:'',examples:[]},
    {id:'c851',ro:'saek-saa-faan',tr:'saksafon',en:'saxophone',tip:'',ctx:'',examples:[]},
    {id:'c852',ro:'glaawng',tr:'davul',en:'drums',tip:'',ctx:'',examples:[]},
    {id:'c853',ro:'hiip-phleeng-bpaak',tr:'armonika',en:'harmonica',tip:'',ctx:'',examples:[]},
    {id:'c854',ro:'hawng-phak',tr:'oda servisi',en:'room service',tip:'',ctx:'',examples:[]},
    {id:'c855',ro:'bai-set-rap-ngoen',tr:'fiş',en:'receipt',tip:'',ctx:'',examples:[]},
    {id:'c858',ro:'saawng-jot-maai',tr:'mektup',en:'envelope',tip:'',ctx:'',examples:[]},
    {id:'c859',ro:'gra-daat',tr:'kağıt',en:'paper',tip:'',ctx:'',examples:[]},
    {id:'c860',ro:'man',tr:'angaje etmek',en:'engage',tip:'',ctx:'',examples:[]},
    {id:'c861',ro:'khii-baawt',tr:'klavye ben',en:'keyboard I',tip:'',ctx:'',examples:[]},
    {id:'c862',ro:'phuuen',tr:'döküntü ben',en:'rash I',tip:'',ctx:'',examples:[]},
    {id:'c863',ro:'aa-gaan',tr:'bulantı',en:'nausea',tip:'',ctx:'',examples:[]},
    {id:'c865',ro:'bping-bpawng',tr:'masa tenisi',en:'ping pong',tip:'',ctx:'',examples:[]},
    {id:'c866',ro:'gaan',tr:'koşma',en:'running',tip:'',ctx:'',examples:[]},
    {id:'c867',ro:'dii-wii-dii',tr:'DVD',en:'DVD',tip:'',ctx:'',examples:[]},
    {id:'c869',ro:'thfi-yep-gra-daat',tr:'zımba',en:'stapler',tip:'',ctx:'',examples:[]},
    {id:'c870',ro:'dtaeng-ngaan',tr:'evlenmek',en:'marry',tip:'',ctx:'',examples:[]},
    {id:'c872',ro:'aa-gaan',tr:'kaşıntı',en:'itch',tip:'',ctx:'',examples:[]},
    {id:'c873',ro:'jep-khaaw',tr:'boğaz ağrısı',en:'sore throat',tip:'',ctx:'',examples:[]},
    {id:'c874',ro:'beet-bawn',tr:'beyzbol',en:'baseball',tip:'',ctx:'',examples:[]},
    {id:'c875',ro:'hawk-gfi-nam-khaeng',tr:'buz hokeyi',en:'ice hockey',tip:'',ctx:'',examples:[]},
    {id:'c876',ro:'gaan',tr:'kayak yapma',en:'skiing',tip:'',ctx:'',examples:[]},
    {id:'c879',ro:'suue',tr:'satın almak',en:'buy',tip:'',ctx:'',examples:[]},
    {id:'c880',ro:'maa-drit',tr:'Madrid',en:'Madrid',tip:'',ctx:'',examples:[]},
    {id:'c881',ro:'mii',tr:'burun akması',en:'runny nose',tip:'',ctx:'',examples:[]},
    {id:'c882',ro:'wiian',tr:'başı dönmek',en:'dizzy',tip:'',ctx:'',examples:[]},
    {id:'c883',ro:'khat',tr:'burun tıkanıklığı',en:'stuffy nose',tip:'',ctx:'',examples:[]},
    {id:'c884',ro:'wawn-fee-bawn',tr:'voleybol',en:'volleyball',tip:'',ctx:'',examples:[]},
    {id:'c885',ro:'gaawp',tr:'eğer',en:'lf',tip:'',ctx:'',examples:[]},
    {id:'c886',ro:'muuai',tr:'boks',en:'boxing',tip:'',ctx:'',examples:[]},
    {id:'c887',ro:'dooen-thaang',tr:'seyahat',en:'travel',tip:'',ctx:'',examples:[]},
    {id:'c888',ro:'jop',tr:'mezun olmak',en:'graduate',tip:'',ctx:'',examples:[]},
    {id:'c889',ro:'yaai',tr:'taşınmak',en:'move',tip:'',ctx:'',examples:[]},
    {id:'c890',ro:'niu-dee-lii',tr:'Yeni Delhi',en:'New Delhi',tip:'',ctx:'',examples:[]},
    {id:'c891',ro:'lawp-bfi',tr:'lobi',en:'lobby',tip:'',ctx:'',examples:[]},
    {id:'c892',ro:'baaw-rf-gaan',tr:'makyaj servisi',en:'ake-up service',tip:'',ctx:'',examples:[]},
    {id:'c893',ro:'haawng',tr:'süit',en:'suite',tip:'',ctx:'',examples:[]},
    {id:'c894',ro:'bpan',tr:'bisikletçilik',en:'cycling',tip:'',ctx:'',examples:[]},
    {id:'c895',ro:'khaeng',tr:'otomobil yarışı',en:'auto racing',tip:'',ctx:'',examples:[]},
  ]
};

LESSONS[32] = L32;
