// === DERS14.JS START ===
// Ders 14 verisi — tayca-v3
// =================== VERİ: DERS 14 — Sosyallesme ===================
const L14 = {
  tones:[],
  words:[
    {id:'w1',th:'สนุก',ro:'sa-nuk',tr:'Eglenceli / Eglenmek',
     tip:'"Sa-nuk" = eglence/keyif. Taylar icin cok onemli bir kavram. "Sa-nuk mak" = cok eglenceli.',
     ctx:'Phuket\te partiler, plaj, aktiviteler icin sik kullanilir.',
     examples:[
       {th:'สนุกมากครับ',ro:'sa-nuk maak khrap',tr:'Cok eglenceli.',bd:[{ro:'sa-nuk maak',tr:'cok eglenceli',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'คืนนี้สนุกมากครับ',ro:'khuean-nii sa-nuk maak khrap',tr:'Bu gece cok eglenceli.',bd:[{ro:'khuean-nii sa-nuk maak',tr:'bu gece cok eglenceli',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'สนุกไหมครับ',ro:'sa-nuk mai khrap',tr:'Egleniyor musunuz?',bd:[{ro:'sa-nuk mai',tr:'egleniyor musunuz',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'อยากสนุกครับ',ro:'yaak sa-nuk khrap',tr:'Eglenmek istiyorum.',bd:[{ro:'yaak sa-nuk',tr:'eglemek istiyorum',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w2',th:'เพื่อน',ro:'phuean',tr:'Arkadas',
     tip:'"Phuean" = arkadas. "Phuean-san-nit" = en iyi arkadas. Cok kullanilan kelime.',
     ctx:'Yeni arkadaslar edinmek icin temel kelime.',
     examples:[
       {th:'เพื่อนผมชื่อลูซี่ครับ',ro:'phuean pom chuea Lucy khrap',tr:'Arkadasimin adi Lucy.',bd:[{ro:'phuean pom chuea Lucy',tr:'arkadasimin adi Lucy',role:'Kelime'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ไปกับเพื่อนครับ',ro:'pai gap phuean khrap',tr:'Arkadasimla gidiyorum.',bd:[{ro:'pai gap phuean',tr:'arkadasimla gidiyorum',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'มีเพื่อนไทยไหมครับ',ro:'mii phuean Thai mai khrap',tr:'Tayli arkadasiniz var mi?',bd:[{ro:'mii phuean Thai mai',tr:'tayli arkadas var mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'เพื่อนดีมากครับ',ro:'phuean dii maak khrap',tr:'Arkadas cok iyi.',bd:[{ro:'phuean dii maak',tr:'arkadas cok iyi',role:'Kelime'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w3',th:'ดื่ม',ro:'duem',tr:'Icmek',
     tip:'"Duem" = icmek (buyukler icin, ozellikle alkol veya icecek). "Gin" de icmek demektir ama daha genel.',
     ctx:'Bar, restoran, partilerde en cok kullanilan fiil.',
     examples:[
       {th:'ดื่มอะไรดีครับ',ro:'duem a-rai dii khrap',tr:'Ne icmek istersiniz?',bd:[{ro:'duem a-rai dii',tr:'ne icmek istersiniz',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ดื่มเบียร์ไหมครับ',ro:'duem bia mai khrap',tr:'Bira iceriz mi?',bd:[{ro:'duem bia mai',tr:'bira iceriz mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ดื่มไม่เป็นครับ',ro:'duem mai-pen khrap',tr:'Icmiyorum (alkol).',bd:[{ro:'duem mai-pen',tr:'icmiyorum',role:'Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ดื่มน้ำเปล่าดีกว่าครับ',ro:'duem naam-plao dii-gwaa khrap',tr:'Sade su icmek daha iyi.',bd:[{ro:'duem naam-plao dii-gwaa',tr:'sade su daha iyi',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w4',th:'ปาร์ตี้',ro:'paa-tii',tr:'Parti',
     tip:'Ingilizce\'den gecme. "Paa-tii" veya "ngaan" (= etkinlik/doğum gunu) da kullanilabilir.',
     ctx:'Phuket\te plaj partileri ve barlar icin.',
     examples:[
       {th:'มีปาร์ตี้คืนนี้ครับ',ro:'mii paa-tii khuean-nii khrap',tr:'Bu gece parti var.',bd:[{ro:'mii paa-tii khuean-nii',tr:'bu gece parti var',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ไปปาร์ตี้ด้วยกันไหมครับ',ro:'pai paa-tii duay-gan mai khrap',tr:'Birlikte partiye gidelim mi?',bd:[{ro:'pai paa-tii duay-gan mai',tr:'birlikte partiye gidelim mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ปาร์ตี้ที่ไหนครับ',ro:'paa-tii thii-nai khrap',tr:'Parti nerede?',bd:[{ro:'paa-tii thii-nai',tr:'parti nerede',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ปาร์ตี้สนุกมากครับ',ro:'paa-tii sa-nuk maak khrap',tr:'Parti cok eglenceli.',bd:[{ro:'paa-tii sa-nuk maak',tr:'parti cok eglenceli',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w5',th:'เต้น',ro:'ten',tr:'Dans etmek',
     tip:'"Ten" = dans. "Ten ram" = koreografili dans. Patong gece hayatinda cok kullanilir.',
     ctx:'Bar ve diskoteklerde dans icin.',
     examples:[
       {th:'เต้นด้วยกันไหมครับ',ro:'ten duay-gan mai khrap',tr:'Birlikte dans edelim mi?',bd:[{ro:'ten duay-gan mai',tr:'birlikte dans edelim mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'เต้นเป็นไหมครับ',ro:'ten pen mai khrap',tr:'Dans edebilir misiniz?',bd:[{ro:'ten pen mai',tr:'dans edebilir misiniz',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ผมเต้นไม่เป็นครับ',ro:'pom ten mai-pen khrap',tr:'Dans edemiyorum.',bd:[{ro:'pom ten mai-pen',tr:'dans edemiyorum',role:'Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'เต้นสนุกมากครับ',ro:'ten sa-nuk maak khrap',tr:'Dans etmek cok eglenceli.',bd:[{ro:'ten sa-nuk maak',tr:'dans etmek eglenceli',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w6',th:'นัดหมาย',ro:'nat-maai',tr:'Randevu / Bulusma planlamak',
     tip:'"Nat" = belirleme, "maai" = isaret. "Nat kan" = bulusmak. Kisa hali "nat" de kullanilir.',
     ctx:'Arkadaslarla veya is toplantilari icin randevu alirken.',
     examples:[
       {th:'นัดหมายไว้ครับ',ro:'nat-maai wai khrap',tr:'Randevum var.',bd:[{ro:'nat-maai wai',tr:'randevu var',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'นัดหมายกันวันเสาร์ไหมครับ',ro:'nat-maai gan wan-sao mai khrap',tr:'Cumartesi bulusalim mi?',bd:[{ro:'nat-maai gan wan-sao mai',tr:'cumartesi bulusalim mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'นัดหมายเปลี่ยนได้ไหมครับ',ro:'nat-maai plian dai mai khrap',tr:'Randevuyu degistirebilir miyiz?',bd:[{ro:'nat-maai plian dai mai',tr:'randevu degistirilebilir mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w7',th:'ดีใจ',ro:'dii-jai',tr:'Mutlu / Sevindim',
     tip:'"Dii" = iyi, "jai" = kalp/his. "Dii-jai maak" = cok mutluyum. Samimi duygu ifadesi.',
     ctx:'Arkadas bulusmalari, iyi haberler, davet kabulleri icin.',
     examples:[
       {th:'ดีใจที่ได้เจอครับ',ro:'dii-jai thii dai joa khrap',tr:'Sizi gorduğume sevindim.',bd:[{ro:'dii-jai thii dai joa',tr:'sizi gorduğume sevindim',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ดีใจมากครับ',ro:'dii-jai maak khrap',tr:'Cok mutluyum.',bd:[{ro:'dii-jai maak',tr:'cok mutluyum',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ดีใจที่คุณมาครับ',ro:'dii-jai thii khun maa khrap',tr:'Geldiginize sevindim.',bd:[{ro:'dii-jai thii khun maa',tr:'geldiginize sevindim',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ดีใจด้วยนะครับ',ro:'dii-jai duay na khrap',tr:'Tebrikler (ben de mutluyum).',bd:[{ro:'dii-jai duay na',tr:'tebrikler',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w8',th:'ไปด้วยกัน',ro:'pai-duay-gan',tr:'Birlikte gitmek',
     tip:'"Pai" = gitmek, "duay" = ile, "gan" = birlikte. "Pai ... duay-gan" = birlikte ... gidelim.',
     ctx:'Arkadaslari bir yere davet etmek icin.',
     examples:[
       {th:'ไปด้วยกันไหมครับ',ro:'pai-duay-gan mai khrap',tr:'Birlikte gidelim mi?',bd:[{ro:'pai-duay-gan mai',tr:'birlikte gidelim mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ไปกินข้าวด้วยกันครับ',ro:'pai gin khao duay-gan khrap',tr:'Birlikte yemek yemeye gidelim.',bd:[{ro:'pai gin khao duay-gan',tr:'birlikte yemek yemeye gidelim',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ไปด้วยกันได้เลยครับ',ro:'pai-duay-gan dai loey khrap',tr:'Hemen birlikte gidebiliriz.',bd:[{ro:'pai-duay-gan dai loey',tr:'hemen birlikte gidebiliriz',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ไปด้วยกันสนุกกว่าครับ',ro:'pai-duay-gan sa-nuk gwaa khrap',tr:'Birlikte gitmek daha eglenceli.',bd:[{ro:'pai-duay-gan sa-nuk gwaa',tr:'birlikte gitmek daha eglenceli',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w9',th:'เจอกัน',ro:'joa-gan',tr:'Bulusmak / Gorüsmek',
     tip:'"Joa" = karsilasmak/gormek, "gan" = birlikte. "Joa gan wan-sao" = cumartesi bulusuruz.',
     ctx:'Bulusma ayarlamak ve vedalasmak icin.',
     examples:[
       {th:'เจอกันที่ไหนดีครับ',ro:'joa-gan thii-nai dii khrap',tr:'Nerede bulusalim?',bd:[{ro:'joa-gan thii-nai dii',tr:'nerede bulusalim',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'เจอกันหกโมงครับ',ro:'joa-gan hok-mong khrap',tr:'Saat 6\'da bulusuruz.',bd:[{ro:'joa-gan hok-mong',tr:'saat 6da bulusuruz',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ดีใจที่ได้เจอกันครับ',ro:'dii-jai thii dai joa-gan khrap',tr:'Bulustuğumuza sevindim.',bd:[{ro:'dii-jai thii dai joa-gan',tr:'bulustuğumuza sevindim',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'แล้วเจอกันครับ',ro:'laeo joa-gan khrap',tr:'Gorusuruzdegil mi (gorusürüz).',bd:[{ro:'laeo joa-gan',tr:'gorusuruz',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w10',th:'เลี้ยง',ro:'liang',tr:'Ismarlamak / Ikram etmek',
     tip:'"Liang" = ismarlamak, birinin hesabini odemek. "Pom liang" = ben ismarlarim. Cok nazik bir jest.',
     ctx:'Phuket restoran ve barlarinda arkadaslara ikram icin.',
     examples:[
       {th:'ผมเลี้ยงครับ',ro:'pom liang khrap',tr:'Ben ismarlarim.',bd:[{ro:'pom liang',tr:'ben ismarlarim',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'เลี้ยงเบียร์ไหมครับ',ro:'liang bia mai khrap',tr:'Bira ismarlar misiniz?',bd:[{ro:'liang bia mai',tr:'bira ismarlar misiniz',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ครั้งหน้าผมเลี้ยงครับ',ro:'khrang-naa pom liang khrap',tr:'Bir dahaki seferinde ben ismarlarim.',bd:[{ro:'khrang-naa pom liang',tr:'bir daha ben ismarlarim',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ขอบคุณที่เลี้ยงครับ',ro:'khob-khun thii liang khrap',tr:'Ismarladiginiz icin tesekkurler.',bd:[{ro:'khob-khun thii liang',tr:'ismarladiginiz icin tesekkur',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
  ],
  grammar:[
    {
      title:'1. PAI + [aktivite] + GAN MAI = Birlikte ... gidelim mi?',
      formula:'PAI + [AKTİVİTE] + DUAY-GAN MAI = Birlikte ... gidelim mi?',
      explain:'"Pai" = gitmek, "duay-gan" = birlikte, "mai" = soru eki. Bu yapi birini bir aktiviteye davet etmek icin kullanilir. "Mai" olmadan teklif degil durum bildirimi olur.',
      tips:['pai gin khao duay-gan mai = birlikte yemek yiyelim mi','pai deum bia duay-gan mai = birlikte bira iceriz mi','pai ten duay-gan mai = birlikte dans edelim mi','pai thiiao duay-gan mai = birlikte gezmeye gidelim mi','duay-gan = birlikte (pekistirir)','gan tek basina da "birlikte" anlaminda kullanilabilir'],
      examples:[
        {th:'ไปกินข้าวด้วยกันไหมครับ',ro:'pai gin khao duay-gan mai khrap',tr:'Birlikte yemek yiyelim mi?',bd:[{ro:'pai gin khao',tr:'yemek yemeye git',role:'V - Yuklem'},{ro:'duay-gan mai',tr:'birlikte mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
        {th:'ไปปาร์ตี้ด้วยกันไหมครับ',ro:'pai paa-tii duay-gan mai khrap',tr:'Birlikte partiye gidelim mi?',bd:[{ro:'pai paa-tii',tr:'partiye git',role:'V - Yuklem'},{ro:'duay-gan mai',tr:'birlikte mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
        {th:'ไปเที่ยวด้วยกันไหมครับ',ro:'pai thiiao duay-gan mai khrap',tr:'Birlikte gezmeye gidelim mi?',bd:[{ro:'pai thiiao',tr:'gezmeye git',role:'V - Yuklem'},{ro:'duay-gan mai',tr:'birlikte mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
        {th:'ไปดื่มด้วยกันคืนนี้ไหมครับ',ro:'pai duem duay-gan khuean-nii mai khrap',tr:'Bu gece birlikte iceriz mi?',bd:[{ro:'pai duem',tr:'iceriz',role:'V - Yuklem'},{ro:'duay-gan khuean-nii mai',tr:'bu gece birlikte mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
      ]
    },
    {
      title:'2. [isim] + DEE-GWAA = ... daha iyi',
      formula:'[İSİM veya FİİL] + DEE-GWAA = ... daha iyi',
      explain:'"Dee" = iyi, "gwaa" = daha (karsilastirma eki). Iki sey arasinda tercih belirtmek icin. Turkce\'deki "-dan/-den daha iyi" gibi.',
      tips:['baan dee-gwaa = ev daha iyi (barda kalmaktansa)','gin thii-nii dee-gwaa = burada yemek daha iyi','pai duay-gan sa-nuk gwaa = birlikte gitmek daha eglenceli','gwaa = daha (karsilastirma)','dee gwaa = daha iyi','sa-nuk gwaa = daha eglenceli'],
      examples:[
        {th:'บ้านดีกว่าครับ',ro:'baan dee-gwaa khrap',tr:'Ev daha iyi.',bd:[{ro:'baan dee-gwaa',tr:'ev daha iyi',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
        {th:'ที่นี่ดีกว่าครับ',ro:'thii-nii dee-gwaa khrap',tr:'Burasi daha iyi.',bd:[{ro:'thii-nii dee-gwaa',tr:'burasi daha iyi',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
        {th:'ไปด้วยกันสนุกกว่าครับ',ro:'pai-duay-gan sa-nuk-gwaa khrap',tr:'Birlikte gitmek daha eglenceli.',bd:[{ro:'pai-duay-gan sa-nuk-gwaa',tr:'birlikte daha eglenceli',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
        {th:'ดื่มน้ำเปล่าดีกว่าครับ',ro:'duem naam-plao dee-gwaa khrap',tr:'Sade su icmek daha iyi.',bd:[{ro:'duem naam-plao dee-gwaa',tr:'sade su daha iyi',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
      ]
    },
  ],
  speaking:[
    {task:'Parti davet et',th:'ไปปาร์ตี้ด้วยกันไหมครับ',ro:'pai paa-tii duay-gan mai khrap',tr:'Birlikte partiye gidelim mi?',bd:[{ro:'pai paa-tii duay-gan mai',tr:'birlikte partiye gidelim mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Yemek teklifinde bulun',th:'ไปกินข้าวด้วยกันไหมครับ',ro:'pai gin khao duay-gan mai khrap',tr:'Birlikte yemek yiyelim mi?',bd:[{ro:'pai gin khao duay-gan mai',tr:'birlikte yemek yiyelim mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Dans teklif et',th:'เต้นด้วยกันไหมครับ',ro:'ten duay-gan mai khrap',tr:'Birlikte dans edelim mi?',bd:[{ro:'ten duay-gan mai',tr:'birlikte dans edelim mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Memnuniyetini belirt',th:'สนุกมากครับ',ro:'sa-nuk maak khrap',tr:'Cok eglenceli.',bd:[{ro:'sa-nuk maak',tr:'cok eglenceli',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Ben ismarlarim de',th:'ผมเลี้ยงครับ',ro:'pom liang khrap',tr:'Ben ismarlarim.',bd:[{ro:'pom liang',tr:'ben ismarlarim',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Nerede bulusacak sor',th:'เจอกันที่ไหนดีครับ',ro:'joa-gan thii-nai dii khrap',tr:'Nerede bulusalim?',bd:[{ro:'joa-gan thii-nai dii',tr:'nerede bulusalim',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Cumartesi randevu',th:'นัดหมายกันวันเสาร์ไหมครับ',ro:'nat-maai gan wan-sao mai khrap',tr:'Cumartesi bulusalim mi?',bd:[{ro:'nat-maai gan wan-sao mai',tr:'cumartesi bulusalim mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Sevindigini soy',th:'ดีใจมากครับ',ro:'dii-jai maak khrap',tr:'Cok mutluyum.',bd:[{ro:'dii-jai maak',tr:'cok mutluyum',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Vedalasin',th:'แล้วเจอกันครับ',ro:'laeo joa-gan khrap',tr:'Gorusuruz.',bd:[{ro:'laeo joa-gan',tr:'gorusuruz',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Birlikte gitmek daha iyi de',th:'ไปด้วยกันสนุกกว่าครับ',ro:'pai-duay-gan sa-nuk-gwaa khrap',tr:'Birlikte gitmek daha eglenceli.',bd:[{ro:'pai-duay-gan sa-nuk-gwaa',tr:'birlikte daha eglenceli',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Ismarladigin icin tesekkur',th:'ขอบคุณที่เลี้ยงครับ',ro:'khob-khun thii liang khrap',tr:'Ismarladiginiz icin tesekkurler.',bd:[{ro:'khob-khun thii liang',tr:'ismarladiginiz icin tesekkur',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
  ],
  dialogues:[
    {title:'🎉 Parti Daveti',
     lines:[
       {s:'Tom',th:'คืนนี้มีปาร์ตี้ที่ป่าตองครับ ไปด้วยกันไหมครับ',ro:'khuean-nii mii paa-tii thii pa-tong khrap pai duay-gan mai khrap',tr:'Bu gece Patongda parti var, birlikte gidelim mi?',bd:[{ro:'khuean-nii mii paa-tii thii pa-tong',tr:'bu gece Patongda parti var',role:'Kelime'},{ro:'pai duay-gan mai',tr:'birlikte gidelim mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {s:'Lucy',th:'ดีใจจังเลยค่ะ ไปด้วยได้เลยค่ะ',ro:'dii-jai jang loey kha pai duay dai loey kha',tr:'Haa harika! Gidelim tabii.',bd:[{ro:'dii-jai jang loey',tr:'haa harika',role:'V - Yuklem'},{ro:'pai duay dai loey',tr:'gidelim tabii',role:'V - Yuklem'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
       {s:'Tom',th:'เจอกันกี่โมงดีครับ',ro:'joa-gan gii-mong dii khrap',tr:'Saat kacta bulusuruz?',bd:[{ro:'joa-gan gii-mong dii',tr:'saat kacta bulusuruz',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {s:'Lucy',th:'สามทุ่มได้ไหมคะ',ro:'saam-thum dai mai kha',tr:'Saat 9 olur mu?',bd:[{ro:'saam-thum dai mai',tr:'saat 9 olur mu',role:'Soru/Olumsuz'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
       {s:'Tom',th:'โอเคครับ แล้วเจอกันครับ',ro:'o-kee khrap laeo joa-gan khrap',tr:'Tamam, gorusuruz.',bd:[{ro:'o-kee',tr:'tamam',role:'Kelime'},{ro:'laeo joa-gan',tr:'gorusuruz',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {title:'🍻 Barda',
     lines:[
       {s:'Tom',th:'ดื่มอะไรดีครับ ผมเลี้ยงครับ',ro:'duem a-rai dii khrap pom liang khrap',tr:'Ne icmek istersiniz? Ben ismarlarim.',bd:[{ro:'duem a-rai dii',tr:'ne icersiniz',role:'Soru/Olumsuz'},{ro:'pom liang',tr:'ben ismarlarim',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {s:'Lucy',th:'ขอบคุณค่ะ ขอเบียร์สิงห์นะคะ',ro:'khob-khun kha khor bia Sing na kha',tr:'Tesekkurler, Singha bira lutfen.',bd:[{ro:'khob-khun',tr:'tesekkurler',role:'Kelime'},{ro:'khor bia Sing',tr:'singha bira istiyorum',role:'V - Yuklem'},{ro:'na kha',tr:'onay eki',role:'Kibar'}]},
       {s:'Tom',th:'คืนนี้สนุกมากครับ',ro:'khuean-nii sa-nuk maak khrap',tr:'Bu gece cok eglenceli.',bd:[{ro:'khuean-nii sa-nuk maak',tr:'bu gece cok eglenceli',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {s:'Lucy',th:'ใช่เลยค่ะ เต้นด้วยกันไหมคะ',ro:'chai loey kha ten duay-gan mai kha',tr:'Kesinlikle! Birlikte dans edelim mi?',bd:[{ro:'chai loey',tr:'kesinlikle',role:'Kelime'},{ro:'ten duay-gan mai',tr:'birlikte dans edelim mi',role:'Soru/Olumsuz'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {title:'📅 Randevu Ayarlama',
     lines:[
       {s:'Tom',th:'นัดหมายกันวันเสาร์ไหมครับ',ro:'nat-maai gan wan-sao mai khrap',tr:'Cumartesi bulusalim mi?',bd:[{ro:'nat-maai gan wan-sao mai',tr:'cumartesi bulusalim mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {s:'Lucy',th:'ได้เลยค่ะ ไปกินข้าวด้วยกันไหมคะ',ro:'dai loey kha pai gin khao duay-gan mai kha',tr:'Tabii! Birlikte yemek yiyelim mi?',bd:[{ro:'dai loey',tr:'tabii olur',role:'Kelime'},{ro:'pai gin khao duay-gan mai',tr:'birlikte yemek yiyelim mi',role:'Soru/Olumsuz'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
       {s:'Tom',th:'ดีมากครับ เจอกันที่ไหนดีครับ',ro:'dii maak khrap joa-gan thii-nai dii khrap',tr:'Harika! Nerede bulusuruz?',bd:[{ro:'dii maak',tr:'cok iyi',role:'Kelime'},{ro:'joa-gan thii-nai dii',tr:'nerede bulusuruz',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {s:'Lucy',th:'ที่บ้านดีกว่าค่ะ แล้วไปด้วยกันค่ะ',ro:'thii baan dee-gwaa kha laeo pai duay-gan kha',tr:'Ev daha iyi, sonra birlikte gideriz.',bd:[{ro:'thii baan dee-gwaa',tr:'ev daha iyi',role:'V - Yuklem'},{ro:'laeo pai duay-gan',tr:'sonra birlikte gideriz',role:'V - Yuklem'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {title:'🕺 Dans Pistiyle',
     lines:[
       {s:'Tom',th:'เต้นเป็นไหมครับ',ro:'ten pen mai khrap',tr:'Dans edebilir misiniz?',bd:[{ro:'ten pen mai',tr:'dans edebilir misiniz',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {s:'Lucy',th:'เป็นนิดหน่อยค่ะ แต่สนุกค่ะ',ro:'pen nit-noi kha tae sa-nuk kha',tr:'Biraz yapabilirim, ama eglenceli.',bd:[{ro:'pen nit-noi',tr:'biraz yapabilirim',role:'V - Yuklem'},{ro:'tae sa-nuk',tr:'ama eglenceli',role:'Kelime'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
       {s:'Tom',th:'ผมเต้นไม่เป็นครับ แต่ลองดูครับ',ro:'pom ten mai-pen khrap tae long duu khrap',tr:'Ben edemiyorum ama deneyeyim.',bd:[{ro:'pom ten mai-pen',tr:'dans edemiyorum',role:'Olumsuz'},{ro:'tae long duu',tr:'ama deneyeyim',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {s:'Lucy',th:'ไปด้วยกันสนุกกว่าค่ะ ไปเลยนะคะ',ro:'pai-duay-gan sa-nuk-gwaa kha pai loey na kha',tr:'Birlikte daha eglenceli, hadi gidelim.',bd:[{ro:'pai-duay-gan sa-nuk-gwaa',tr:'birlikte daha eglenceli',role:'V - Yuklem'},{ro:'pai loey na',tr:'hadi gidelim',role:'V - Yuklem'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
     ]},
  ],
  listening:[
    {diff:'easy',th:'สนุกมากครับ',q:'Nasil bir his bildiriliyor?',opts:['Uzgunluk','Eglence/Mutluluk','Sikilganlık','Kizginlik'],c:1},
    {diff:'easy',th:'ผมเลี้ยงครับ',q:'Ne soyleniyor?',opts:['Siz odeyiniz','Ben ismarlarim','Hep beraber oderiz','Sonra odemek'],c:1},
    {diff:'easy',th:'เต้นด้วยกันไหมครับ',q:'Ne teklif ediliyor?',opts:['Birlikte yemek','Birlikte dans','Birlikte gezi','Birlikte sinema'],c:1},
    {diff:'easy',th:'ดีใจมากครับ',q:'Nasil bir his var?',opts:['Uzgunluk','Mutluluk/Sevinc','Korku','Saskinlik'],c:1},
    {diff:'medium',th:'ไปกินข้าวด้วยกันไหมครับ',q:'Ne teklif ediliyor?',opts:['Birlikte alısveris','Birlikte yemek','Birlikte uyku','Birlikte spor'],c:1},
    {diff:'medium',th:'เจอกันที่ไหนดีครับ',q:'Ne soruluyor?',opts:['Ne zaman bulusacaklar','Nerede bulusacaklar','Kacta bulusacaklar','Neden bulusacaklar'],c:1},
    {diff:'medium',th:'นัดหมายกันวันเสาร์ไหมครับ',q:'Hangi gun nerdeye randevu?',opts:['Pazar','Cuma','Cumartesi','Sali'],c:2},
    {diff:'medium',th:'ขอบคุณที่เลี้ยงครับ',q:'Neden tesekkur ediliyor?',opts:['Dans ettigi icin','Ismarladigi icin','Geldigii icin','Pismanligi icin'],c:1},
    {diff:'hard',th:'ไปด้วยกันสนุกกว่าครับ',q:'Ne kiyaslanıyor?',opts:['Yalniz gitmek daha iyi','Birlikte gitmek daha eglenceli','Hic gitmemek daha iyi','Yarin gitmek'],c:1},
    {diff:'hard',th:'บ้านดีกว่าค่ะ แล้วไปด้วยกัน',q:'Ne onerildi?',opts:['Barda bulusup gitmek','Evde bulusup birlikte gitmek','Ayri ayri gitmek','Ertesi gun bulusmak'],c:1},
  ],
  quiz:[
    {q:'"sa-nuk" ne demek?',opts:['Uzgun','Eglenceli','Yorgun','Kizgin'],c:1},
    {q:'"phuean" ne demek?',opts:['Aile','Sevgili','Arkadas','Komsu'],c:2},
    {q:'"duem" ne demek?',opts:['Yemek','Icmek','Pisirmek','Siparis vermek'],c:1},
    {q:'"ten" ne demek?',opts:['Sarki soymek','Dans etmek','Calgi cakmak','Gulmek'],c:1},
    {q:'"liang" ne demek?',opts:['Odeme reddetmek','Ismarlamak/Ikram etmek','Ucuza almak','Borclanmak'],c:1},
    {q:'"joa-gan" ne demek?',opts:['Ayrilmak','Bulusmak','Kaybetmek','Unutmak'],c:1},
    {q:'"dii-jai" ne demek?',opts:['Uzgunluk','Korku','Mutluluk/Sevinc','Saskinlik'],c:2},
    {q:'"nat-maai" ne demek?',opts:['Randevu/Bulusma planlamak','Iptal etmek','Gec kalmak','Unutmak'],c:0},
    {q:'"pai-duay-gan" ne demek?',opts:['Yalniz gitmek','Birlikte gitmek','Hizli gitmek','Geri donmek'],c:1},
    {q:'"dee-gwaa" ne anlama gelir?',opts:['Daha pahali','Daha kotu','Daha iyi','Daha yavas'],c:2},
    {q:'"pai gin khao duay-gan mai" ne demek?',opts:['Birlikte yemek yedik mi','Birlikte yemek yiyelim mi','Birlikte yemek yemek istemiyorum','Yemek ne kadar'],c:1},
    {q:'"sa-nuk gwaa" ne demek?',opts:['Daha sikici','Daha eglenceli','Hic eglenceli degil','En eglenceli'],c:1},
    {q:'"laeo joa-gan" ne demek?',opts:['Gorusmeyiz','Gorusuruz','Hoscakal','Hosgeldiniz'],c:1},
    {q:'"pom liang" ne anlama gelir?',opts:['Sen ismarla','Ben ismarlarim','Ikimiz oderiz','Kimse odeme'],c:1},
    {q:'"ten pen mai" ne soruluyor?',opts:['Dans ediyor musun','Dans edebilir misin','Dans ediyor muydu','Dans etmek ister misin'],c:1},
    {q:'Tom nasil konusur?',opts:['ค่ะ/kha ile','ครับ/khrap ile','Her ikisiyle','Hicbiriyle'],c:1},
    {q:'"khuean-nii sa-nuk maak" ne demek?',opts:['Bu sabah guzel','Bu gece cok eglenceli','Bu hafta cok iyi','Bu ay harika'],c:1},
    {q:'"duay-gan" ne demek?',opts:['Yalniz','Birlikte','Hizlica','Yavasca'],c:1},
    {q:'"dii-jai thii dai joa" ne demek?',opts:['Gelmediginize uzuldum','Sizi gorduğume sevindim','Sevinmiyorum','Umarim gorusuruz'],c:1},
    {q:'"khrang-naa pom liang" ne demek?',opts:['Bugun sen ismarla','Bir dahaki sefer ben ismarlarim','Hic ismarlamam','Her zaman ben ismarlarim'],c:1},
  ],
};

LESSONS[14] = L14;
