// Ders 33 verisi — CORE 2000 (896-954)
const L33 = {
  words:[
    {id:'c896',ro:'sa-gawt-theep',tr:'selobant',en:'Scotch tape',tip:'',ctx:'',examples:[]},
    {id:'c897',ro:'gooet',tr:'doğmak',en:'be born',tip:'',ctx:'',examples:[]},
    {id:'c898',ro:'dai',tr:'iş bul',en:'get a job',tip:'',ctx:'',examples:[]},
    {id:'c900',ro:'dtoo-giiao',tr:'Tokyo',en:'Tokyo',tip:'',ctx:'',examples:[]},
    {id:'c901',ro:'bpak-ging',tr:'Pekin',en:'Beijing',tip:'',ctx:'',examples:[]},
    {id:'c902',ro:'lawn-dawn',tr:'Londra',en:'London',tip:'',ctx:'',examples:[]},
    {id:'c903',ro:'bpaa-rfit',tr:'Paris',en:'Paris',tip:'',ctx:'',examples:[]},
    {id:'c904',ro:'booe-lin',tr:'Berlin',en:'Berlin',tip:'',ctx:'',examples:[]},
    {id:'c905',ro:'niu-yaawk',tr:'New York',en:'New York',tip:'',ctx:'',examples:[]},
    {id:'c906',ro:'room',tr:'şöhret',en:'fame',tip:'',ctx:'',examples:[]},
    {id:'c907',ro:'maawt-goo',tr:'Moskova',en:'Moscow',tip:'',ctx:'',examples:[]},
    {id:'c908',ro:'dtaua',tr:'bilet',en:'ticket',tip:'',ctx:'',examples:[]},
    {id:'c910',ro:'duuan',tr:'ekspres tren',en:'express train',tip:'',ctx:'',examples:[]},
    {id:'c911',ro:'tham-ma-daa',tr:'yerel tren',en:'local train',tip:'',ctx:'',examples:[]},
    {id:'c912',ro:'dtaa-raang-wee-laa',tr:'zaman çizelgesi',en:'timetable',tip:'',ctx:'',examples:[]},
    {id:'c913',ro:'gaan',tr:'bilet kontrolü',en:'ticket inspection',tip:'',ctx:'',examples:[]},
    {id:'c915',ro:'chaan-chaa-laa',tr:'platformu',en:'platform',tip:'',ctx:'',examples:[]},
    {id:'c916',ro:'dtaua',tr:'bilet makinesi',en:'ticket machine',tip:'',ctx:'',examples:[]},
    {id:'c917',ro:'buut-khaai-dtuua',tr:'bilet gişesi',en:'ticket booth',tip:'',ctx:'',examples:[]},
    {id:'c918',ro:'phim',tr:'baskı',en:'print',tip:'',ctx:'',examples:[]},
    {id:'c919',ro:'dtii-phim',tr:'yayınlamak',en:'publish',tip:'',ctx:'',examples:[]},
    {id:'c920',ro:'phaen-phap',tr:'broşür',en:'pamphlet',tip:'',ctx:'',examples:[]},
    {id:'c921',ro:'thaai-thaawt',tr:'kabul etmek',en:'ansmit',tip:'',ctx:'',examples:[]},
    {id:'c923',ro:'raai-ngaan',tr:'rapor',en:'report',tip:'',ctx:'',examples:[]},
    {id:'c924',ro:'song',tr:'göndermek',en:'submit',tip:'',ctx:'',examples:[]},
    {id:'c925',ro:'khaao',tr:'haberler',en:'news',tip:'',ctx:'',examples:[]},
    {id:'c926',ro:'sa-thaa-nii',tr:'televizyon istasyonu',en:'TV station',tip:'',ctx:'',examples:[]},
    {id:'c927',ro:'dtruuat-gae',tr:'düzenlemek',en:'edit',tip:'',ctx:'',examples:[]},
    {id:'c929',ro:'gaan-aawk-aa-gaat',tr:'yayın',en:'broadcast',tip:'',ctx:'',examples:[]},
    {id:'c930',ro:'chawng',tr:'kanal',en:'channel',tip:'',ctx:'',examples:[]},
    {id:'c931',ro:'suue',tr:'medya',en:'media',tip:'',ctx:'',examples:[]},
    {id:'c932',ro:'sa-thaa-nii',tr:'istasyon',en:'station',tip:'',ctx:'',examples:[]},
    {id:'c933',ro:'sing-phim',tr:'baskı',en:'printing',tip:'',ctx:'',examples:[]},
    {id:'c934',ro:'hawng',tr:'toplantı odası gam-ma-gaan',en:'na boardroom gam-ma-gaan',tip:'',ctx:'',examples:[]},
    {id:'c935',ro:'bpra-thaan',tr:'başkan',en:'chairman',tip:'',ctx:'',examples:[]},
    {id:'c936',ro:'laam',tr:'tercüman',en:'interpreter',tip:'',ctx:'',examples:[]},
    {id:'c937',ro:'nak-bplaae',tr:'çevirmen',en:'translator',tip:'',ctx:'',examples:[]},
    {id:'c938',ro:'khop-khan',tr:'esprili',en:'humorous',tip:'',ctx:'',examples:[]},
    {id:'c940',ro:'khwaam',tr:'izlenim',en:'impression',tip:'',ctx:'',examples:[]},
    {id:'c941',ro:'wf-thii',tr:'düşünme şekli',en:'way of thinking',tip:'',ctx:'',examples:[]},
    {id:'c943',ro:'gra-bprfi-gra-bprao',tr:'enerjik',en:'energetic',tip:'',ctx:'',examples:[]},
    {id:'c944',ro:'gaan',tr:'tartışma',en:'discussion',tip:'',ctx:'',examples:[]},
    {id:'c945',ro:'dtrong',tr:'aynı fikirde olmamak',en:'disagree',tip:'',ctx:'',examples:[]},
    {id:'c946',ro:'rak-saa',tr:'sürdürmek',en:'maintain',tip:'',ctx:'',examples:[]},
    {id:'c947',ro:'bpliian',tr:'değiştirmek',en:'change',tip:'',ctx:'',examples:[]},
    {id:'c949',ro:'dtaaw-dtaan',tr:'poz',en:'pose',tip:'',ctx:'',examples:[]},
    {id:'c951',ro:'bpra-gaat',tr:'duyurmak',en:'announce',tip:'',ctx:'',examples:[]},
    {id:'c952',ro:'jat-bpra-chum',tr:'toplantı yapmak',en:'hold a meeting',tip:'',ctx:'',examples:[]},
    {id:'c953',ro:'a-nu-mat',tr:'onaylamak',en:'approve',tip:'',ctx:'',examples:[]},
    {id:'c954',ro:'wf-jaan',tr:'eleştirmek',en:'criticize',tip:'',ctx:'',examples:[]},
  ]
};

LESSONS[33] = L33;
