// Ders 43 verisi — CORE 2000 (1598-1663)
const L43 = {
  words:[
    {id:'c1598',ro:'gaw-raao-jap',tr:'küpeşteye tutun',en:'hold onto the handrail',tip:'',ctx:'',examples:[]},
    {id:'c1599',ro:'baan',tr:'Ev',en:'home',tip:'',ctx:'',examples:[]},
    {id:'c1600',ro:'gaan-baan',tr:'Ev ödevi',en:'homework',tip:'',ctx:'',examples:[]},
    {id:'c1601',ro:'suue-sat',tr:'dürüst',en:'honest',tip:'',ctx:'',examples:[]},
    {id:'c1602',ro:'khii-maa',tr:'binicilik',en:'horseback riding',tip:'',ctx:'',examples:[]},
    {id:'c1603',ro:'hawt-meo',tr:'Otmail',en:'otmail',tip:'',ctx:'',examples:[]},
    {id:'c1604',ro:'maae-baan',tr:'ev hanımı',en:'housewife',tip:'',ctx:'',examples:[]},
    {id:'c1605',ro:'khun',tr:'baang nasılsın',en:'baang How have you',tip:'',ctx:'',examples:[]},
    {id:'c1606',ro:'khun',tr:'kaç yaşındasın',en:'How old are',tip:'',ctx:'',examples:[]},
    {id:'c1607',ro:'saa-mii',tr:'koca',en:'husband',tip:'',ctx:'',examples:[]},
    {id:'c1608',ro:'chan',tr:'bundan hoşlanmıyorum',en:'I dislike it',tip:'',ctx:'',examples:[]},
    {id:'c1609',ro:'chan',tr:'Anlamıyorum',en:'I don\'t understand',tip:'',ctx:'',examples:[]},
    {id:'c1610',ro:'chan',tr:'bunu al',en:'ke this',tip:'',ctx:'',examples:[]},
    {id:'c1611',ro:'chan',tr:'İsterdim',en:'I\'d like to',tip:'',ctx:'',examples:[]},
    {id:'c1612',ro:'chan',tr:'Ben iyiyim',en:'I\'m fine',tip:'',ctx:'',examples:[]},
    {id:'c1614',ro:'phit',tr:'yasa dışı',en:'illegal',tip:'',ctx:'',examples:[]},
    {id:'c1615',ro:'naawn',tr:'inç kurdu',en:'inchworm',tip:'',ctx:'',examples:[]},
    {id:'c1616',ro:'mai',tr:'yanlış',en:'incorrect',tip:'',ctx:'',examples:[]},
    {id:'c1618',ro:'dtruuat-saawp',tr:'incelemek',en:'inspect',tip:'',ctx:'',examples:[]},
    {id:'c1619',ro:'ruu-suek',tr:'ilgili',en:'interested',tip:'',ctx:'',examples:[]},
    {id:'c1620',ro:'yaakjang',tr:'Bu zor',en:'It\'s difficult',tip:'',ctx:'',examples:[]},
    {id:'c1621',ro:'i-dtaa-lfi',tr:'İtalya',en:'Italy',tip:'',ctx:'',examples:[]},
    {id:'c1622',ro:'thaang',tr:'seyahat planı',en:'itinerary',tip:'',ctx:'',examples:[]},
    {id:'c1625',ro:'yen',tr:'Yen',en:'Yen',tip:'',ctx:'',examples:[]},
    {id:'c1626',ro:'gra-doot',tr:'zıplamak',en:'jump',tip:'',ctx:'',examples:[]},
    {id:'c1628',ro:'dte',tr:'tekme atmak',en:'kick',tip:'',ctx:'',examples:[]},
    {id:'c1629',ro:'nai',tr:'mutfak masası',en:'kitchen table',tip:'',ctx:'',examples:[]},
    {id:'c1630',ro:'khaw',tr:'kapıyı çalmak',en:'knock',tip:'',ctx:'',examples:[]},
    {id:'c1632',ro:'thaawng',tr:'uğur böceği',en:'ladybug',tip:'',ctx:'',examples:[]},
    {id:'c1633',ro:'khoom-fai',tr:'lamba',en:'lamp',tip:'',ctx:'',examples:[]},
    {id:'c1637',ro:'baaw-ri-gaan',tr:'çamaşırhane servisi',en:'laundry service',tip:'',ctx:'',examples:[]},
    {id:'c1639',ro:'bai-mai',tr:'yaprak',en:'leaf',tip:'',ctx:'',examples:[]},
    {id:'c1640',ro:'gaan-ban-yaai',tr:'ders',en:'lecture',tip:'',ctx:'',examples:[]},
    {id:'c1641',ro:'lfiao',tr:'sola dönüş',en:'left turn',tip:'',ctx:'',examples:[]},
    {id:'c1642',ro:'bot-riian',tr:'ders',en:'lesson',tip:'',ctx:'',examples:[]},
    {id:'c1643',ro:'jot-maai',tr:'mektup',en:'letter',tip:'',ctx:'',examples:[]},
    {id:'c1644',ro:'bai-a-nu-yaat',tr:'lisans',en:'license',tip:'',ctx:'',examples:[]},
    {id:'c1647',ro:'fai-chaek',tr:'çakmak',en:'lighter',tip:'',ctx:'',examples:[]},
    {id:'c1648',ro:'chaawp',tr:'beğenmek',en:'like',tip:'',ctx:'',examples:[]},
    {id:'c1649',ro:'phaa-saa-saat',tr:'dilbilim',en:'linguistics',tip:'',ctx:'',examples:[]},
    {id:'c1651',ro:'dtuua-miia',tr:'dişi aslan',en:'lioness',tip:'',ctx:'',examples:[]},
    {id:'c1652',ro:'mii',tr:'kolayca',en:'f ely',tip:'',ctx:'',examples:[]},
    {id:'c1653',ro:'gf',tr:'kertenkele',en:'lizard',tip:'',ctx:'',examples:[]},
    {id:'c1654',ro:'ngao',tr:'yalnız',en:'lonely',tip:'',ctx:'',examples:[]},
    {id:'c1655',ro:'mai',tr:'Uzun zamandır görüşemedik',en:'Long time no see',tip:'',ctx:'',examples:[]},
    {id:'c1657',ro:'laawt-aaen-jee-lft',tr:'Los Angeles',en:'Los Angeles',tip:'',ctx:'',examples:[]},
    {id:'c1658',ro:'phaae',tr:'kaybetmek',en:'lose',tip:'',ctx:'',examples:[]},
    {id:'c1661',ro:'gaan-dtruuat',tr:'bagaj kontrolü',en:'luggage check',tip:'',ctx:'',examples:[]},
    {id:'c1662',ro:'thfi',tr:'bagaj teslimi',en:'luggage pickup',tip:'',ctx:'',examples:[]},
    {id:'c1663',ro:'bprai-sa-nii',tr:'posta',en:'mail',tip:'',ctx:'',examples:[]},
  ]
};

LESSONS[43] = L43;
