// Ders 27 verisi — CORE 2000 (513-577)
const L27 = {
  words:[
    {id:'c513',ro:'un-ha-phuum',tr:'sıcaklık',en:'temperature',tip:'',ctx:'',examples:[]},
    {id:'c514',ro:'chuuen',tr:'nemli',en:'humid',tip:'',ctx:'',examples:[]},
    {id:'c515',ro:'mii',tr:'rüzgarlı',en:'windy',tip:'',ctx:'',examples:[]},
    {id:'c517',ro:'sa-naam',tr:'havuz',en:'pool',tip:'',ctx:'',examples:[]},
    {id:'c518',ro:'then-nit',tr:'tenis',en:'tennis',tip:'',ctx:'',examples:[]},
    {id:'c519',ro:'baat-get-baawn',tr:'basketbol',en:'basketball',tip:'',ctx:'',examples:[]},
    {id:'c521',ro:'khaao',tr:'pirinç',en:'rice',tip:'',ctx:'',examples:[]},
    {id:'c525',ro:'naa-lf-gaa',tr:'çalar saat',en:'alarm clock',tip:'',ctx:'',examples:[]},
    {id:'c526',ro:'bpra-dtuu',tr:'kapı',en:'door',tip:'',ctx:'',examples:[]},
    {id:'c527',ro:'rii-moot',tr:'uzaktan kumanda',en:'remote control',tip:'',ctx:'',examples:[]},
    {id:'c528',ro:'chet',tr:'silip süpürmek',en:'wipe',tip:'',ctx:'',examples:[]},
    {id:'c529',ro:'mee-nuu-aa-haan',tr:'menü',en:'menu',tip:'',ctx:'',examples:[]},
    {id:'c530',ro:'nft-dta-ya-saan',tr:'gazete',en:'fagazine',tip:'',ctx:'',examples:[]},
    {id:'c532',ro:'wf-dii-oo-geem',tr:'video oyunu',en:'video game',tip:'',ctx:'',examples:[]},
    {id:'c533',ro:'thuuk',tr:'ucuz',en:'cheap',tip:'',ctx:'',examples:[]},
    {id:'c534',ro:'phaaeng',tr:'masraflı',en:'expensive',tip:'',ctx:'',examples:[]},
    {id:'c535',ro:'jai-dii',tr:'tür',en:'kind',tip:'',ctx:'',examples:[]},
    {id:'c536',ro:'naa-waat-gluua',tr:'korkutucu',en:'scary',tip:'',ctx:'',examples:[]},
    {id:'c538',ro:'bpaawn',tr:'pound',en:'pound',tip:'',ctx:'',examples:[]},
    {id:'c539',ro:'mai',tr:'mil',en:'mile',tip:'',ctx:'',examples:[]},
    {id:'c540',ro:'fut',tr:'ayak',en:'foot',tip:'',ctx:'',examples:[]},
    {id:'c541',ro:'khwaam',tr:'hastalık',en:'illness',tip:'',ctx:'',examples:[]},
    {id:'c542',ro:'wat',tr:'soğuk',en:'cold',tip:'',ctx:'',examples:[]},
    {id:'c543',ro:'aa-gaan',tr:'incinme',en:'injury',tip:'',ctx:'',examples:[]},
    {id:'c545',ro:'khwaam',tr:'ağrı',en:'pain',tip:'',ctx:'',examples:[]},
    {id:'c546',ro:'khai',tr:'ateş',en:'fever',tip:'',ctx:'',examples:[]},
    {id:'c547',ro:'naa-dtaang',tr:'pencere',en:'window',tip:'',ctx:'',examples:[]},
    {id:'c548',ro:'tao',tr:'alkol',en:'alcohol',tip:'',ctx:'',examples:[]},
    {id:'c549',ro:'aa-haan',tr:'yemek',en:'meal',tip:'',ctx:'',examples:[]},
    {id:'c550',ro:'maawk',tr:'sis',en:'fog',tip:'',ctx:'',examples:[]},
    {id:'c552',ro:'naawng',tr:'fırtına',en:'thunderstorm',tip:'',ctx:'',examples:[]},
    {id:'c553',ro:'nam',tr:'akvaryum',en:'aquarium',tip:'',ctx:'',examples:[]},
    {id:'c554',ro:'fut-baawn',tr:'futbol',en:'soccer',tip:'',ctx:'',examples:[]},
    {id:'c555',ro:'suuan-sat',tr:'hayvanat bahçesi',en:'zoo',tip:'',ctx:'',examples:[]},
    {id:'c556',ro:'khaa-dooi-saan',tr:'ücret',en:'fare',tip:'',ctx:'',examples:[]},
    {id:'c558',ro:'gram',tr:'ben',en:'am',tip:'',ctx:'',examples:[]},
    {id:'c559',ro:'meet',tr:'metre',en:'meter',tip:'',ctx:'',examples:[]},
    {id:'c561',ro:'bpuuat-huua',tr:'baş ağrısı',en:'headache',tip:'',ctx:'',examples:[]},
    {id:'c562',ro:'rook',tr:'ishal',en:'diarrhea',tip:'',ctx:'',examples:[]},
    {id:'c563',ro:'aa-gaan',tr:'belirti',en:'symptom',tip:'',ctx:'',examples:[]},
    {id:'c564',ro:'thaawng',tr:'karın ağrısı',en:'stomachache',tip:'',ctx:'',examples:[]},
    {id:'c566',ro:'tham',tr:'kuru',en:'dry',tip:'',ctx:'',examples:[]},
    {id:'c567',ro:'bpat',tr:'toz',en:'dust',tip:'',ctx:'',examples:[]},
    {id:'c568',ro:'duut',tr:'vakum',en:'vacuum',tip:'',ctx:'',examples:[]},
    {id:'c569',ro:'sii-yaaek',tr:'kavşak',en:'intersection',tip:'',ctx:'',examples:[]},
    {id:'c570',ro:'thaang-luuang',tr:'otoyol',en:'highway',tip:'',ctx:'',examples:[]},
    {id:'c574',ro:'jai-raai',tr:'Anlam',en:'mean',tip:'',ctx:'',examples:[]},
    {id:'c575',ro:'ruu-suek',tr:'sıkılmış',en:'bored',tip:'',ctx:'',examples:[]},
    {id:'c576',ro:'jet-raauy',tr:'yedi yüz',en:'seven hundred',tip:'',ctx:'',examples:[]},
    {id:'c577',ro:'bpaaet-raauy',tr:'sekiz yüz',en:'eight hundred',tip:'',ctx:'',examples:[]},
  ]
};

LESSONS[27] = L27;
