// Ders 25 verisi — CORE 2000 (368-434)
const L25 = {
  words:[
    {id:'c368',ro:'phaap-pha-yon',tr:'sevgi',en:'fovie',tip:'',ctx:'',examples:[]},
    {id:'c369',ro:'pleeng',tr:'müzik',en:'music',tip:'',ctx:'',examples:[]},
    {id:'c370',ro:'kham-dtaawp',tr:'cevap',en:'answer',tip:'',ctx:'',examples:[]},
    {id:'c371',ro:'saawn',tr:'öğretmek',en:'teach',tip:'',ctx:'',examples:[]},
    {id:'c372',ro:'thaam',tr:'sormak',en:'ask',tip:'',ctx:'',examples:[]},
    {id:'c373',ro:'bpit',tr:'kapalı',en:'close',tip:'',ctx:'',examples:[]},
    {id:'c374',ro:'gaan-gooet',tr:'doğum',en:'birth',tip:'',ctx:'',examples:[]},
    {id:'c376',ro:'bpooet',tr:'aç',en:'turn on',tip:'',ctx:'',examples:[]},
    {id:'c377',ro:'bpit',tr:'kapamak',en:'turn off',tip:'',ctx:'',examples:[]},
    {id:'c378',ro:'baan',tr:'dışarıda yemek',en:'eat out',tip:'',ctx:'',examples:[]},
    {id:'c380',ro:'thft-dta-wan-dtok',tr:'batı',en:'west',tip:'',ctx:'',examples:[]},
    {id:'c381',ro:'bpraaeng',tr:'fırçalamak',en:'brush',tip:'',ctx:'',examples:[]},
    {id:'c384',ro:'aawk',tr:'ayrılmak',en:'leave',tip:'',ctx:'',examples:[]},
    {id:'c385',ro:'chek',tr:'kontrol etmek',en:'check',tip:'',ctx:'',examples:[]},
    {id:'c386',ro:'hok-sip-hok',tr:'altmış altı',en:'sixty-six',tip:'',ctx:'',examples:[]},
    {id:'c387',ro:'jet-sip-jet',tr:'yetmiş yedi',en:'seventy-seven',tip:'',ctx:'',examples:[]},
    {id:'c388',ro:'bpaaet-sip-bpaaet',tr:'seksen sekiz',en:'eighty-eight',tip:'',ctx:'',examples:[]},
    {id:'c390',ro:'nueng-raauy',tr:'yüz',en:'one hundred',tip:'',ctx:'',examples:[]},
    {id:'c392',ro:'hawng-aa-haan',tr:'yemek odası',en:'dining room',tip:'',ctx:'',examples:[]},
    {id:'c393',ro:'thaang-dooen',tr:'koridor',en:'hallway',tip:'',ctx:'',examples:[]},
    {id:'c394',ro:'a-phaat-men',tr:'daire',en:'apartment',tip:'',ctx:'',examples:[]},
    {id:'c395',ro:'baan',tr:'ev',en:'house',tip:'',ctx:'',examples:[]},
    {id:'c397',ro:'bpooet',tr:'açık',en:'open',tip:'',ctx:'',examples:[]},
    {id:'c398',ro:'fang',tr:'Dinlemek',en:'listen',tip:'',ctx:'',examples:[]},
    {id:'c399',ro:'wan-gooet',tr:'doğum günü',en:'birthday',tip:'',ctx:'',examples:[]},
    {id:'c401',ro:'khaang',tr:'dıştan',en:'outside',tip:'',ctx:'',examples:[]},
    {id:'c402',ro:'khaang',tr:'içeri',en:'inside',tip:'',ctx:'',examples:[]},
    {id:'c404',ro:'khwaa',tr:'Sağ',en:'right',tip:'',ctx:'',examples:[]},
    {id:'c405',ro:'raaek',tr:'Birinci',en:'first',tip:'',ctx:'',examples:[]},
    {id:'c406',ro:'thfi',tr:'ikinci',en:'second',tip:'',ctx:'',examples:[]},
    {id:'c407',ro:'thfi',tr:'üçüncü',en:'third',tip:'',ctx:'',examples:[]},
    {id:'c408',ro:'sa-buu',tr:'sabun',en:'soap',tip:'',ctx:'',examples:[]},
    {id:'c412',ro:'khaaw-muun',tr:'bilgi',en:'information',tip:'',ctx:'',examples:[]},
    {id:'c413',ro:'ga-seet-dtra-gaawn',tr:'çiftçi',en:'farmer',tip:'',ctx:'',examples:[]},
    {id:'c417',ro:'pha-yaa-yaam',tr:'denemek',en:'try',tip:'',ctx:'',examples:[]},
    {id:'c418',ro:'wat',tr:'ölçüm',en:'measure',tip:'',ctx:'',examples:[]},
    {id:'c419',ro:'gep',tr:'kale',en:'keep',tip:'',ctx:'',examples:[]},
    {id:'c420',ro:'raaw',tr:'Beklemek',en:'wait',tip:'',ctx:'',examples:[]},
    {id:'c422',ro:'maaw',tr:'saksı',en:'pot',tip:'',ctx:'',examples:[]},
    {id:'c423',ro:'gap',tr:'kurbağa',en:'frog',tip:'',ctx:'',examples:[]},
    {id:'c425',ro:'nam-thfiao',tr:'rehber kitap',en:'guidebook',tip:'',ctx:'',examples:[]},
    {id:'c426',ro:'thaang-khao',tr:'giriş',en:'entrance',tip:'',ctx:'',examples:[]},
    {id:'c427',ro:'mak-khu-theet',tr:'tur rehberi',en:'tour guide',tip:'',ctx:'',examples:[]},
    {id:'c428',ro:'gaan',tr:'rezervasyon',en:'reservation',tip:'',ctx:'',examples:[]},
    {id:'c429',ro:'thaang',tr:'pasaport',en:'passport',tip:'',ctx:'',examples:[]},
    {id:'c430',ro:'wt-chaa',tr:'bilgisayar Bilimi',en:'computer science',tip:'',ctx:'',examples:[]},
    {id:'c431',ro:'wf-chaa',tr:'matematik',en:'math',tip:'',ctx:'',examples:[]},
    {id:'c432',ro:'ruu-suek',tr:'hissetmek',en:'feel',tip:'',ctx:'',examples:[]},
    {id:'c433',ro:'waat',tr:'çizmek',en:'draw',tip:'',ctx:'',examples:[]},
    {id:'c434',ro:'phaaen-gaan',tr:'planı',en:'plan',tip:'',ctx:'',examples:[]},
  ]
};

LESSONS[25] = L25;
