// === DERS13.JS START ===
// Ders 13 verisi — tayca-v3
// =================== VERİ: DERS 13 — Ev Yasami ve Internet ===================
const L13 = {
  tones:[],
  words:[
    {id:'w1',th:'บ้าน',ro:'baan',tr:'Ev',
     tip:'"Baan" = ev, konut. "Baan-pom" = benim evim. Phuket\'te kiralik evler icin hep kullanilir.',
     ctx:'Kira sozlesmesi, komsu iliskileri ve ev konusmalari icin temel kelime.',
     examples:[
       {th:'บ้านผมอยู่แถวราไวย์ครับ',ro:'baan pom yuu thaeo ra-wai khrap',tr:'Evim Rawai civarinda.',bd:[{ro:'baan pom yuu thaeo ra-wai',tr:'evim rawai civarinda',role:'Kelime'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'บ้านนี้เช่าได้ไหมครับ',ro:'baan nii chao dai mai khrap',tr:'Bu ev kiralik mi?',bd:[{ro:'baan nii chao dai mai',tr:'bu ev kiralik mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'บ้านสวยมากครับ',ro:'baan suay maak khrap',tr:'Ev cok guzel.',bd:[{ro:'baan suay maak',tr:'ev cok guzel',role:'Kelime'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ผมอยู่บ้านครับ',ro:'pom yuu baan khrap',tr:'Evdeyim.',bd:[{ro:'pom yuu baan',tr:'evdeyim',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w2',th:'wifi',ro:'wai-fai',tr:'WiFi / Kablosuz internet',
     tip:'Ingilizce\'den gecme. Thai\'ce "wai-fai" seklinde soylenir. Sifre = "rat-sa-phan wai-fai".',
     ctx:'Phuket\'teki ev ve kafelerde en cok sorulan sey.',
     examples:[
       {th:'wifi มีไหมครับ',ro:'wai-fai mii mai khrap',tr:'WiFi var mi?',bd:[{ro:'wai-fai mii mai',tr:'wifi var mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'รหัส wifi คืออะไรครับ',ro:'ra-hat wai-fai khue a-rai khrap',tr:'WiFi sifresi nedir?',bd:[{ro:'ra-hat wai-fai khue a-rai',tr:'wifi sifresi nedir',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'wifi ช้ามากครับ',ro:'wai-fai chaa maak khrap',tr:'WiFi cok yavas.',bd:[{ro:'wai-fai chaa maak',tr:'wifi cok yavas',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'wifi ใช้ไม่ได้ครับ',ro:'wai-fai chai mai-dai khrap',tr:'WiFi calismiyor.',bd:[{ro:'wai-fai chai mai-dai',tr:'wifi calismiyor',role:'Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w3',th:'ห้องนอน',ro:'hong-non',tr:'Yatak odasi',
     tip:'"Hong" = oda, "non" = uyumak. "Hong-non nueng" = tek yatak odasi.',
     ctx:'Kiralik ev veya daire ararken.',
     examples:[
       {th:'มีกี่ห้องนอนครับ',ro:'mii gii hong-non khrap',tr:'Kac yatak odasi var?',bd:[{ro:'mii gii hong-non',tr:'kac yatak odasi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ห้องนอนใหญ่ไหมครับ',ro:'hong-non yai mai khrap',tr:'Yatak odasi buyuk mu?',bd:[{ro:'hong-non yai mai',tr:'yatak odasi buyuk mu',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ห้องนอนมีแอร์ไหมครับ',ro:'hong-non mii aer mai khrap',tr:'Yatak odasinda klima var mi?',bd:[{ro:'hong-non mii aer mai',tr:'yatak odasinda klima var mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w4',th:'ห้องน้ำ',ro:'hong-naam',tr:'Banyo / Tuvalet',
     tip:'"Hong" = oda, "naam" = su. Hem banyo hem tuvalet icin kullanilir.',
     ctx:'Her ev konusmasinda gerekli. "Hong-naam pang" = tuvalet bozuk.',
     examples:[
       {th:'ห้องน้ำอยู่ที่ไหนครับ',ro:'hong-naam yuu thii-nai khrap',tr:'Banyo nerede?',bd:[{ro:'hong-naam yuu thii-nai',tr:'banyo nerede',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ห้องน้ำมีปัญหาครับ',ro:'hong-naam mii pan-haa khrap',tr:'Banyoda sorun var.',bd:[{ro:'hong-naam mii pan-haa',tr:'banyoda sorun var',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ห้องน้ำในห้องนอนไหมครับ',ro:'hong-naam nai hong-non mai khrap',tr:'Banyo yatak odasinin icinde mi?',bd:[{ro:'hong-naam nai hong-non mai',tr:'banyo icinde mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ห้องน้ำสะอาดดีครับ',ro:'hong-naam sa-aat dii khrap',tr:'Banyo temiz ve guzel.',bd:[{ro:'hong-naam sa-aat dii',tr:'banyo temiz ve guzel',role:'Kelime'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w5',th:'ค่าเช่า',ro:'khaa-chao',tr:'Kira (ucret)',
     tip:'"Khaa" = ucret/bedel, "chao" = kiralamak. "Khaa-chao ruam" = kira dahil.',
     ctx:'Ev kira mufakerelerinde en onemli kelime.',
     examples:[
       {th:'ค่าเช่าเดือนละเท่าไรครับ',ro:'khaa-chao duean-la thao-rai khrap',tr:'Aylik kira ne kadar?',bd:[{ro:'khaa-chao duean-la thao-rai',tr:'aylik kira ne kadar',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ค่าเช่ารวมน้ำไฟไหมครับ',ro:'khaa-chao ruam naam fai mai khrap',tr:'Kira su ve elektrik dahil mi?',bd:[{ro:'khaa-chao ruam naam fai mai',tr:'kira su elektrik dahil mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ค่าเช่าแพงไปครับ',ro:'khaa-chao phaeng pai khrap',tr:'Kira cok pahali.',bd:[{ro:'khaa-chao phaeng pai',tr:'kira pahali',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ลดค่าเช่าได้ไหมครับ',ro:'lot khaa-chao dai mai khrap',tr:'Kirayi indirebilir misiniz?',bd:[{ro:'lot khaa-chao dai mai',tr:'kirayi indirebilir misiniz',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w6',th:'ทำความสะอาด',ro:'tham-khwaam-sa-aat',tr:'Temizlemek',
     tip:'"Tham" = yapmak, "khwaam sa-aat" = temizlik. Ev temizligi icin.',
     ctx:'Temizlikci tutmak veya temizlik sormak icin. Phuket\'te ev temizlikci yaygın.',
     examples:[
       {th:'ทำความสะอาดบ้านหน่อยได้ไหมครับ',ro:'tham-khwaam-sa-aat baan noi dai mai khrap',tr:'Evi biraz temizleyebilir misiniz?',bd:[{ro:'tham-khwaam-sa-aat baan noi dai mai',tr:'evi temizleyebilir mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ผมทำความสะอาดเองครับ',ro:'pom tham-khwaam-sa-aat eng khrap',tr:'Kendim temizlerim.',bd:[{ro:'pom tham-khwaam-sa-aat eng',tr:'kendim temizlerim',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ทำความสะอาดทุกอาทิตย์ครับ',ro:'tham-khwaam-sa-aat thuk aa-thit khrap',tr:'Her hafta temizlenyor.',bd:[{ro:'tham-khwaam-sa-aat thuk aa-thit',tr:'her hafta temizleniyor',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w7',th:'ซ่อม',ro:'som',tr:'Tamir etmek',
     tip:'"Som" = tamir. "Chuay som hai noi" = lutfen tamir eder misin? Kiraci olarak bilmeniz sart.',
     ctx:'Ev arizalarinda ev sahibine soylenecek kelime.',
     examples:[
       {th:'ช่วยซ่อมให้หน่อยครับ',ro:'chuay som hai noi khrap',tr:'Lutfen tamir eder misiniz?',bd:[{ro:'chuay som hai noi',tr:'lutfen tamir et',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ซ่อมแล้วยังครับ',ro:'som laeo yang khrap',tr:'Tamir edildi mi?',bd:[{ro:'som laeo yang',tr:'tamir edildi mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ยังซ่อมไม่เสร็จครับ',ro:'yang som mai-set khrap',tr:'Henuz tamir bitmedi.',bd:[{ro:'yang som mai-set',tr:'henuz tamir bitmedi',role:'Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ซ่อมเสร็จแล้วครับ',ro:'som set laeo khrap',tr:'Tamir tamamlandi.',bd:[{ro:'som set laeo',tr:'tamir tamam',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w8',th:'เปิด / ปิด',ro:'poet / pit',tr:'Acmak / Kapatmak',
     tip:'"Poet" = ac, "pit" = kapat. Kapi, pencere, elektrik, su, klima her sey icin.',
     ctx:'Gunluk ev hayatinin en temel komutlari.',
     examples:[
       {th:'เปิดไฟด้วยครับ',ro:'poet fai duay khrap',tr:'Isigi acin lutfen.',bd:[{ro:'poet fai duay',tr:'isigi ac lutfen',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ปิดแอร์หน่อยครับ',ro:'pit aer noi khrap',tr:'Klimayi kapatir misiniz?',bd:[{ro:'pit aer noi',tr:'klimayi kapat',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'เปิดน้ำด้วยครับ',ro:'poet naam duay khrap',tr:'Suyu acar misiniz?',bd:[{ro:'poet naam duay',tr:'suyu ac lutfen',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ปิดประตูด้วยครับ',ro:'pit pra-tuu duay khrap',tr:'Kapiyi kapar misiniz?',bd:[{ro:'pit pra-tuu duay',tr:'kapiyi kapat lutfen',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w9',th:'น้ำประปา',ro:'naam-pra-paa',tr:'Musluk suyu',
     tip:'"Naam" = su, "pra-paa" = boru hatti. "Naam-pra-paa mai ok" = musluk suyu cikmiyor.',
     ctx:'Su arızasi durumunda veya su kalitesi sorulmak istendiginde.',
     examples:[
       {th:'น้ำประปาไม่ออกครับ',ro:'naam-pra-paa mai ok khrap',tr:'Musluk suyu cikmiyor.',bd:[{ro:'naam-pra-paa mai ok',tr:'musluk suyu cikmiyor',role:'Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'น้ำประปาร้อนมากครับ',ro:'naam-pra-paa ron maak khrap',tr:'Musluk suyu cok sicak.',bd:[{ro:'naam-pra-paa ron maak',tr:'musluk suyu sicak',role:'Kelime'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ดื่มน้ำประปาได้ไหมครับ',ro:'duem naam-pra-paa dai mai khrap',tr:'Musluk suyu icilir mi?',bd:[{ro:'duem naam-pra-paa dai mai',tr:'musluk suyu icilir mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'น้ำประปาแรงดีครับ',ro:'naam-pra-paa raeng dii khrap',tr:'Su basinci iyi.',bd:[{ro:'naam-pra-paa raeng dii',tr:'su basinci iyi',role:'Kelime'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w10',th:'ไฟฟ้า',ro:'fai-faa',tr:'Elektrik',
     tip:'"Fai" = ates/isik, "faa" = gok. "Fai-faa dat" = elektrik kesildi. Sık Phuket\'te olur.',
     ctx:'Phuket\'te yagmur mevsiminde elektrik kesintileri olur.',
     examples:[
       {th:'ไฟฟ้าดับครับ',ro:'fai-faa dap khrap',tr:'Elektrik kesildi.',bd:[{ro:'fai-faa dap',tr:'elektrik kesildi',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ค่าไฟฟ้าเดือนนี้เท่าไรครับ',ro:'khaa fai-faa duean-nii thao-rai khrap',tr:'Bu ayın elektrik faturasi ne kadar?',bd:[{ro:'khaa fai-faa duean-nii thao-rai',tr:'bu ay elektrik faturasi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ไฟฟ้ากลับมาแล้วครับ',ro:'fai-faa glap maa laeo khrap',tr:'Elektrik geri geldi.',bd:[{ro:'fai-faa glap maa laeo',tr:'elektrik geri geldi',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ปลั๊กไฟฟ้าอยู่ที่ไหนครับ',ro:'plak fai-faa yuu thii-nai khrap',tr:'Elektrik prizi nerede?',bd:[{ro:'plak fai-faa yuu thii-nai',tr:'elektrik prizi nerede',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
  ],
  grammar:[
    {
      title:'1. CHUAY + fiil + HAI NOI = lutfen ... yapar misin?',
      formula:'CHUAY + [FİİL] + HAI NOI = Lutfen [fiil] yapar misiniz?',
      explain:'"Chuay" = yardim et/lutfen, "hai" = icin/yaparak, "noi" = biraz (kibar yumusatici). Bu kalip ev sahibine veya yardimciya kibarca istek bildirmek icin cok kullanilir.',
      tips:['chuay som hai noi = lutfen tamir eder misin','chuay poet hai noi = lutfen acar misin','chuay pit hai noi = lutfen kapar misin','chuay tham-khwaam-sa-aat hai noi = lutfen temizler misin','noi eklemek islegi daha nazik yapar','hai olmadan daha direkt olur'],
      examples:[
        {th:'ช่วยซ่อมให้หน่อยครับ',ro:'chuay som hai noi khrap',tr:'Lutfen tamir eder misiniz?',bd:[{ro:'chuay som hai noi',tr:'lutfen tamir et',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
        {th:'ช่วยเปิดแอร์ให้หน่อยครับ',ro:'chuay poet aer hai noi khrap',tr:'Lutfen klimayi acar misiniz?',bd:[{ro:'chuay poet aer hai noi',tr:'lutfen klimayi ac',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
        {th:'ช่วยดูให้หน่อยครับ',ro:'chuay duu hai noi khrap',tr:'Lutfen bir bakar misiniz?',bd:[{ro:'chuay duu hai noi',tr:'lutfen bir bak',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
        {th:'ช่วยบอกให้หน่อยครับ',ro:'chuay bok hai noi khrap',tr:'Lutfen soyleyer misiniz?',bd:[{ro:'chuay bok hai noi',tr:'lutfen soyle',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
      ]
    },
    {
      title:'2. YANG MAI + fiil = henuz ... edilmedi',
      formula:'YANG MAI + [FİİL] = Henuz ... edilmedi / yapmadi',
      explain:'"Yang" = henuz/hala, "mai" = olumsuz. Birlikte "henuz olmadi" anlaminda. Ev tamiri veya beklenilen bir seyin gelmedigini soylemek icin kullanilir.',
      tips:['yang mai som = henuz tamir edilmedi','yang mai maa = henuz gelmedi','yang mai set = henuz bitmedi','yang mii = hala var','yang yuu = hala burada','yang = henuz (zaman belirteci)'],
      examples:[
        {th:'ยังซ่อมไม่เสร็จครับ',ro:'yang som mai-set khrap',tr:'Henuz tamir bitmedi.',bd:[{ro:'yang som mai-set',tr:'henuz tamir bitmedi',role:'Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
        {th:'ยังไม่มาครับ',ro:'yang mai maa khrap',tr:'Henuz gelmedi.',bd:[{ro:'yang mai maa',tr:'henuz gelmedi',role:'Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
        {th:'ยังไม่พร้อมครับ',ro:'yang mai prom khrap',tr:'Henuz hazir degil.',bd:[{ro:'yang mai prom',tr:'henuz hazir degil',role:'Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
        {th:'ยัง wifi ใช้ไม่ได้ครับ',ro:'yang wai-fai chai mai-dai khrap',tr:'Wifi henuz calismiyor.',bd:[{ro:'yang wai-fai chai mai-dai',tr:'wifi henuz calismiyor',role:'Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
      ]
    },
  ],
  speaking:[
    {task:'WiFi sifresi sor',th:'รหัส wifi คืออะไรครับ',ro:'ra-hat wai-fai khue a-rai khrap',tr:'WiFi sifresi nedir?',bd:[{ro:'ra-hat wai-fai khue a-rai',tr:'wifi sifresi nedir',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Aylik kira sor',th:'ค่าเช่าเดือนละเท่าไรครับ',ro:'khaa-chao duean-la thao-rai khrap',tr:'Aylik kira ne kadar?',bd:[{ro:'khaa-chao duean-la thao-rai',tr:'aylik kira ne kadar',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Tamir iste',th:'ช่วยซ่อมให้หน่อยครับ',ro:'chuay som hai noi khrap',tr:'Lutfen tamir eder misiniz?',bd:[{ro:'chuay som hai noi',tr:'lutfen tamir et',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Elektrik kesildi bildir',th:'ไฟฟ้าดับครับ',ro:'fai-faa dap khrap',tr:'Elektrik kesildi.',bd:[{ro:'fai-faa dap',tr:'elektrik kesildi',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Musluk suyu yok',th:'น้ำประปาไม่ออกครับ',ro:'naam-pra-paa mai ok khrap',tr:'Musluk suyu cikmiyor.',bd:[{ro:'naam-pra-paa mai ok',tr:'musluk suyu cikmiyor',role:'Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Klimayi ac',th:'เปิดแอร์ด้วยครับ',ro:'poet aer duay khrap',tr:'Klimayi acar misiniz?',bd:[{ro:'poet aer duay',tr:'klimayi ac',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Kirayi indir',th:'ลดค่าเช่าได้ไหมครับ',ro:'lot khaa-chao dai mai khrap',tr:'Kirayi indirebilir misiniz?',bd:[{ro:'lot khaa-chao dai mai',tr:'kirayi indirebilir misiniz',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Banyo bozuk',th:'ห้องน้ำมีปัญหาครับ',ro:'hong-naam mii pan-haa khrap',tr:'Banyoda sorun var.',bd:[{ro:'hong-naam mii pan-haa',tr:'banyoda sorun var',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'WiFi calismiyor',th:'wifi ใช้ไม่ได้ครับ',ro:'wai-fai chai mai-dai khrap',tr:'WiFi calismiyor.',bd:[{ro:'wai-fai chai mai-dai',tr:'wifi calismiyor',role:'Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Kira dahil mi sor',th:'ค่าเช่ารวมน้ำไฟไหมครับ',ro:'khaa-chao ruam naam fai mai khrap',tr:'Kira su ve elektrik dahil mi?',bd:[{ro:'khaa-chao ruam naam fai mai',tr:'kira su elektrik dahil mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Tamir bitmedi bildir',th:'ยังซ่อมไม่เสร็จครับ',ro:'yang som mai-set khrap',tr:'Henuz tamir bitmedi.',bd:[{ro:'yang som mai-set',tr:'henuz tamir bitmedi',role:'Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
  ],
  dialogues:[
    {title:'🏠 Kiralik Ev Gorusmesi',
     lines:[
       {s:'Tom',th:'ค่าเช่าเดือนละเท่าไรครับ',ro:'khaa-chao duean-la thao-rai khrap',tr:'Aylik kira ne kadar?',bd:[{ro:'khaa-chao duean-la thao-rai',tr:'aylik kira ne kadar',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {s:'Lucy',th:'หมื่นห้าพันบาทค่ะ รวมน้ำค่ะ',ro:'muean-haa phan baht kha ruam naam kha',tr:'15.000 Baht, su dahil.',bd:[{ro:'muean-haa phan baht',tr:'15.000 baht',role:'Kelime'},{ro:'ruam naam',tr:'su dahil',role:'Kelime'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
       {s:'Tom',th:'wifi มีไหมครับ',ro:'wai-fai mii mai khrap',tr:'WiFi var mi?',bd:[{ro:'wai-fai mii mai',tr:'wifi var mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {s:'Lucy',th:'มีค่ะ แต่ค่าไฟฟ้าจ่ายเองนะคะ',ro:'mii kha tae khaa fai-faa jai eng na kha',tr:'Var, ama elektrik faturasini kendiniz odersiniz.',bd:[{ro:'mii',tr:'var',role:'Kelime'},{ro:'tae khaa fai-faa jai eng',tr:'ama elektrik kendinize',role:'Kelime'},{ro:'na kha',tr:'onay eki',role:'Kibar'}]},
       {s:'Tom',th:'ลดได้ไหมครับ',ro:'lot dai mai khrap',tr:'Indirim olur mu?',bd:[{ro:'lot dai mai',tr:'indirim olur mu',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {s:'Lucy',th:'ลดให้หน่อยได้ค่ะ หมื่นสองพันได้ไหมคะ',ro:'lot hai noi dai kha muean-song phan dai mai kha',tr:'Biraz indirebilirim, 12.000 olur mu?',bd:[{ro:'lot hai noi dai',tr:'biraz indirebilirim',role:'V - Yuklem'},{ro:'muean-song phan dai mai',tr:'12.000 olur mu',role:'Soru/Olumsuz'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {title:'🔧 Bozuk Musluk Tamiri',
     lines:[
       {s:'Tom',th:'น้ำประปาไม่ออกครับ ช่วยซ่อมให้หน่อยครับ',ro:'naam-pra-paa mai ok khrap chuay som hai noi khrap',tr:'Musluk suyu cikmiyor, lutfen tamir eder misiniz?',bd:[{ro:'naam-pra-paa mai ok',tr:'musluk suyu cikmiyor',role:'Olumsuz'},{ro:'chuay som hai noi',tr:'lutfen tamir et',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {s:'Lucy',th:'โอเคค่ะ พรุ่งนี้ส่งช่างมาให้ค่ะ',ro:'o-kee kha phrung-nii song chang maa hai kha',tr:'Tamam, yarin tamirci gonderirim.',bd:[{ro:'o-kee',tr:'tamam',role:'Kelime'},{ro:'phrung-nii song chang maa hai',tr:'yarin tamirci gonder',role:'V - Yuklem'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
       {s:'Tom',th:'ยังซ่อมไม่เสร็จครับ มาเมื่อไรครับ',ro:'yang som mai-set khrap maa muea-rai khrap',tr:'Henuz tamir bitmedi, ne zaman gelecek?',bd:[{ro:'yang som mai-set',tr:'henuz tamir bitmedi',role:'Olumsuz'},{ro:'maa muea-rai',tr:'ne zaman geliyor',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {s:'Lucy',th:'ขอโทษนะคะ พรุ่งนี้เช้าแน่นอนค่ะ',ro:'khor-thot na kha phrung-nii-chao nae-non kha',tr:'Ozur dilerim, yarin sabah kesinlikle.',bd:[{ro:'khor-thot na',tr:'ozur dilerim',role:'Kelime'},{ro:'phrung-nii-chao nae-non',tr:'yarin sabah kesinlikle',role:'Kelime'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {title:'📶 WiFi Sorunu',
     lines:[
       {s:'Tom',th:'wifi ใช้ไม่ได้ครับ รหัสถูกไหมครับ',ro:'wai-fai chai mai-dai khrap ra-hat thuuk mai khrap',tr:'WiFi calismiyor, sifre dogru mu?',bd:[{ro:'wai-fai chai mai-dai',tr:'wifi calismiyor',role:'Olumsuz'},{ro:'ra-hat thuuk mai',tr:'sifre dogru mu',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {s:'Lucy',th:'รหัสใหม่ค่ะ เดี๋ยวส่งให้นะคะ',ro:'ra-hat mai kha diaw song hai na kha',tr:'Yeni sifre var, hemen gonderirim.',bd:[{ro:'ra-hat mai',tr:'yeni sifre',role:'Kelime'},{ro:'diaw song hai',tr:'hemen gonderirim',role:'V - Yuklem'},{ro:'na kha',tr:'onay eki',role:'Kibar'}]},
       {s:'Tom',th:'ขอบคุณครับ wifi ช้ามากครับ',ro:'khob-khun khrap wai-fai chaa maak khrap',tr:'Tesekkurler, WiFi cok yavas.',bd:[{ro:'khob-khun',tr:'tesekkur ederim',role:'Kelime'},{ro:'wai-fai chaa maak',tr:'wifi cok yavas',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {s:'Lucy',th:'จะแจ้งบริษัทอินเทอร์เน็ตให้ค่ะ',ro:'ja jaeng bo-ri-sat in-toa-net hai kha',tr:'Internet sirketine haber veririm.',bd:[{ro:'ja jaeng bo-ri-sat in-toa-net hai',tr:'internet sirketine haber veririm',role:'V - Yuklem'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {title:'💡 Elektrik Kesintisi',
     lines:[
       {s:'Tom',th:'ไฟฟ้าดับครับ ทั้งบ้านเลยครับ',ro:'fai-faa dap khrap thang-baan loey khrap',tr:'Elektrik kesildi, tum ev.',bd:[{ro:'fai-faa dap',tr:'elektrik kesildi',role:'V - Yuklem'},{ro:'thang-baan loey',tr:'tum ev',role:'Kelime'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {s:'Lucy',th:'แถวนั้นไฟดับทั้งหมดค่ะ กำลังซ่อมค่ะ',ro:'thaeo-nan fai-dap thang-mot kha gam-lang som kha',tr:'O bolgenin hepsi kesildi, tamir ediliyor.',bd:[{ro:'thaeo-nan fai-dap thang-mot',tr:'o bolge tamamen kesildi',role:'Kelime'},{ro:'gam-lang som',tr:'tamir ediliyor',role:'V - Yuklem'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
       {s:'Tom',th:'นานแค่ไหนครับ',ro:'naan khae-nai khrap',tr:'Ne kadar surecek?',bd:[{ro:'naan khae-nai',tr:'ne kadar sure',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {s:'Lucy',th:'ไม่นานค่ะ ประมาณหนึ่งชั่วโมงค่ะ',ro:'mai naan kha pra-maan nueng chua-mong kha',tr:'Uzun degil, yaklasik bir saat.',bd:[{ro:'mai naan',tr:'uzun degil',role:'Olumsuz'},{ro:'pra-maan nueng chua-mong',tr:'yaklasik bir saat',role:'Kelime'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
     ]},
  ],
  listening:[
    {diff:'easy',th:'wifi มีไหมครับ',q:'Ne soruluyor?',opts:['Su var mi','WiFi var mi','Klima var mi','Garaj var mi'],c:1},
    {diff:'easy',th:'ไฟฟ้าดับครับ',q:'Ne oldu?',opts:['Su kesildi','Elektrik kesildi','Internet kesildi','Su kesildi'],c:1},
    {diff:'easy',th:'น้ำประปาไม่ออกครับ',q:'Sorun ne?',opts:['Elektrik yok','Musluk suyu cikmiyor','WiFi calismiyor','Isi degisecek'],c:1},
    {diff:'easy',th:'ช่วยซ่อมให้หน่อยครับ',q:'Ne isteniyor?',opts:['Temizlik yapilmasi','Tamir yapilmasi','Anahtar verilmesi','Boya yapilmasi'],c:1},
    {diff:'medium',th:'ค่าเช่าเดือนละเท่าไรครับ',q:'Ne soruluyor?',opts:['Gunluk kira','Aylik kira','Yillik kira','Saatlik kira'],c:1},
    {diff:'medium',th:'รหัส wifi คืออะไรครับ',q:'Ne soruluyor?',opts:['WiFi hizi','WiFi sifresi','WiFi markasi','WiFi markasi'],c:1},
    {diff:'medium',th:'ยังซ่อมไม่เสร็จครับ',q:'Tamir ne durumda?',opts:['Tamir tamamlandi','Tamir henuz bitmedi','Tamir baslamadi','Tamir suruyor'],c:1},
    {diff:'medium',th:'ปิดแอร์หน่อยครับ',q:'Ne isteniyor?',opts:['Klimayi ac','Klimayi kapat','Klimayi tamir et','Tamiri ertele'],c:1},
    {diff:'hard',th:'ค่าเช่ารวมน้ำไฟไหมครับ',q:'Ne dahil mi soruluyor?',opts:['Yemek dahil mi','Su ve elektrik dahil mi','WiFi dahil mi','Garaj dahil mi'],c:1},
    {diff:'hard',th:'จะแจ้งบริษัทอินเทอร์เน็ตให้ค่ะ',q:'Ne yapilacak?',opts:['Internet sifresi degistirilecek','Internet sirketine haber verilecek','Internet kesilecek','Yeni internet kurulacak'],c:1},
  ],
  quiz:[
    {q:'"baan" ne demek?',opts:['Araba','Ev','Ofis','Magaza'],c:1},
    {q:'"khaa-chao" ne demek?',opts:['Kira bedeli','Elektrik faturasi','Su faturasi','Yemek ucreti'],c:0},
    {q:'"hong-non" ne demek?',opts:['Banyo','Mutfak','Yatak odasi','Salon'],c:2},
    {q:'"hong-naam" ne demek?',opts:['Yatak odasi','Banyo/Tuvalet','Mutfak','Depo'],c:1},
    {q:'"som" ne demek?',opts:['Temizlemek','Boyamak','Tamir etmek','Yikmak'],c:2},
    {q:'"poet" ne demek?',opts:['Kapatmak','Kirmak','Acmak','Itmek'],c:2},
    {q:'"pit" ne demek?',opts:['Acmak','Kapatmak','Kilidlemek','Itmek'],c:1},
    {q:'"fai-faa" ne demek?',opts:['Su','Gaz','Elektrik','Internet'],c:2},
    {q:'"naam-pra-paa" ne demek?',opts:['Yagmur suyu','Deniz suyu','Musluk suyu','Soguk su'],c:2},
    {q:'"yang mai som" ne demek?',opts:['Tamir edildi','Henuz tamir edilmedi','Tamir gerekmiyor','Tamir pahali'],c:1},
    {q:'"chuay som hai noi" ne demek?',opts:['Tamirci geldi','Tamir edildi','Lutfen tamir eder misiniz','Tamir pahali degil'],c:2},
    {q:'"wai-fai chaa maak" ne demek?',opts:['WiFi cok hizli','WiFi cok yavas','WiFi yok','WiFi iyi'],c:1},
    {q:'"tham-khwaam-sa-aat" ne demek?',opts:['Yemek pisirmek','Temizlemek','Boyamak','Dizmek'],c:1},
    {q:'"fai-faa dap" ne demek?',opts:['Isik acik','Elektrik kesildi','Ampul bitti','Sigorta attı'],c:1},
    {q:'"ra-hat wai-fai" ne demek?',opts:['WiFi markasi','WiFi hizi','WiFi sifresi','WiFi kablosu'],c:2},
    {q:'Kira dahil su ve elektrik icin ne denir?',opts:['ruam naam fai','yang mai som','poet fai','pit naam'],c:0},
    {q:'"lot khaa-chao" ne demek?',opts:['Kirayi artir','Kirayi indir','Kirayi ode','Kirayi sor'],c:1},
    {q:'"yang" ne anlama gelir?',opts:['Hemen','Henuz/Hala','Sonra','Once'],c:1},
    {q:'"hong-naam nai hong-non" ne demek?',opts:['Banyo yatak odasinin disinda','Banyo yatak odasinin icinde','Banyo mutfakta','Banyo salonunda'],c:1},
    {q:'"naan khae-nai" ne demek?',opts:['Ne kadar uzak','Ne kadar sure','Ne kadar agir','Ne kadar buyuk'],c:1},
  ],
};

LESSONS[13] = L13;
