// Ders 48 verisi — CORE 2000 (1952-2000)
const L48 = {
  words:[
    {id:'c1952',ro:'pha-maa',tr:'Birmanya',en:'Burmese',tip:'',ctx:'',examples:[]},
    {id:'c1953',ro:'jiin',tr:'Çince',en:'Chinese',tip:'',ctx:'',examples:[]},
    {id:'c1954',ro:'faaa',tr:'Laos dili',en:'Laotian',tip:'',ctx:'',examples:[]},
    {id:'c1956',ro:'muuai',tr:'Tay boksu',en:'Thai boxing',tip:'',ctx:'',examples:[]},
    {id:'c1957',ro:'gaan',tr:'Tay masajı',en:'Thai massage',tip:'',ctx:'',examples:[]},
    {id:'c1958',ro:'gaan',tr:'sörf',en:'surfing',tip:'',ctx:'',examples:[]},
    {id:'c1959',ro:'gaan',tr:'dalma',en:'scuba diving',tip:'',ctx:'',examples:[]},
    {id:'c1960',ro:'gaan',tr:'gaan rafting ve trekking gaaeng',en:'gaan rafting and trekking gaaeng',tip:'',ctx:'',examples:[]},
    {id:'c1961',ro:'gaan',tr:'dağ bisikleti',en:'mountain biking',tip:'',ctx:'',examples:[]},
    {id:'c1962',ro:'gaan',tr:'kayak yapmak',en:'kayaking',tip:'',ctx:'',examples:[]},
    {id:'c1963',ro:'gaan',tr:'bpra-wat-saat geçmişinin izini sürüyor',en:'bpra-wat-saat retracing history',tip:'',ctx:'',examples:[]},
    {id:'c1964',ro:'gaan',tr:'kayalıklara tırmanma',en:'rock climbing',tip:'',ctx:'',examples:[]},
    {id:'c1965',ro:'bping-bpawng',tr:'masa tenisi',en:'table tennis',tip:'',ctx:'',examples:[]},
    {id:'c1966',ro:'see-bpak',tr:'sepak takraw',en:'sepak takraw',tip:'',ctx:'',examples:[]},
    {id:'c1969',ro:'phat-thai',tr:'reklam Tay dili',en:'ad Thai',tip:'',ctx:'',examples:[]},
    {id:'c1971',ro:'saa-thoo',tr:'Sato',en:'Sato',tip:'',ctx:'',examples:[]},
    {id:'c1972',ro:'nam',tr:'karpuz suyu',en:'watermelon juice',tip:'',ctx:'',examples:[]},
    {id:'c1973',ro:'nam',tr:'şeker kamışı suyu',en:'sugarcane juice',tip:'',ctx:'',examples:[]},
    {id:'c1974',ro:'nam',tr:'Hindistan cevizi suyu',en:'coconut juice',tip:'',ctx:'',examples:[]},
    {id:'c1975',ro:'chaa-yen',tr:'Sütlü Tay buzlu çayı',en:'Thai iced tea with milk',tip:'',ctx:'',examples:[]},
    {id:'c1976',ro:'chaa',tr:'ark Thai buzlu çay',en:'ark Thai iced tea',tip:'',ctx:'',examples:[]},
    {id:'c1977',ro:'gra-thing',tr:'Red Bull',en:'Red Bull',tip:'',ctx:'',examples:[]},
    {id:'c1981',ro:'dtaaeng-moo',tr:'karpuz suyu',en:'watermelon juice',tip:'',ctx:'',examples:[]},
    {id:'c1983',ro:'s-af',tr:'elma',en:'neapple',tip:'',ctx:'',examples:[]},
    {id:'c1985',ro:'lam-yai',tr:'longan',en:'longan',tip:'',ctx:'',examples:[]},
    {id:'c1986',ro:'chiiang-mai',tr:'Chiang Mai',en:'Chiang Mai',tip:'',ctx:'',examples:[]},
    {id:'c1987',ro:'haa-raat-cha-wang',tr:'Büyük Saray',en:'the Grand Palace',tip:'',ctx:'',examples:[]},
    {id:'c1988',ro:'gaw-chaang',tr:'Ko Chang',en:'Ko Chang',tip:'',ctx:'',examples:[]},
    {id:'c1989',ro:'wat-phoo',tr:'Wat Pho',en:'Wat Pho',tip:'',ctx:'',examples:[]},
    {id:'c1991',ro:'maae-hawng-saawn',tr:'Mae Hong\'un Oğlu',en:'Mae Hong Son',tip:'',ctx:'',examples:[]},
    {id:'c1992',ro:'dta-laat-nam',tr:'Yüzen Pazar',en:'the Floating Market',tip:'',ctx:'',examples:[]},
    {id:'c1993',ro:'phleeng',tr:'rock müzik',en:'rock music',tip:'',ctx:'',examples:[]},
    {id:'c1995',ro:'hip-hawp',tr:'hip hop',en:'hip hop',tip:'',ctx:'',examples:[]},
    {id:'c1996',ro:'gra-raawk',tr:'sincap',en:'squirrel',tip:'',ctx:'',examples:[]},
    {id:'c1998',ro:'dawk',tr:'Modern köpek',en:'Moderndog',tip:'',ctx:'',examples:[]},
    {id:'c1999',ro:'joo-fi',tr:'Erkek çocuk',en:'Boy',tip:'',ctx:'',examples:[]},
    {id:'c2000',ro:'en-droo-fin',tr:'Endorfin',en:'Endorphine',tip:'',ctx:'',examples:[]},
  ]
};

LESSONS[48] = L48;
