// Ders 36 verisi — CORE 2000 (1108-1167)
const L36 = {
  words:[
    {id:'c1108',ro:'a-rai',tr:'Ne',en:'what',tip:'',ctx:'',examples:[]},
    {id:'c1109',ro:'khrai',tr:'DSÖ',en:'who',tip:'',ctx:'',examples:[]},
    {id:'c1110',ro:'bpra-pheet',tr:'f hatkind',en:'f hatkind',tip:'',ctx:'',examples:[]},
    {id:'c1111',ro:'waa-ngai',tr:'ne',en:'What\'s',tip:'',ctx:'',examples:[]},
    {id:'c1114',ro:'naa-thuep',tr:'yoğun',en:'dense',tip:'',ctx:'',examples:[]},
    {id:'c1115',ro:'gwaang-yai',tr:'büyüklük',en:'vast',tip:'',ctx:'',examples:[]},
    {id:'c1116',ro:'song',tr:'kare',en:'square',tip:'',ctx:'',examples:[]},
    {id:'c1118',ro:'ta-iiat',tr:'iyi',en:'fine',tip:'',ctx:'',examples:[]},
    {id:'c1119',ro:'nak',tr:'ağır',en:'heavy',tip:'',ctx:'',examples:[]},
    {id:'c1120',ro:'yaao',tr:'uzun',en:'long',tip:'',ctx:'',examples:[]},
    {id:'c1121',ro:'gaan-sa-daaeng',tr:'performans',en:'performance',tip:'',ctx:'',examples:[]},
    {id:'c1122',ro:'khaawng-khwan',tr:'Sunmak',en:'present',tip:'',ctx:'',examples:[]},
    {id:'c1126',ro:'ngoen-sot',tr:'peşin',en:'cash',tip:'',ctx:'',examples:[]},
    {id:'c1127',ro:'chai-ngoen',tr:'para harcamak',en:'spend money',tip:'',ctx:'',examples:[]},
    {id:'c1129',ro:'haang-sap-pa-srn-khaa',tr:'büyük mağaza',en:'department store',tip:'',ctx:'',examples:[]},
    {id:'c1130',ro:'raan',tr:'butik',en:'boutique',tip:'',ctx:'',examples:[]},
    {id:'c1131',ro:'aao',tr:'çapa mağazası',en:'hoe store',tip:'',ctx:'',examples:[]},
    {id:'c1132',ro:'fen',tr:'poker oyna',en:'play poker',tip:'',ctx:'',examples:[]},
    {id:'c1133',ro:'khaa',tr:'alışveriş merkezi',en:'mall',tip:'',ctx:'',examples:[]},
    {id:'c1135',ro:'dtuua-ak-saawn',tr:'metin',en:'text',tip:'',ctx:'',examples:[]},
    {id:'c1136',ro:'in-thooe-net',tr:'İnternet kafe',en:'Internet cafe',tip:'',ctx:'',examples:[]},
    {id:'c1137',ro:'rai-saai',tr:'kablosuz',en:'wireless',tip:'',ctx:'',examples:[]},
    {id:'c1138',ro:'blawk',tr:'o g',en:'o g',tip:'',ctx:'',examples:[]},
    {id:'c1139',ro:'wep-sai-khruuea-khaai',tr:'sosyal ağ sitesi',en:'social networking site',tip:'',ctx:'',examples:[]},
    {id:'c1140',ro:'haa',tr:'arama motoru',en:'search engine',tip:'',ctx:'',examples:[]},
    {id:'c1141',ro:'in-thooe-net',tr:'İnternet erişimi',en:'Internet access',tip:'',ctx:'',examples:[]},
    {id:'c1142',ro:'thaa-ra-sap',tr:'thaae-net IP telefonu',en:'thaae-net IP phone',tip:'',ctx:'',examples:[]},
    {id:'c1143',ro:'ra-na',tr:'ankesörlü telefon',en:'public phone',tip:'',ctx:'',examples:[]},
    {id:'c1144',ro:'nai',tr:'yerel telefon görüşmesi',en:'local phone call',tip:'',ctx:'',examples:[]},
    {id:'c1145',ro:'sap',tr:'aramak',en:'dial',tip:'',ctx:'',examples:[]},
    {id:'c1146',ro:'thaa-ra-sap',tr:'telefon numarası',en:'phone number',tip:'',ctx:'',examples:[]},
    {id:'c1147',ro:'thaa-ra-sap',tr:'operatör',en:'operator',tip:'',ctx:'',examples:[]},
    {id:'c1148',ro:'gaan',tr:'thaang-glai şehirlerarası arama',en:'thaang-glai long-distance call',tip:'',ctx:'',examples:[]},
    {id:'c1149',ro:'dtaawn-yen',tr:'akşam',en:'evening',tip:'',ctx:'',examples:[]},
    {id:'c1150',ro:'dtaawn-chaao',tr:'Sabah',en:'morning',tip:'',ctx:'',examples:[]},
    {id:'c1151',ro:'thang-wan',tr:'bütün gün',en:'all day',tip:'',ctx:'',examples:[]},
    {id:'c1152',ro:'gfaang-khuuen',tr:'gece vakti',en:'ghttime',tip:'',ctx:'',examples:[]},
    {id:'c1153',ro:'gfaang-wan',tr:'gündüz',en:'daytime',tip:'',ctx:'',examples:[]},
    {id:'c1154',ro:'fang',tr:'sonrasında',en:'after',tip:'',ctx:'',examples:[]},
    {id:'c1155',ro:'nap-dtaae-nfi-bpai',tr:'bundan sonra',en:'from now on',tip:'',ctx:'',examples:[]},
    {id:'c1156',ro:'gaawn',tr:'önce',en:'before',tip:'',ctx:'',examples:[]},
    {id:'c1157',ro:'dtaawn-nfi',tr:'Şimdi',en:'now',tip:'',ctx:'',examples:[]},
    {id:'c1158',ro:'bauy',tr:'sıklıkla',en:'often',tip:'',ctx:'',examples:[]},
    {id:'c1160',ro:'rue-duu',tr:'kış',en:'winter',tip:'',ctx:'',examples:[]},
    {id:'c1161',ro:'rue-duu',tr:'yaz',en:'summer',tip:'',ctx:'',examples:[]},
    {id:'c1162',ro:'rue-duu',tr:'bahar',en:'spring',tip:'',ctx:'',examples:[]},
    {id:'c1163',ro:'rue-duu',tr:'düşmek',en:'fall',tip:'',ctx:'',examples:[]},
    {id:'c1165',ro:'bpen',tr:'dondurmak',en:'freeze',tip:'',ctx:'',examples:[]},
    {id:'c1166',ro:'rung',tr:'gökkuşağı',en:'rainbow',tip:'',ctx:'',examples:[]},
    {id:'c1167',ro:'taa-taep',tr:'yıldırım',en:'lightning',tip:'',ctx:'',examples:[]},
  ]
};

LESSONS[36] = L36;
