// === DERS10.JS START ===
// Ders 10 verisi — tayca-v3
// =================== VERİ: DERS 10 — Plaj ve Deniz ===================
const L10 = {
  tones:[],
  words:[
    {id:'w1',th:'หาด',ro:'haat',tr:'Plaj',
     tip:'"Haat" kısa ve net. "Haat Patong" = Patong Plajı. Phuket\'te her plaj adı "haat" ile başlar.',
     ctx:'Phuket\'te en popüler plajlar: Haat Patong, Haat Karon, Haat Kata.',
     examples:[
       {th:'หาดสวยมากครับ',ro:'haat suay maak khrap',tr:'Plaj çok güzel.',bd:[{ro:'haat',tr:'plaj',role:'S - Ozne'},{ro:'suay maak',tr:'çok güzel',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ไปหาดไหนดีครับ',ro:'pai haat nai dii khrap',tr:'Hangi plaja gidelim?',bd:[{ro:'pai haat nai dii',tr:'hangi plaja gidelim',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'หาดอยู่ไกลไหมครับ',ro:'haat yuu glai mai khrap',tr:'Plaj uzak mı?',bd:[{ro:'haat yuu glai mai',tr:'plaj uzak mı',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'หาดป่าตองครับ',ro:'haat pa-tong khrap',tr:'Patong Plajı.',bd:[{ro:'haat pa-tong',tr:'Patong Plajı',role:'Kelime'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'หาดนี้สะอาดครับ',ro:'haat nii sa-aat khrap',tr:'Bu plaj temiz.',bd:[{ro:'haat nii',tr:'bu plaj',role:'S - Ozne'},{ro:'sa-aat',tr:'temiz',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w2',th:'ทะเล',ro:'ta-lee',tr:'Deniz',
     tip:'"Ta-lee" = deniz. "Rim ta-lee" = deniz kenarı. Phuket Andaman Denizi\'ne bakar.',
     ctx:'Andaman Denizi Kasım-Nisan arası sakin, Mayıs-Ekim dalgalı olur.',
     examples:[
       {th:'ทะเลสวยมากครับ',ro:'ta-lee suay maak khrap',tr:'Deniz çok güzel.',bd:[{ro:'ta-lee',tr:'deniz',role:'S - Ozne'},{ro:'suay maak',tr:'çok güzel',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ทะเลวันนี้แรงครับ',ro:'ta-lee wan-nii raeng khrap',tr:'Bugün deniz sert.',bd:[{ro:'ta-lee wan-nii',tr:'bugün deniz',role:'S - Ozne'},{ro:'raeng',tr:'sert/güçlü',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ลงทะเลได้ไหมครับ',ro:'long ta-lee dai mai khrap',tr:'Denize girebilir miyim?',bd:[{ro:'long ta-lee',tr:'denize in',role:'V - Yuklem'},{ro:'dai mai',tr:'olur mu',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ริมทะเลสวยมากครับ',ro:'rim ta-lee suay maak khrap',tr:'Deniz kenarı çok güzel.',bd:[{ro:'rim ta-lee',tr:'deniz kenarı',role:'S - Ozne'},{ro:'suay maak',tr:'çok güzel',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'น้ำทะเลใสครับ',ro:'naam ta-lee sai khrap',tr:'Deniz suyu berrak.',bd:[{ro:'naam ta-lee',tr:'deniz suyu',role:'S - Ozne'},{ro:'sai',tr:'berrak/saydam',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w3',th:'ว่ายน้ำ',ro:'waai-naam',tr:'Yüzmek',
     tip:'"Waai" = yüzme hareketi, "naam" = su. Birlikte "waai-naam" = yüzmek.',
     ctx:'Phuket\'te bayrak sistemine dikkat: kırmızı bayrak = denize girme, sarı = dikkatli ol.',
     examples:[
       {th:'ผมอยากว่ายน้ำครับ',ro:'pom yaak waai-naam khrap',tr:'Yüzmek istiyorum.',bd:[{ro:'pom',tr:'ben',role:'S - Ozne'},{ro:'yaak waai-naam',tr:'yüzmek istiyorum',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ว่ายน้ำได้ไหมครับ',ro:'waai-naam dai mai khrap',tr:'Yüzebilir misiniz? / Yüzme var mı?',bd:[{ro:'waai-naam dai mai',tr:'yüzebilir mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ว่ายน้ำไม่เป็นครับ',ro:'waai-naam mai pen khrap',tr:'Yüzme bilmiyorum.',bd:[{ro:'waai-naam mai pen',tr:'yüzme bilmiyorum',role:'Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ว่ายน้ำด้วยกันไหมครับ',ro:'waai-naam duay-gan mai khrap',tr:'Birlikte yüzelim mi?',bd:[{ro:'waai-naam duay-gan mai',tr:'birlikte yüzelim mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ห้ามว่ายน้ำตรงนี้ครับ',ro:'ham waai-naam trong-nii khrap',tr:'Burada yüzmek yasak.',bd:[{ro:'ham waai-naam trong-nii',tr:'burada yüzmek yasak',role:'Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w4',th:'ครีมกันแดด',ro:'kriim-gan-daet',tr:'Gunes Kremi',
     tip:'"Kriim" = krem, "gan" = karşı/koruma, "daet" = güneş. Phuket\'te SPF 50+ şart.',
     ctx:'Tropikal güneş çok kuvvetli. Her 2 saatte bir yeniden sürmeyi unutma.',
     examples:[
       {th:'ครีมกันแดดอยู่ที่ไหนครับ',ro:'kriim-gan-daet yuu thii-nai khrap',tr:'Güneş kremi nerede?',bd:[{ro:'kriim-gan-daet yuu thii-nai',tr:'güneş kremi nerede',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ทาครีมกันแดดก่อนลงทะเลครับ',ro:'thaa kriim-gan-daet gon long ta-lee khrap',tr:'Denize girmeden once güneş kremi sür.',bd:[{ro:'thaa kriim-gan-daet gon long ta-lee',tr:'önce güneş kremi sür',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ครีมกันแดด SPF 50 มีไหมครับ',ro:'kriim-gan-daet SPF haa-sip mii mai khrap',tr:'SPF 50 güneş kremi var mı?',bd:[{ro:'kriim-gan-daet SPF haa-sip',tr:'SPF 50 güneş kremi',role:'S - Ozne'},{ro:'mii mai',tr:'var mı',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ลืมทาครีมกันแดดครับ',ro:'luem thaa kriim-gan-daet khrap',tr:'Güneş kremi sürmeyi unuttum.',bd:[{ro:'luem thaa kriim-gan-daet',tr:'güneş kremi sürmeyi unuttum',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ซื้อครีมกันแดดที่ร้านสะดวกซื้อได้ครับ',ro:'sue kriim-gan-daet thii raan-sa-duak-sue dai khrap',tr:'Güneş kremini marketten alabilirsin.',bd:[{ro:'sue kriim-gan-daet thii raan-sa-duak-sue',tr:'marketten güneş kremi al',role:'V - Yuklem'},{ro:'dai',tr:'olur/yapılabilir',role:'Kelime'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w5',th:'เรือ',ro:'ruea',tr:'Tekne / Gemi',
     tip:'"Ruea" = tekne. "Ruea long-tail" = longtail tekne. Phuket\'te adaya gitmek için kullanılır.',
     ctx:'Phi Phi adasına veya Similan adalarına tekneyle gidilir.',
     examples:[
       {th:'เรือออกกี่โมงครับ',ro:'ruea ok gii-mong khrap',tr:'Tekne saat kaçta kalkıyor?',bd:[{ro:'ruea ok',tr:'tekne kalkıyor',role:'V - Yuklem'},{ro:'gii-mong',tr:'saat kaç',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ขอซื้อตั๋วเรือครับ',ro:'khor sue tua ruea khrap',tr:'Tekne bileti almak istiyorum.',bd:[{ro:'khor sue tua ruea',tr:'tekne bileti almak',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'เรือไปเกาะพีพีใช้เวลานานไหมครับ',ro:'ruea pai gao-phi-phi chai-wee-laa naan mai khrap',tr:'Phi Phi\'ye tekneyle uzun sürer mi?',bd:[{ro:'ruea pai gao-phi-phi',tr:'Phi Phi\'ye tekne',role:'S - Ozne'},{ro:'chai-wee-laa naan mai',tr:'uzun sürer mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'เรือลำนี้ปลอดภัยไหมครับ',ro:'ruea lam-nii plot-phai mai khrap',tr:'Bu tekne güvenli mi?',bd:[{ro:'ruea lam-nii',tr:'bu tekne',role:'S - Ozne'},{ro:'plot-phai mai',tr:'güvenli mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'เรือหัวโทงครับ',ro:'ruea long-tail khrap',tr:'Longtail tekne.',bd:[{ro:'ruea long-tail',tr:'longtail tekne',role:'Kelime'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w6',th:'ทราย',ro:'saai',tr:'Kum',
     tip:'"Saai" = kum. "Haat saai khao" = beyaz kumlu plaj. Phuket\'te ince beyaz kum yaygın.',
     ctx:'Kata ve Karon plajlarında çok güzel beyaz kum var.',
     examples:[
       {th:'ทรายขาวสวยมากครับ',ro:'saai khao suay maak khrap',tr:'Beyaz kum çok güzel.',bd:[{ro:'saai khao',tr:'beyaz kum',role:'S - Ozne'},{ro:'suay maak',tr:'çok güzel',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'นั่งบนทรายครับ',ro:'nang bon saai khrap',tr:'Kumun üstüne oturuyorum.',bd:[{ro:'nang bon saai',tr:'kumda otur',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ทรายร้อนมากครับ',ro:'saai ron maak khrap',tr:'Kum çok sıcak.',bd:[{ro:'saai ron maak',tr:'kum çok sıcak',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ทรายละเอียดมากครับ',ro:'saai la-iat maak khrap',tr:'Kum çok ince.',bd:[{ro:'saai la-iat maak',tr:'kum çok ince',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w7',th:'ร่ม',ro:'rom',tr:'Semsiye (Plaj Semsiyesi)',
     tip:'"Rom" = şemsiye. Hem güneş hem yağmur için kullanılır. Plajda "rom chaa-hat" = plaj şemsiyesi.',
     ctx:'Plajlarda günlük 100-200 Baht\'a şemsiye kiralayabilirsin.',
     examples:[
       {th:'เช่าร่มได้ไหมครับ',ro:'chao rom dai mai khrap',tr:'Semsiye kiralayabilir miyim?',bd:[{ro:'chao rom dai mai',tr:'semsiye kiralayabilir mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ร่มวันละเท่าไรครับ',ro:'rom wan-la thao-rai khrap',tr:'Semsiye günlük ne kadar?',bd:[{ro:'rom wan-la thao-rai',tr:'semsiye günlük ne kadar',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ขอร่มสองอันครับ',ro:'khor rom song an khrap',tr:'Iki semsiye istiyorum.',bd:[{ro:'khor rom song an',tr:'iki semsiye',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ร่มชายหาดอยู่ที่ไหนครับ',ro:'rom chaai-haat yuu thii-nai khrap',tr:'Plaj semsiyesi nerede?',bd:[{ro:'rom chaai-haat yuu thii-nai',tr:'plaj semsiyesi nerede',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w8',th:'คลื่น',ro:'khluen',tr:'Dalga',
     tip:'"Khluen" = dalga. "Khluen sung" = yüksek dalga. Mayıs-Ekim arasında dalgalar büyük olur.',
     ctx:'Kırmızı bayrak = dalgalar tehlikeli, denize girme. Phuket hayat kurtarıcılarına uyu.',
     examples:[
       {th:'คลื่นแรงมากครับ',ro:'khluen raeng maak khrap',tr:'Dalgalar çok güçlü.',bd:[{ro:'khluen raeng maak',tr:'dalgalar çok güçlü',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'คลื่นสูงไหมครับ',ro:'khluen sung mai khrap',tr:'Dalgalar yüksek mi?',bd:[{ro:'khluen sung mai',tr:'dalgalar yüksek mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'คลื่นสงบแล้วครับ',ro:'khluen sa-ngop laeo khrap',tr:'Dalgalar yatıştı.',bd:[{ro:'khluen sa-ngop laeo',tr:'dalgalar artık yatışık',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ระวังคลื่นด้วยครับ',ro:'ra-wang khluen duay khrap',tr:'Dalgalara dikkat edin.',bd:[{ro:'ra-wang khluen duay',tr:'dalgalara dikkat et',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'คลื่นเล็กน้อยครับวันนี้',ro:'khluen lek noi khrap wan-nii',tr:'Bugun dalgalar küçük.',bd:[{ro:'khluen lek noi',tr:'dalgalar küçük',role:'V - Yuklem'},{ro:'wan-nii',tr:'bugün',role:'Zaman'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w9',th:'ลึก',ro:'luek',tr:'Derin',
     tip:'"Luek" = derin. "Ta-lee luek" = deniz derin. Zıt anlamı "tan" = sığ.',
     ctx:'Snorkel yapacaksan derin mi sığ mı olduğunu sormayı unutma.',
     examples:[
       {th:'น้ำลึกไหมครับ',ro:'naam luek mai khrap',tr:'Su derin mi?',bd:[{ro:'naam luek mai',tr:'su derin mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ตรงนี้ลึกมากครับ',ro:'trong-nii luek maak khrap',tr:'Burası çok derin.',bd:[{ro:'trong-nii luek maak',tr:'burası çok derin',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ลึกกี่เมตรครับ',ro:'luek gii-met khrap',tr:'Kaç metre derin?',bd:[{ro:'luek gii-met',tr:'kaç metre derin',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ไม่ลึกครับ ปลอดภัย',ro:'mai luek khrap plot-phai',tr:'Derin degil, güvenli.',bd:[{ro:'mai luek',tr:'derin değil',role:'Olumsuz'},{ro:'plot-phai',tr:'güvenli',role:'Kelime'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w10',th:'ปะการัง',ro:'pa-ga-rang',tr:'Mercan',
     tip:'"Pa-ga-rang" = mercan resifi. Phuket çevresi mercan bahçeleriyle ünlüdür.',
     ctx:'Similan ve Surin adalarında en güzel mercan resifleri. Snorkel veya dalis gerekli.',
     examples:[
       {th:'ปะการังสวยมากครับ',ro:'pa-ga-rang suay maak khrap',tr:'Mercanlar çok güzel.',bd:[{ro:'pa-ga-rang',tr:'mercan',role:'S - Ozne'},{ro:'suay maak',tr:'çok güzel',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'มีปะการังแถวนี้ไหมครับ',ro:'mii pa-ga-rang thaeo-nii mai khrap',tr:'Bu civarda mercan var mı?',bd:[{ro:'mii pa-ga-rang thaeo-nii mai',tr:'bu civarda mercan var mı',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'อย่าแตะปะการังครับ',ro:'yaa tae pa-ga-rang khrap',tr:'Mercanlara dokunma.',bd:[{ro:'yaa tae pa-ga-rang',tr:'mercanlara dokunma',role:'Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ดำน้ำดูปะการังครับ',ro:'dam-naam duu pa-ga-rang khrap',tr:'Dalarak mercanlara bakıyorum.',bd:[{ro:'dam-naam duu pa-ga-rang',tr:'dalarak mercanlara bak',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ปะการังเสียหายเพราะนักท่องเที่ยวครับ',ro:'pa-ga-rang sia-haai phro nak-thong-thiao khrap',tr:'Mercanlar turistler yüzünden zarar görüyor.',bd:[{ro:'pa-ga-rang sia-haai',tr:'mercanlar zarar görüyor',role:'V - Yuklem'},{ro:'phro nak-thong-thiao',tr:'turistler yüzünden',role:'Kelime'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
  ],
  grammar:[
    {
      title:'1. YAAK + fiil = istemek',
      formula:'YAAK + [FİİL] = ... yapmak istiyorum',
      explain:'"Yaak" kelimesi bir fiilin önüne gelince "istemek" anlamı kazandırır. Türkçedeki "-mek istiyorum" yapısına benzer. Phuket\'te plajda çok kullanılır.',
      tips:['"yaak" her zaman fiilden önce gelir','Soru yapmak için sona "mai" ekle: yaak ... mai?','Olumsuz: mai yaak = istemiyorum','yaak gin = yemek istemek','yaak pai = gitmek istemek','yaak non = uyumak istemek'],
      examples:[
        {th:'ผมอยากว่ายน้ำครับ',ro:'pom yaak waai-naam khrap',tr:'Yüzmek istiyorum.',bd:[{ro:'pom',tr:'ben',role:'S - Ozne'},{ro:'yaak',tr:'istemek',role:'Modal'},{ro:'waai-naam',tr:'yüzmek',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
        {th:'อยากเช่าร่มไหมครับ',ro:'yaak chao rom mai khrap',tr:'Semsiye kiralamak ister misiniz?',bd:[{ro:'yaak',tr:'istemek',role:'Modal'},{ro:'chao rom',tr:'semsiye kirala',role:'V - Yuklem'},{ro:'mai',tr:'soru eki',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
        {th:'ผมอยากดูปะการังครับ',ro:'pom yaak duu pa-ga-rang khrap',tr:'Mercanlara bakmak istiyorum.',bd:[{ro:'pom',tr:'ben',role:'S - Ozne'},{ro:'yaak',tr:'istemek',role:'Modal'},{ro:'duu pa-ga-rang',tr:'mercanlara bak',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
        {th:'ไม่อยากลงทะเลครับ คลื่นแรง',ro:'mai yaak long ta-lee khrap khluen raeng',tr:'Denize girmek istemiyorum, dalgalar güçlü.',bd:[{ro:'mai yaak long ta-lee',tr:'denize girmek istemiyorum',role:'Olumsuz'},{ro:'khluen raeng',tr:'dalgalar güçlü',role:'Kelime'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
        {th:'อยากไปเกาะพีพีครับ',ro:'yaak pai gao-phi-phi khrap',tr:'Phi Phi adasına gitmek istiyorum.',bd:[{ro:'yaak',tr:'istemek',role:'Modal'},{ro:'pai gao-phi-phi',tr:'Phi Phi\'ye git',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
      ]
    },
    {
      title:'2. ... dai-mai = yapabilir misin? / olabilir mi?',
      formula:'[FİİL] + DAI + MAI = ... yapabilir misiniz?',
      explain:'"Dai" = yapabilmek/olabilmek. "Mai" = soru eki. İkisi birlikte "... yapabilir misin?" anlamı verir. Hem yetenek hem de izin sormak için kullanılır.',
      tips:['"dai" fiilin hemen ardından gelir','Cevap: dai = evet/olur | mai dai = hayır/olmaz','Geçmiş: "dai" tek başına = başardım/yapabildim','"dai-mai" her durumda kibar bir soru şeklidir','Olumsuz form: mai dai = yapamam / olmuyor'],
      examples:[
        {th:'ว่ายน้ำได้ไหมครับ',ro:'waai-naam dai mai khrap',tr:'Yüzebilir misiniz?',bd:[{ro:'waai-naam',tr:'yüzmek',role:'V - Yuklem'},{ro:'dai mai',tr:'yapabilir mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
        {th:'เช่าเรือได้ไหมครับ',ro:'chao ruea dai mai khrap',tr:'Tekne kiralayabilir miyim?',bd:[{ro:'chao ruea',tr:'tekne kirala',role:'V - Yuklem'},{ro:'dai mai',tr:'yapabilir mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
        {th:'ลงทะเลได้ไหมครับ วันนี้',ro:'long ta-lee dai mai khrap wan-nii',tr:'Bugün denize girebilir miyim?',bd:[{ro:'long ta-lee',tr:'denize in',role:'V - Yuklem'},{ro:'dai mai',tr:'yapabilir mi',role:'Soru/Olumsuz'},{ro:'wan-nii',tr:'bugün',role:'Zaman'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
        {th:'ถ่ายรูปที่นี่ได้ไหมครับ',ro:'thai-ruup thii-nii dai mai khrap',tr:'Burada fotoğraf cekebilir miyim?',bd:[{ro:'thai-ruup thii-nii',tr:'burada fotoğraf çek',role:'V - Yuklem'},{ro:'dai mai',tr:'yapabilir mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
        {th:'ดำน้ำได้ไหมครับ แถวนี้',ro:'dam-naam dai mai khrap thaeo-nii',tr:'Bu civarda dalabilir miyim?',bd:[{ro:'dam-naam',tr:'dalmak',role:'V - Yuklem'},{ro:'dai mai',tr:'yapabilir mi',role:'Soru/Olumsuz'},{ro:'thaeo-nii',tr:'bu civarda',role:'Kelime'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
      ]
    },
    {
      title:'3. RA-WANG = dikkat et',
      formula:'RA-WANG + [TEHLİKE] = ... ye dikkat et',
      explain:'"Ra-wang" = dikkat et/dikkatli ol. Tehlike uyarısı için kullanılır. Plaj güvenliğinde çok önemli.',
      tips:['"ra-wang" genellikle cümle başında gelir','"ra-wang duay" = "lütfen dikkat et" (daha kibar)','khluen raeng = güçlü dalgalar','pla-muu = denizanası','daet ron = sıcak güneş'],
      examples:[
        {th:'ระวังคลื่นด้วยครับ',ro:'ra-wang khluen duay khrap',tr:'Dalgalara dikkat edin lütfen.',bd:[{ro:'ra-wang',tr:'dikkat et',role:'V - Yuklem'},{ro:'khluen',tr:'dalgalar',role:'O - Nesne'},{ro:'duay',tr:'lütfen',role:'Vurgu'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
        {th:'ระวังแดดครับ',ro:'ra-wang daet khrap',tr:'Gunese dikkat edin.',bd:[{ro:'ra-wang daet',tr:'güneşe dikkat et',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
        {th:'ระวังปลาแมงกะพรุนครับ',ro:'ra-wang pla-maeng-ga-phrun khrap',tr:'Denizanasına dikkat edin.',bd:[{ro:'ra-wang pla-maeng-ga-phrun',tr:'denizanasına dikkat et',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
        {th:'ระวังน้ำลึกครับ',ro:'ra-wang naam luek khrap',tr:'Derin suya dikkat edin.',bd:[{ro:'ra-wang naam luek',tr:'derin suya dikkat et',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
      ]
    },
  ],
  speaking:[
    {task:'Yüzmek istedigini söyle',th:'ผมอยากว่ายน้ำครับ',ro:'pom yaak waai-naam khrap',tr:'Yüzmek istiyorum.',bd:[{ro:'pom',tr:'ben',role:'S - Ozne'},{ro:'yaak waai-naam',tr:'yüzmek istiyorum',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Plaj güzel diye söyle',th:'หาดสวยมากครับ',ro:'haat suay maak khrap',tr:'Plaj çok güzel.',bd:[{ro:'haat',tr:'plaj',role:'S - Ozne'},{ro:'suay maak',tr:'çok güzel',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Semsiye kiralamanın fiyatını sor',th:'ร่มวันละเท่าไรครับ',ro:'rom wan-la thao-rai khrap',tr:'Semsiye günlük ne kadar?',bd:[{ro:'rom wan-la thao-rai',tr:'semsiye günlük ne kadar',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Denizin derin olup olmadıgını sor',th:'น้ำลึกไหมครับ',ro:'naam luek mai khrap',tr:'Su derin mi?',bd:[{ro:'naam luek mai',tr:'su derin mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Dalgaların güçlü oldugunu söyle',th:'คลื่นแรงมากครับ',ro:'khluen raeng maak khrap',tr:'Dalgalar çok güçlü.',bd:[{ro:'khluen raeng maak',tr:'dalgalar çok güçlü',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Güneş kreminin nerede oldugunu sor',th:'ครีมกันแดดอยู่ที่ไหนครับ',ro:'kriim-gan-daet yuu thii-nai khrap',tr:'Güneş kremi nerede?',bd:[{ro:'kriim-gan-daet yuu thii-nai',tr:'güneş kremi nerede',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Tekne biletini almak istedigini söyle',th:'ขอซื้อตั๋วเรือครับ',ro:'khor sue tua ruea khrap',tr:'Tekne bileti almak istiyorum.',bd:[{ro:'khor sue tua ruea',tr:'tekne bileti almak',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Mercanlara dokunulmasını yasakla',th:'อย่าแตะปะการังครับ',ro:'yaa tae pa-ga-rang khrap',tr:'Mercanlara dokunma.',bd:[{ro:'yaa tae pa-ga-rang',tr:'mercanlara dokunma',role:'Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Kumun çok sıcak oldugunu söyle',th:'ทรายร้อนมากครับ',ro:'saai ron maak khrap',tr:'Kum çok sıcak.',bd:[{ro:'saai ron maak',tr:'kum çok sıcak',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Denize girip giremeyecegini sor',th:'ลงทะเลได้ไหมครับ',ro:'long ta-lee dai mai khrap',tr:'Denize girebilir miyim?',bd:[{ro:'long ta-lee dai mai',tr:'denize girebilir mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Phi Phi adasına gitmek istedigini söyle',th:'อยากไปเกาะพีพีครับ',ro:'yaak pai gao-phi-phi khrap',tr:'Phi Phi adasına gitmek istiyorum.',bd:[{ro:'yaak pai gao-phi-phi',tr:'Phi Phi\'ye gitmek istiyorum',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Deniz suyu berrak diye söyle',th:'น้ำทะเลใสครับ',ro:'naam ta-lee sai khrap',tr:'Deniz suyu berrak.',bd:[{ro:'naam ta-lee sai',tr:'deniz suyu berrak',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
  ],
  dialogues:[
    {title:'🏖️ Plajda Semsiye Kiralama',
     lines:[
       {s:'Tom',th:'สวัสดีครับ เช่าร่มได้ไหมครับ',ro:'sa-wat-dee khrap chao rom dai mai khrap',tr:'Merhaba, semsiye kiralayabilir miyim?',bd:[{ro:'sa-wat-dee',tr:'merhaba',role:'Kelime'},{ro:'chao rom dai mai',tr:'semsiye kiralayabilir mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {s:'Lucy',th:'ได้ค่ะ วันละร้อยห้าสิบบาทค่ะ',ro:'dai kha wan-la roi-haa-sip baht kha',tr:'Tabii ki, günlük 150 Baht.',bd:[{ro:'dai',tr:'olur/evet',role:'Kelime'},{ro:'wan-la roi-haa-sip baht',tr:'günlük 150 Baht',role:'Kelime'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
       {s:'Tom',th:'ขอสองอันครับ และเก้าอี้ด้วยได้ไหมครับ',ro:'khor song an khrap lae gao-ii duay dai mai khrap',tr:'Iki tane istiyorum, sandalye de olabilir mi?',bd:[{ro:'khor song an',tr:'iki tane istiyorum',role:'V - Yuklem'},{ro:'lae gao-ii duay dai mai',tr:'sandalye de olabilir mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {s:'Lucy',th:'ได้ค่ะ เก้าอี้ฟรีค่ะ',ro:'dai kha gao-ii free kha',tr:'Tabii, sandalye ücretsiz.',bd:[{ro:'dai',tr:'olur',role:'Kelime'},{ro:'gao-ii free',tr:'sandalye ücretsiz',role:'Kelime'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
       {s:'Tom',th:'ขอบคุณมากครับ',ro:'khob-khun maak khrap',tr:'Cok tesekkür ederim.',bd:[{ro:'khob-khun maak',tr:'çok teşekkür',role:'Kelime'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {title:'🌊 Deniz Durumunu Sormak',
     lines:[
       {s:'Tom',th:'วันนี้คลื่นเป็นยังไงบ้างครับ',ro:'wan-nii khluen pen yang-ngai bang khrap',tr:'Bugun dalgalar nasıl?',bd:[{ro:'wan-nii khluen pen yang-ngai bang',tr:'bugün dalgalar nasıl',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {s:'Lucy',th:'คลื่นนิดหน่อยค่ะ ปลอดภัยค่ะ',ro:'khluen nit-noi kha plot-phai kha',tr:'Dalgalar biraz var, güvenli.',bd:[{ro:'khluen nit-noi',tr:'dalgalar biraz',role:'Kelime'},{ro:'plot-phai',tr:'güvenli',role:'Kelime'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
       {s:'Tom',th:'ว่ายน้ำได้ไหมครับ',ro:'waai-naam dai mai khrap',tr:'Yüzebilir miyim?',bd:[{ro:'waai-naam dai mai',tr:'yüzebilir miyim',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {s:'Lucy',th:'ได้ค่ะ แต่ระวังด้วยนะคะ',ro:'dai kha tae ra-wang duay na kha',tr:'Evet ama dikkat edin.',bd:[{ro:'dai',tr:'evet',role:'Kelime'},{ro:'tae ra-wang duay na',tr:'ama dikkat et',role:'Vurgu'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {title:'🤿 Snorkel Turu',
     lines:[
       {s:'Tom',th:'ทัวร์ดำน้ำดูปะการังมีไหมครับ',ro:'thua dam-naam duu pa-ga-rang mii mai khrap',tr:'Mercan dalış turu var mı?',bd:[{ro:'thua dam-naam duu pa-ga-rang',tr:'mercan dalış turu',role:'S - Ozne'},{ro:'mii mai',tr:'var mı',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {s:'Lucy',th:'มีค่ะ ออกตอนเช้าเก้าโมงค่ะ',ro:'mii kha ok ton-chao gao-mong kha',tr:'Var, sabah saat 9\'da kalkıyor.',bd:[{ro:'mii',tr:'var',role:'Kelime'},{ro:'ok ton-chao gao-mong',tr:'sabah 9\'da kalkıyor',role:'V - Yuklem'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
       {s:'Tom',th:'ราคาเท่าไรครับ รวมอาหารไหมครับ',ro:'raa-khaa thao-rai khrap ruam aa-haan mai khrap',tr:'Fiyat ne kadar, yemek dahil mi?',bd:[{ro:'raa-khaa thao-rai',tr:'fiyat ne kadar',role:'Soru/Olumsuz'},{ro:'ruam aa-haan mai',tr:'yemek dahil mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {s:'Lucy',th:'คนละ 1500 บาทค่ะ รวมอาหารกลางวันและอุปกรณ์ค่ะ',ro:'khon-la neung-phan-haa-roi baht kha ruam aa-haan-glang-wan lae u-pa-gon kha',tr:'Kişi başı 1500 Baht, ögle yemeği ve ekipman dahil.',bd:[{ro:'khon-la neung-phan-haa-roi baht',tr:'kişi başı 1500 Baht',role:'Kelime'},{ro:'ruam aa-haan-glang-wan lae u-pa-gon',tr:'ögle ve ekipman dahil',role:'Kelime'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {title:'⛵ Longtail Tekne',
     lines:[
       {s:'Tom',th:'เรือหัวโทงไปหาดในค่าเท่าไรครับ',ro:'ruea long-tail pai haat-nai kha thao-rai khrap',tr:'Longtail tekne ile iç koya ne kadar?',bd:[{ro:'ruea long-tail pai haat-nai',tr:'longtail ile iç koya git',role:'V - Yuklem'},{ro:'kha thao-rai',tr:'ne kadar',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {s:'Lucy',th:'ห้าร้อยบาทไปกลับค่ะ',ro:'haa-roi baht pai-glap kha',tr:'500 Baht gidis-donus.',bd:[{ro:'haa-roi baht pai-glap',tr:'500 Baht gidiş-dönüş',role:'Kelime'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
       {s:'Tom',th:'ใช้เวลานานไหมครับ',ro:'chai-wee-laa naan mai khrap',tr:'Uzun sürer mi?',bd:[{ro:'chai-wee-laa naan mai',tr:'uzun sürer mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {s:'Lucy',th:'ประมาณสิบห้านาทีค่ะ',ro:'pra-maan sip-haa naa-thii kha',tr:'Yaklasik 15 dakika.',bd:[{ro:'pra-maan sip-haa naa-thii',tr:'yaklaşık 15 dakika',role:'Kelime'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
       {s:'Tom',th:'โอเคครับ ไปเลยครับ',ro:'o-kee khrap pai loey khrap',tr:'Tamam, gidelim hemen.',bd:[{ro:'o-kee pai loey',tr:'tamam hemen gidelim',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
  ],
  listening:[
    {th:'หาดสวยมากครับ',ro:'haat suay maak khrap',tr:'Plaj çok güzel.',bd:[{ro:'haat',tr:'plaj',role:'S - Ozne'},{ro:'suay maak',tr:'çok güzel',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {th:'ผมอยากว่ายน้ำครับ',ro:'pom yaak waai-naam khrap',tr:'Yüzmek istiyorum.',bd:[{ro:'pom yaak waai-naam',tr:'yüzmek istiyorum',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {th:'คลื่นแรงมากครับ ระวังด้วย',ro:'khluen raeng maak khrap ra-wang duay',tr:'Dalgalar çok güçlü, dikkat edin.',bd:[{ro:'khluen raeng maak',tr:'dalgalar çok güçlü',role:'V - Yuklem'},{ro:'ra-wang duay',tr:'dikkat edin',role:'Vurgu'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {th:'น้ำลึกไหมครับ',ro:'naam luek mai khrap',tr:'Su derin mi?',bd:[{ro:'naam luek mai',tr:'su derin mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {th:'ครีมกันแดดอยู่ที่ไหนครับ',ro:'kriim-gan-daet yuu thii-nai khrap',tr:'Güneş kremi nerede?',bd:[{ro:'kriim-gan-daet yuu thii-nai',tr:'güneş kremi nerede',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {th:'เช่าร่มวันละร้อยห้าสิบบาทค่ะ',ro:'chao rom wan-la roi-haa-sip baht kha',tr:'Semsiye kiralama günlük 150 Baht.',bd:[{ro:'chao rom wan-la roi-haa-sip baht',tr:'günlük 150 Baht semsiye',role:'Kelime'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
    {th:'ปะการังสวยมากครับ',ro:'pa-ga-rang suay maak khrap',tr:'Mercanlar çok güzel.',bd:[{ro:'pa-ga-rang suay maak',tr:'mercanlar çok güzel',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {th:'อย่าแตะปะการังครับ',ro:'yaa tae pa-ga-rang khrap',tr:'Mercanlara dokunmayın.',bd:[{ro:'yaa tae pa-ga-rang',tr:'mercanlara dokunma',role:'Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {th:'เรือออกตอนเช้าเก้าโมงครับ',ro:'ruea ok ton-chao gao-mong khrap',tr:'Tekne sabah 9\'da kalkıyor.',bd:[{ro:'ruea ok ton-chao gao-mong',tr:'tekne sabah 9\'da kalkıyor',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {th:'ทรายขาวสวยมากครับ',ro:'saai khao suay maak khrap',tr:'Beyaz kum çok güzel.',bd:[{ro:'saai khao suay maak',tr:'beyaz kum çok güzel',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
  ],
  quiz:[
    {q:'"haat" ne demek?',opts:['Deniz','Plaj','Kum','Dalga'],c:1},
    {q:'"ta-lee" ne demek?',opts:['Plaj','Göl','Deniz','Nehir'],c:2},
    {q:'"waai-naam" ne demek?',opts:['Yüzmek','Dalmak','Kürek çekmek','Kosmak'],c:0},
    {q:'"khluen" ne demek?',opts:['Kum','Şemsiye','Mercan','Dalga'],c:3},
    {q:'"luek" ne demek?',opts:['Sığ','Sıcak','Derin','Berrak'],c:2},
    {q:'"pa-ga-rang" ne demek?',opts:['Deniz kaplumbağası','Mercan','Denizanası','Balık'],c:1},
    {q:'"rom" ne demek?',opts:['Tekne','Kum','Semsiye','Güneş'],c:2},
    {q:'"ruea" ne demek?',opts:['Tekne','Plaj','Şemsiye','Kum'],c:0},
    {q:'"saai" ne demek?',opts:['Su','Kum','Güneş','Deniz'],c:1},
    {q:'"yaak" kelimesinin görevi nedir?',opts:['Soru yapmak','Olumsuz yapmak','Istemek anlamı vermek','Geçmiş yapmak'],c:2},
    {q:'"yaak waai-naam" ne demek?',opts:['Yüzebiliyorum','Yüzmek istemiyorum','Yüzmek istiyorum','Yüzdüm'],c:2},
    {q:'"waai-naam dai-mai" ne demek?',opts:['Yüzmek istiyorum','Yüzebilir misin','Yüzdün mü','Yüzmek zor'],c:1},
    {q:'"ra-wang khluen" ne demek?',opts:['Dalgalar güzel','Dalgalara dikkat et','Dalga yok','Dalgalar sıcak'],c:1},
    {q:'"kriim-gan-daet" ne demek?',opts:['Nemlendirici krem','Güneş kremi','Saç kremi','El kremi'],c:1},
    {q:'Phuket kırmızı plaj bayrağı ne anlama gelir?',opts:['Güzel hava','Denize girme, tehlikeli','Snorkel bölgesi','Temiz su'],c:1},
    {q:'"long ta-lee" ne demek?',opts:['Denizi görmek','Deniz kenarı','Denize inmek','Deniz derinligi'],c:2},
    {q:'"naam ta-lee sai" ne demek?',opts:['Deniz suyu sıcak','Deniz suyu tuzlu','Deniz suyu berrak','Deniz suyu derin'],c:2},
    {q:'"plot-phai" ne demek?',opts:['Tehlikeli','Derin','Güvenli','Temiz'],c:2},
    {q:'"dam-naam" ne demek?',opts:['Yüzmek','Dalmak','Kürek cekmek','Balık tutmak'],c:1},
    {q:'Phuket\'e bakan deniz hangisidir?',opts:['Hint Okyanusu','Pasifik Okyanusu','Andaman Denizi','Güney Cin Denizi'],c:2},
  ],
};

LESSONS[10] = L10;
