// Ders 39 verisi — CORE 2000 (1327-1389)
const L39 = {
  words:[
    {id:'c1327',ro:'raawng-hai',tr:'ağlamak',en:'cry',tip:'',ctx:'',examples:[]},
    {id:'c1328',ro:'nam-dtaa',tr:'uzak',en:'f ar',tip:'',ctx:'',examples:[]},
    {id:'c1329',ro:'sru',tr:'sivilce',en:'pimple',tip:'',ctx:'',examples:[]},
    {id:'c1330',ro:'sru',tr:'kaçmak',en:'break out',tip:'',ctx:'',examples:[]},
    {id:'c1331',ro:'khaang',tr:'çene',en:'chin',tip:'',ctx:'',examples:[]},
    {id:'c1332',ro:'naa-phaak',tr:'alın',en:'forehead',tip:'',ctx:'',examples:[]},
    {id:'c1333',ro:'blaawn',tr:'sarı saç',en:'blonde hair',tip:'',ctx:'',examples:[]},
    {id:'c1334',ro:'dam',tr:'siyah saç',en:'black hair',tip:'',ctx:'',examples:[]},
    {id:'c1337',ro:'fan',tr:'diş',en:'tooth',tip:'',ctx:'',examples:[]},
    {id:'c1338',ro:'rfu-raauy',tr:'kırışıklık',en:'wrinkle',tip:'',ctx:'',examples:[]},
    {id:'c1339',ro:'khiu',tr:'kaş',en:'eyebrow',tip:'',ctx:'',examples:[]},
    {id:'c1340',ro:'bpfuueak-dtaa',tr:'göz kapağı',en:'eyelid',tip:'',ctx:'',examples:[]},
    {id:'c1343',ro:'fin',tr:'dil',en:'tongue',tip:'',ctx:'',examples:[]},
    {id:'c1345',ro:'ruu',tr:'burun deliği',en:'nostril',tip:'',ctx:'',examples:[]},
    {id:'c1347',ro:'naawng',tr:'buzağı',en:'calf',tip:'',ctx:'',examples:[]},
    {id:'c1348',ro:'tep-thaao',tr:'ayak tırnağı',en:'toenail',tip:'',ctx:'',examples:[]},
    {id:'c1350',ro:'eeo',tr:'bel',en:'waist',tip:'',ctx:'',examples:[]},
    {id:'c1351',ro:'gra-duuk-sa-baa',tr:'diz kapağı',en:'kneecap',tip:'',ctx:'',examples:[]},
    {id:'c1352',ro:'khaa-niip',tr:'kasık',en:'groin',tip:'',ctx:'',examples:[]},
    {id:'c1353',ro:'en-raauy-waai',tr:'Aşil topuğu',en:'Achilles\' heel',tip:'',ctx:'',examples:[]},
    {id:'c1354',ro:'bplaai-khaaen',tr:'önkol',en:'forearm',tip:'',ctx:'',examples:[]},
    {id:'c1356',ro:'niu-gauy',tr:'serçe parmak',en:'pinkie',tip:'',ctx:'',examples:[]},
    {id:'c1357',ro:'niu-glaang',tr:'orta parmak',en:'middle finger',tip:'',ctx:'',examples:[]},
    {id:'c1358',ro:'niu-chii',tr:'işaret parmağı',en:'index finger',tip:'',ctx:'',examples:[]},
    {id:'c1359',ro:'niu-naang',tr:'yüzük parmağı',en:'ring finger',tip:'',ctx:'',examples:[]},
    {id:'c1360',ro:'sfi-khroong',tr:'kaburga',en:'rib',tip:'',ctx:'',examples:[]},
    {id:'c1361',ro:'chawng-thaawng',tr:'karın',en:'abdomen',tip:'',ctx:'',examples:[]},
    {id:'c1363',ro:'dtai',tr:'böbrek',en:'kidney',tip:'',ctx:'',examples:[]},
    {id:'c1364',ro:'gra-duuk-sa-bak',tr:'kürek kemiği',en:'shoulder blade',tip:'',ctx:'',examples:[]},
    {id:'c1365',ro:'gan-grai',tr:'makas',en:'scissors',tip:'',ctx:'',examples:[]},
    {id:'c1367',ro:'khiim-niip',tr:'cımbız',en:'tweezers',tip:'',ctx:'',examples:[]},
    {id:'c1368',ro:'yaa',tr:'yara bandı',en:'bandaid',tip:'',ctx:'',examples:[]},
    {id:'c1369',ro:'phlaae',tr:'yapışkan bant',en:'adhesive tape',tip:'',ctx:'',examples:[]},
    {id:'c1370',ro:'gaai',tr:'dy sıcaklığı',en:'of dy temperature',tip:'',ctx:'',examples:[]},
    {id:'c1371',ro:'wat',tr:'ateşini ölçmek',en:'take one\'s temperature',tip:'',ctx:'',examples:[]},
    {id:'c1372',ro:'gaan-phaa-dtat',tr:'operasyon',en:'operation',tip:'',ctx:'',examples:[]},
    {id:'c1373',ro:'wat',tr:'nabzını almak',en:'take one\'s pulse',tip:'',ctx:'',examples:[]},
    {id:'c1375',ro:'chiit',tr:'enjeksiyon yapmak',en:'give an injection',tip:'',ctx:'',examples:[]},
    {id:'c1376',ro:'bpra-wat',tr:'tıbbi geçmiş',en:'medical history',tip:'',ctx:'',examples:[]},
    {id:'c1378',ro:'phaap',tr:'röntgen',en:'X-ray',tip:'',ctx:'',examples:[]},
    {id:'c1380',ro:'thaang',tr:'intravenöz',en:'intravenous',tip:'',ctx:'',examples:[]},
    {id:'c1381',ro:'phaaet',tr:'doktor ofisi',en:'doctor\'s office',tip:'',ctx:'',examples:[]},
    {id:'c1382',ro:'bpa-raawt-wat-khai',tr:'termometre',en:'thermometer',tip:'',ctx:'',examples:[]},
    {id:'c1383',ro:'khem-chiit-yaa',tr:'iğne',en:'needle',tip:'',ctx:'',examples:[]},
    {id:'c1384',ro:'aap-nam',tr:'banyo yap',en:'ke a bath',tip:'',ctx:'',examples:[]},
    {id:'c1385',ro:'bpuuai',tr:'hasta',en:'sick',tip:'',ctx:'',examples:[]},
    {id:'c1386',ro:'yaa-nam-gaae-ai',tr:'öksürük şurubu',en:'cough syrup',tip:'',ctx:'',examples:[]},
    {id:'c1387',ro:'aaet-phai-rin',tr:'aspirin',en:'aspirin',tip:'',ctx:'',examples:[]},
    {id:'c1388',ro:'yaa',tr:'antibiyotik',en:'antibiotic',tip:'',ctx:'',examples:[]},
    {id:'c1389',ro:'wak-siin',tr:'aşı',en:'vaccine',tip:'',ctx:'',examples:[]},
  ]
};

LESSONS[39] = L39;
