// Ders 26 verisi — CORE 2000 (435-512)
const L26 = {
  words:[
    {id:'c435',ro:'yaawt',tr:'satış',en:'sale',tip:'',ctx:'',examples:[]},
    {id:'c437',ro:'thfi',tr:'dördüncü',en:'fourth',tip:'',ctx:'',examples:[]},
    {id:'c438',ro:'thfi',tr:'beşinci',en:'fth',tip:'',ctx:'',examples:[]},
    {id:'c439',ro:'thfi',tr:'altıncı',en:'sixth',tip:'',ctx:'',examples:[]},
    {id:'c440',ro:'thfi',tr:'yedinci',en:'seventh',tip:'',ctx:'',examples:[]},
    {id:'c443',ro:'sa-buu',tr:'sıvı sabun',en:'liquid soap',tip:'',ctx:'',examples:[]},
    {id:'c444',ro:'bpet',tr:'ördek',en:'duck',tip:'',ctx:'',examples:[]},
    {id:'c445',ro:'gaa',tr:'karga',en:'crow',tip:'',ctx:'',examples:[]},
    {id:'c447',ro:'yung',tr:'sivrisinek',en:'mosquito',tip:'',ctx:'',examples:[]},
    {id:'c449',ro:'maae-baan',tr:'ev hanımı',en:'housewife',tip:'',ctx:'',examples:[]},
    {id:'c450',ro:'naam-khaeng',tr:'buz',en:'ice',tip:'',ctx:'',examples:[]},
    {id:'c451',ro:'saat',tr:'tarih',en:'history',tip:'',ctx:'',examples:[]},
    {id:'c452',ro:'wf-chaa',tr:'coğrafya',en:'geography',tip:'',ctx:'',examples:[]},
    {id:'c455',ro:'raa-khaa',tr:'fiyat',en:'price',tip:'',ctx:'',examples:[]},
    {id:'c456',ro:'khuu-bpawng',tr:'kupon',en:'coupon',tip:'',ctx:'',examples:[]},
    {id:'c457',ro:'chawng',tr:'koridor',en:'aisle',tip:'',ctx:'',examples:[]},
    {id:'c459',ro:'phaap-thaai',tr:'fotoğraf',en:'photograph',tip:'',ctx:'',examples:[]},
    {id:'c461',ro:'thfi',tr:'dokuzuncu',en:'ninth',tip:'',ctx:'',examples:[]},
    {id:'c462',ro:'thfi',tr:'onuncu',en:'tenth',tip:'',ctx:'',examples:[]},
    {id:'c463',ro:'thfi',tr:'sekizinci',en:'eighth',tip:'',ctx:'',examples:[]},
    {id:'c464',ro:'mfit-goon',tr:'tıraş bıçağı',en:'shaving razor',tip:'',ctx:'',examples:[]},
    {id:'c465',ro:'naa',tr:'lif',en:'washcloth',tip:'',ctx:'',examples:[]},
    {id:'c468',ro:'sawm',tr:'çatal',en:'fork',tip:'',ctx:'',examples:[]},
    {id:'c469',ro:'mfit',tr:'bıçak',en:'knife',tip:'',ctx:'',examples:[]},
    {id:'c470',ro:'jaan',tr:'plaka',en:'plate',tip:'',ctx:'',examples:[]},
    {id:'c473',ro:'nguu',tr:'yılan',en:'snake',tip:'',ctx:'',examples:[]},
    {id:'c475',ro:'nak-aawk-baaep',tr:'tasarımcı',en:'designer',tip:'',ctx:'',examples:[]},
    {id:'c477',ro:'tha-haan',tr:'asker',en:'soldier',tip:'',ctx:'',examples:[]},
    {id:'c480',ro:'faem',tr:'dosya',en:'folder',tip:'',ctx:'',examples:[]},
    {id:'c481',ro:'gra-tha',tr:'Inpan',en:'ingpan',tip:'',ctx:'',examples:[]},
    {id:'c483',ro:'aang',tr:'atmak',en:'sink',tip:'',ctx:'',examples:[]},
    {id:'c485',ro:'thaang-aawk',tr:'çıkış',en:'exit',tip:'',ctx:'',examples:[]},
    {id:'c487',ro:'thaang',tr:'bavul',en:'suitcase',tip:'',ctx:'',examples:[]},
    {id:'c488',ro:'nak-thawng-thfiao',tr:'turist',en:'tourist',tip:'',ctx:'',examples:[]},
    {id:'c489',ro:'rat-tha-saat',tr:'politika',en:'politics',tip:'',ctx:'',examples:[]},
    {id:'c490',ro:'tha-yaa',tr:'biyoloji',en:'biology',tip:'',ctx:'',examples:[]},
    {id:'c491',ro:'wi-chaa',tr:'kimya',en:'chemistry',tip:'',ctx:'',examples:[]},
    {id:'c492',ro:'wf-chaa',tr:'fizik',en:'physics',tip:'',ctx:'',examples:[]},
    {id:'c493',ro:'wf-chaa',tr:'ekonomi',en:'economics',tip:'',ctx:'',examples:[]},
    {id:'c494',ro:'waang',tr:'koymak',en:'put',tip:'',ctx:'',examples:[]},
    {id:'c495',ro:'jam-dai',tr:'f üyesi',en:'f member',tip:'',ctx:'',examples:[]},
    {id:'c497',ro:'sai',tr:'alışveriş Sepeti',en:'shopping cart',tip:'',ctx:'',examples:[]},
    {id:'c498',ro:'phlaat-sa-dtik',tr:'plastik torba',en:'plastic bag',tip:'',ctx:'',examples:[]},
    {id:'c499',ro:'nang',tr:'komedi',en:'comedy',tip:'',ctx:'',examples:[]},
    {id:'c500',ro:'na-wa-nf-yaai',tr:'roman',en:'novel',tip:'',ctx:'',examples:[]},
    {id:'c505',ro:'dtiiang-naawn',tr:'yatak',en:'bed',tip:'',ctx:'',examples:[]},
    {id:'c506',ro:'gra-jok',tr:'ayna',en:'mirror',tip:'',ctx:'',examples:[]},
    {id:'c508',ro:'gwaat',tr:'süpürmek',en:'sweep',tip:'',ctx:'',examples:[]},
    {id:'c509',ro:'gep',tr:'uzakta',en:'ut away',tip:'',ctx:'',examples:[]},
    {id:'c512',ro:'faa-ren-hai',tr:'Fahrenhayt',en:'Fahrenheit',tip:'',ctx:'',examples:[]},
  ]
};

LESSONS[26] = L26;
