// Ders 30 verisi — CORE 2000 (712-772)
const L30 = {
  words:[
    {id:'c712',ro:'chek',tr:'Çıkış yapmak',en:'check out',tip:'',ctx:'',examples:[]},
    {id:'c713',ro:'aawn',tr:'ışık',en:'light',tip:'',ctx:'',examples:[]},
    {id:'c714',ro:'thaawng',tr:'altın',en:'gold',tip:'',ctx:'',examples:[]},
    {id:'c715',ro:'chom-phuu',tr:'pembe',en:'pink',tip:'',ctx:'',examples:[]},
    {id:'c716',ro:'ngoen',tr:'gümüş',en:'silver',tip:'',ctx:'',examples:[]},
    {id:'c717',ro:'beet',tr:'bej',en:'beige',tip:'',ctx:'',examples:[]},
    {id:'c718',ro:'raat-booe-rfi',tr:'ahududu',en:'raspberry',tip:'',ctx:'',examples:[]},
    {id:'c719',ro:'aa-gaan',tr:'öksürük',en:'cough',tip:'',ctx:'',examples:[]},
    {id:'c720',ro:'gra-thiiam',tr:'sarımsak',en:'garlic',tip:'',ctx:'',examples:[]},
    {id:'c721',ro:'nuuat',tr:'bıyık',en:'mustache',tip:'',ctx:'',examples:[]},
    {id:'c723',ro:'dii',tr:'DVD oynatıcı',en:'DVD player',tip:'',ctx:'',examples:[]},
    {id:'c724',ro:'phat-lom',tr:'fan',en:'fan',tip:'',ctx:'',examples:[]},
    {id:'c726',ro:'dtao-gaaet',tr:'soba',en:'stove',tip:'',ctx:'',examples:[]},
    {id:'c727',ro:'roong-riian',tr:'suek-saa ilkokulu',en:'suek-saa elementary school',tip:'',ctx:'',examples:[]},
    {id:'c728',ro:'roong-riian',tr:'ortaokul',en:'middle school',tip:'',ctx:'',examples:[]},
    {id:'c729',ro:'roong-riian',tr:'yom-bplaai lisesi',en:'yom-bplaai high school',tip:'',ctx:'',examples:[]},
    {id:'c731',ro:'khruu-yai',tr:'müdür',en:'principal',tip:'',ctx:'',examples:[]},
    {id:'c732',ro:'sa-waang',tr:'parlak',en:'bright',tip:'',ctx:'',examples:[]},
    {id:'c733',ro:'laep-thawp',tr:'dizüstü bilgisayar',en:'laptop computer',tip:'',ctx:'',examples:[]},
    {id:'c734',ro:'mao',tr:'fare',en:'mouse',tip:'',ctx:'',examples:[]},
    {id:'c735',ro:'lam-phoong',tr:'daha iyi',en:'eaker',tip:'',ctx:'',examples:[]},
    {id:'c736',ro:'wep-khaem',tr:'web kamerası',en:'webcam',tip:'',ctx:'',examples:[]},
    {id:'c737',ro:'mai-khroo-foon',tr:'mikrofon',en:'microphone',tip:'',ctx:'',examples:[]},
    {id:'c740',ro:'khaao-phoot',tr:'Mısır',en:'corn',tip:'',ctx:'',examples:[]},
    {id:'c741',ro:'dtiiang-diiao',tr:'tek kişilik yatak',en:'single bed',tip:'',ctx:'',examples:[]},
    {id:'c743',ro:'roong-raaem',tr:'otel',en:'hotel',tip:'',ctx:'',examples:[]},
    {id:'c744',ro:'faai',tr:'ön büro',en:'front desk',tip:'',ctx:'',examples:[]},
    {id:'c745',ro:'ma-haa-sa-mut',tr:'sf-fik Pasifik Okyanusu',en:'sf-fik Pacific Ocean',tip:'',ctx:'',examples:[]},
    {id:'c746',ro:'ma-haa-sa-mut',tr:'Atlantik Okyanusu',en:'Atlantic Ocean',tip:'',ctx:'',examples:[]},
    {id:'c747',ro:'ma-haa-sa-mut',tr:'Hint Okyanusu',en:'Indian Ocean',tip:'',ctx:'',examples:[]},
    {id:'c748',ro:'tha-wfip',tr:'Avustralya',en:'Australia',tip:'',ctx:'',examples:[]},
    {id:'c749',ro:'tha-wfip',tr:'Antarktika',en:'Antarctica',tip:'',ctx:'',examples:[]},
    {id:'c750',ro:'tha-wfip',tr:'Asya',en:'Asia',tip:'',ctx:'',examples:[]},
    {id:'c751',ro:'tha-wfip',tr:'Afrika',en:'Africa',tip:'',ctx:'',examples:[]},
    {id:'c752',ro:'tha-wfip',tr:'Avrupa',en:'Europe',tip:'',ctx:'',examples:[]},
    {id:'c753',ro:'tha-wfip',tr:'Kuzey Amerika',en:'North America',tip:'',ctx:'',examples:[]},
    {id:'c754',ro:'tha-wfip',tr:'Güney Amerika',en:'South America',tip:'',ctx:'',examples:[]},
    {id:'c755',ro:'khraam',tr:'çivit',en:'indigo',tip:'',ctx:'',examples:[]},
    {id:'c756',ro:'phfit',tr:'şeftali',en:'peach',tip:'',ctx:'',examples:[]},
    {id:'c757',ro:'khem',tr:'karanlık',en:'dark',tip:'',ctx:'',examples:[]},
    {id:'c758',ro:'naa-ram-khaan',tr:'sinir bozucu',en:'annoying',tip:'',ctx:'',examples:[]},
    {id:'c760',ro:'naa-ak',tr:'göğüs',en:'breast',tip:'',ctx:'',examples:[]},
    {id:'c761',ro:'gra-bpao-sa-phaai-lang',tr:'sırt çantası',en:'backpack',tip:'',ctx:'',examples:[]},
    {id:'c762',ro:'sai-din-saaw',tr:'kalem kurşun',en:'pencil lead',tip:'',ctx:'',examples:[]},
    {id:'c765',ro:'gap',tr:'kalemtıraş',en:'pencil sharpener',tip:'',ctx:'',examples:[]},
    {id:'c766',ro:'gwaang',tr:'geniş',en:'wide',tip:'',ctx:'',examples:[]},
    {id:'c767',ro:'khaaep',tr:'dar',en:'narrow',tip:'',ctx:'',examples:[]},
    {id:'c768',ro:'khaeng',tr:'zor',en:'hard',tip:'',ctx:'',examples:[]},
    {id:'c770',ro:'aep-bpri-khawt',tr:'ricot',en:'ricot',tip:'',ctx:'',examples:[]},
    {id:'c772',ro:'mee-lawn',tr:'kavun',en:'melon',tip:'',ctx:'',examples:[]},
  ]
};

LESSONS[30] = L30;
