// Ders 31 verisi — CORE 2000 (773-837)
const L31 = {
  words:[
    {id:'c773',ro:'ma-duuea',tr:'incir',en:'fig',tip:'',ctx:'',examples:[]},
    {id:'c779',ro:'thuua-ngaawk',tr:'fasulye filizi',en:'bean sprout',tip:'',ctx:'',examples:[]},
    {id:'c781',ro:'mii',tr:'umutlu',en:'hopeful',tip:'',ctx:'',examples:[]},
    {id:'c784',ro:'ruuai',tr:'zengin',en:'rich',tip:'',ctx:'',examples:[]},
    {id:'c785',ro:'yaak-jon',tr:'fakir',en:'poor',tip:'',ctx:'',examples:[]},
    {id:'c786',ro:'naa-jaaw',tr:'fonitor',en:'fonitor',tip:'',ctx:'',examples:[]},
    {id:'c787',ro:'bpaen',tr:'klavye',en:'keyboard',tip:'',ctx:'',examples:[]},
    {id:'c788',ro:'huu-fang',tr:'kulaklıklar',en:'headphones',tip:'',ctx:'',examples:[]},
    {id:'c789',ro:'sa-uek',tr:'hıçkırık',en:'hiccup',tip:'',ctx:'',examples:[]},
    {id:'c793',ro:'ma-naao',tr:'limon',en:'lemon',tip:'',ctx:'',examples:[]},
    {id:'c794',ro:'gon',tr:'kalça',en:'buttocks',tip:'',ctx:'',examples:[]},
    {id:'c795',ro:'lai',tr:'omuz',en:'shoulder',tip:'',ctx:'',examples:[]},
    {id:'c796',ro:'glaam-nuuea',tr:'kas',en:'muscle',tip:'',ctx:'',examples:[]},
    {id:'c797',ro:'gra-duuk',tr:'kemik',en:'bone',tip:'',ctx:'',examples:[]},
    {id:'c798',ro:'khrao',tr:'sakal',en:'beard',tip:'',ctx:'',examples:[]},
    {id:'c799',ro:'man-theet',tr:'tatlı patates',en:'sweet potato',tip:'',ctx:'',examples:[]},
    {id:'c800',ro:'het',tr:'mantar',en:'mushroom',tip:'',ctx:'',examples:[]},
    {id:'c801',ro:'mai',tr:'önemsiz',en:'insignificant',tip:'',ctx:'',examples:[]},
    {id:'c802',ro:'mii',tr:'ünlü',en:'famous',tip:'',ctx:'',examples:[]},
    {id:'c803',ro:'jaam',tr:'hapşırmak',en:'sneeze',tip:'',ctx:'',examples:[]},
    {id:'c804',ro:'rnai',tr:'gündelik',en:'casual',tip:'',ctx:'',examples:[]},
    {id:'c805',ro:'gii-dtaa',tr:'gitar',en:'guitar',tip:'',ctx:'',examples:[]},
    {id:'c807',ro:'thorn',tr:'BT',en:'it',tip:'',ctx:'',examples:[]},
    {id:'c808',ro:'rnaaw-fan',tr:'dişçi',en:'dentist',tip:'',ctx:'',examples:[]},
    {id:'c809',ro:'fan',tr:'boşluk',en:'cavity',tip:'',ctx:'',examples:[]},
    {id:'c812',ro:'baawt-dfng-phaat',tr:'biniş kartı',en:'boarding pass',tip:'',ctx:'',examples:[]},
    {id:'c813',ro:'gaan',tr:'eğitim',en:'education',tip:'',ctx:'',examples:[]},
    {id:'c814',ro:'phaa-saa',tr:'İngilizce',en:'English',tip:'',ctx:'',examples:[]},
    {id:'c815',ro:'nf-dti-saat',tr:'kanun',en:'law',tip:'',ctx:'',examples:[]},
    {id:'c816',ro:'flut',tr:'flüt',en:'flute',tip:'',ctx:'',examples:[]},
    {id:'c817',ro:'pha-naaek',tr:'BT departmanı',en:'IT department',tip:'',ctx:'',examples:[]},
    {id:'c818',ro:'bpai',tr:'iş git gezisi',en:'business git trip',tip:'',ctx:'',examples:[]},
    {id:'c820',ro:'bpen',tr:'popüler',en:'popular',tip:'',ctx:'',examples:[]},
    {id:'c821',ro:'gaan',tr:'muhasebe',en:'accounting',tip:'',ctx:'',examples:[]},
    {id:'c822',ro:'ngaaen-baa-nat',tr:'bonus',en:'bonus',tip:'',ctx:'',examples:[]},
    {id:'c823',ro:'baa',tr:'ışık',en:'light',tip:'',ctx:'',examples:[]},
    {id:'c824',ro:'thrawm-baan',tr:'trombon',en:'trombone',tip:'',ctx:'',examples:[]},
    {id:'c825',ro:'khaa-aawk',tr:'kalkış',en:'departure',tip:'',ctx:'',examples:[]},
    {id:'c826',ro:'khaa-khao',tr:'varış',en:'arrival',tip:'',ctx:'',examples:[]},
    {id:'c827',ro:'wai-oo-lin',tr:'keman',en:'violin',tip:'',ctx:'',examples:[]},
    {id:'c828',ro:'wft-tha-yaa-saat',tr:'r. bilim',en:'rth science',tip:'',ctx:'',examples:[]},
    {id:'c829',ro:'wft-tha-yaa-saat',tr:'bilim',en:'science',tip:'',ctx:'',examples:[]},
    {id:'c830',ro:'bai-sang-yaa',tr:'reçete',en:'prescription',tip:'',ctx:'',examples:[]},
    {id:'c831',ro:'sam-phaa-ra',tr:'bagaj',en:'luggage',tip:'',ctx:'',examples:[]},
    {id:'c832',ro:'phaa-phan-phlaae',tr:'bandaj',en:'bandage',tip:'',ctx:'',examples:[]},
    {id:'c833',ro:'khon-khai',tr:'hasta',en:'patient',tip:'',ctx:'',examples:[]},
    {id:'c834',ro:'pha-naaek',tr:'departman',en:'department',tip:'',ctx:'',examples:[]},
    {id:'c835',ro:'k-ban-shii',tr:'muhasebeci',en:'ccountant',tip:'',ctx:'',examples:[]},
    {id:'c836',ro:'tha-naai-khwaam',tr:'avukat',en:'lawyer',tip:'',ctx:'',examples:[]},
    {id:'c837',ro:'khaa-raaeng',tr:'maaş',en:'wage',tip:'',ctx:'',examples:[]},
  ]
};

LESSONS[31] = L31;
