// Ders 23 verisi — CORE 2000 (229-300)
const L23 = {
  words:[
    {id:'c229',ro:'sip-hok',tr:'on altı',en:'sixteen',tip:'',ctx:'',examples:[]},
    {id:'c230',ro:'thoo-ra-sap',tr:'telefon',en:'telephone',tip:'',ctx:'',examples:[]},
    {id:'c231',ro:'dtaa',tr:'göz',en:'eye',tip:'',ctx:'',examples:[]},
    {id:'c232',ro:'fan',tr:'dişler',en:'teeth',tip:'',ctx:'',examples:[]},
    {id:'c234',ro:'ga-saan',tr:'fotokopi makinesi',en:'copy machine',tip:'',ctx:'',examples:[]},
    {id:'c236',ro:'nang-suue',tr:'kitap',en:'book',tip:'',ctx:'',examples:[]},
    {id:'c237',ro:'bpaak-gaa',tr:'dolma kalem',en:'pen',tip:'',ctx:'',examples:[]},
    {id:'c238',ro:'gaan',tr:'Postane',en:'post office',tip:'',ctx:'',examples:[]},
    {id:'c239',ro:'hawng-sa-mut',tr:'kütüphane',en:'library',tip:'',ctx:'',examples:[]},
    {id:'c240',ro:'sup-bpooe-maa-get',tr:'süpermarket',en:'supermarket',tip:'',ctx:'',examples:[]},
    {id:'c242',ro:'riian',tr:'saat',en:'arn',tip:'',ctx:'',examples:[]},
    {id:'c243',ro:'yaai',tr:'taşınmak',en:'move',tip:'',ctx:'',examples:[]},
    {id:'c244',ro:'sip-jet',tr:'on yedi',en:'seventeen',tip:'',ctx:'',examples:[]},
    {id:'c245',ro:'sip-bpaaet',tr:'on sekiz',en:'eighteen',tip:'',ctx:'',examples:[]},
    {id:'c246',ro:'sip-gaao',tr:'on dokuz',en:'nineteen',tip:'',ctx:'',examples:[]},
    {id:'c247',ro:'yfi-sip',tr:'yirmi',en:'twenty',tip:'',ctx:'',examples:[]},
    {id:'c248',ro:'khaaw',tr:'boyun',en:'neck',tip:'',ctx:'',examples:[]},
    {id:'c252',ro:'phuu-khao',tr:'dağ',en:'mountain',tip:'',ctx:'',examples:[]},
    {id:'c253',ro:'chaai-haat',tr:'sahil',en:'beach',tip:'',ctx:'',examples:[]},
    {id:'c255',ro:'gaw',tr:'ada',en:'island',tip:'',ctx:'',examples:[]},
    {id:'c257',ro:'faa',tr:'mavi',en:'blue',tip:'',ctx:'',examples:[]},
    {id:'c261',ro:'naa-buuea',tr:'sıkıcı',en:'boring',tip:'',ctx:'',examples:[]},
    {id:'c262',ro:'naa-dtuuen-dten',tr:'heyecan verici',en:'exciting',tip:'',ctx:'',examples:[]},
    {id:'c263',ro:'mii-khwaam-sam-khan',tr:'önemli',en:'portant',tip:'',ctx:'',examples:[]},
    {id:'c264',ro:'bat-khree-dit',tr:'kredi kartı',en:'credit card',tip:'',ctx:'',examples:[]},
    {id:'c265',ro:'gun-jaae',tr:'anahtar',en:'key',tip:'',ctx:'',examples:[]},
    {id:'c266',ro:'bai-khap-khii',tr:'Ehliyet',en:'driver\'s license',tip:'',ctx:'',examples:[]},
    {id:'c267',ro:'bpaa',tr:'orman',en:'forest',tip:'',ctx:'',examples:[]},
    {id:'c268',ro:'maae-nam',tr:'nehir',en:'river',tip:'',ctx:'',examples:[]},
    {id:'c272',ro:'khaawm-phf',tr:'bilgisayar',en:'computer',tip:'',ctx:'',examples:[]},
    {id:'c275',ro:'din-saaw-got',tr:'mekanik kurşun kalem',en:'mechanical pencil',tip:'',ctx:'',examples:[]},
    {id:'c276',ro:'mai-ban-that',tr:'cetvel',en:'ruler',tip:'',ctx:'',examples:[]},
    {id:'c277',ro:'bpaak-gaa',tr:'işaretleyici',en:'marker',tip:'',ctx:'',examples:[]},
    {id:'c278',ro:'tha-naa-khaan',tr:'banka',en:'bank',tip:'',ctx:'',examples:[]},
    {id:'c279',ro:'raan',tr:'market',en:'convenience store',tip:'',ctx:'',examples:[]},
    {id:'c280',ro:'roong-pha-yaa-baan',tr:'hastane',en:'hospital',tip:'',ctx:'',examples:[]},
    {id:'c281',ro:'gra-bpao-sa-dtaang',tr:'cüzdan',en:'wallet',tip:'',ctx:'',examples:[]},
    {id:'c283',ro:'sang',tr:'emir',en:'order',tip:'',ctx:'',examples:[]},
    {id:'c285',ro:'tha-lee-saai',tr:'çöl',en:'desert',tip:'',ctx:'',examples:[]},
    {id:'c286',ro:'huua',tr:'patron',en:'boss',tip:'',ctx:'',examples:[]},
    {id:'c287',ro:'sam-nak-ngaan',tr:'ofis',en:'office',tip:'',ctx:'',examples:[]},
    {id:'c289',ro:'gaan',tr:'toplantı',en:'meeting',tip:'',ctx:'',examples:[]},
    {id:'c290',ro:'sa-thaa-nii',tr:'polis karakolu',en:'police station',tip:'',ctx:'',examples:[]},
    {id:'c292',ro:'raan',tr:'fırıncılık',en:'bakery',tip:'',ctx:'',examples:[]},
    {id:'c293',ro:'roong-nang',tr:'sinema',en:'movie theater',tip:'',ctx:'',examples:[]},
    {id:'c294',ro:'gaan',tr:'müzakere',en:'negotiation',tip:'',ctx:'',examples:[]},
    {id:'c295',ro:'san-yaa',tr:'sözleşme',en:'contract',tip:'',ctx:'',examples:[]},
    {id:'c296',ro:'thu-ra-git',tr:'işletme',en:'business',tip:'',ctx:'',examples:[]},
    {id:'c299',ro:'jing',tr:'cidden',en:'serious',tip:'',ctx:'',examples:[]},
    {id:'c300',ro:'nuueai',tr:'yorgun',en:'tired',tip:'',ctx:'',examples:[]},
  ]
};

LESSONS[23] = L23;
