// Ders 40 verisi — CORE 2000 (1390-1451)
const L40 = {
  words:[
    {id:'c1390',ro:'yaa-gaae-wat',tr:'soğuk algınlığı ilacı',en:'cold medicine',tip:'',ctx:'',examples:[]},
    {id:'c1392',ro:'khaang',tr:'komidin',en:'nightstand',tip:'',ctx:'',examples:[]},
    {id:'c1393',ro:'gaa-faae',tr:'sehpa',en:'coffee table',tip:'',ctx:'',examples:[]},
    {id:'c1394',ro:'soo-faa',tr:'divan',en:'sofa',tip:'',ctx:'',examples:[]},
    {id:'c1395',ro:'gao-fi',tr:'sandalye',en:'chair',tip:'',ctx:'',examples:[]},
    {id:'c1396',ro:'rap-bpra-thaan',tr:'haan-yen yemek masası',en:'haan-yen dinner table',tip:'',ctx:'',examples:[]},
    {id:'c1398',ro:'hawng-kh',tr:'çalışmak',en:'study',tip:'',ctx:'',examples:[]},
    {id:'c1399',ro:'hawng-dtai-din',tr:'bodrum',en:'basement',tip:'',ctx:'',examples:[]},
    {id:'c1402',ro:'mai',tr:'mevcut olmayan',en:'absent',tip:'',ctx:'',examples:[]},
    {id:'c1403',ro:'bpaigap',tr:'eşlik etmek',en:'accompany',tip:'',ctx:'',examples:[]},
    {id:'c1404',ro:'khlaawng-khlaaeo',tr:'aktif',en:'active',tip:'',ctx:'',examples:[]},
    {id:'c1405',ro:'thfi-yuu',tr:'adres',en:'address',tip:'',ctx:'',examples:[]},
    {id:'c1406',ro:'phaa-phan-phlaae',tr:'yapışkanlı bandaj',en:'adhesive bandage',tip:'',ctx:'',examples:[]},
    {id:'c1407',ro:'kham-khun-na-sap',tr:'sıfat',en:'djective',tip:'',ctx:'',examples:[]},
    {id:'c1408',ro:'gluua',tr:'korkmuş',en:'afraid',tip:'',ctx:'',examples:[]},
    {id:'c1409',ro:'gam-not-gaan',tr:'gündem',en:'agenda',tip:'',ctx:'',examples:[]},
    {id:'c1410',ro:'bprai-sa-nii',tr:'uçak postası',en:'airmail',tip:'',ctx:'',examples:[]},
    {id:'c1411',ro:'dooen',tr:'koridor koltuğu',en:'aisle seat',tip:'',ctx:'',examples:[]},
    {id:'c1412',ro:'jaaw-ra-khee',tr:'timsah',en:'alligator',tip:'',ctx:'',examples:[]},
    {id:'c1413',ro:'dtuua',tr:'alfabe',en:'alphabet',tip:'',ctx:'',examples:[]},
    {id:'c1414',ro:'aae-nf-mee-chan',tr:'taklit',en:'imation',tip:'',ctx:'',examples:[]},
    {id:'c1416',ro:'wf-dtok',tr:'endişeli',en:'anxious',tip:'',ctx:'',examples:[]},
    {id:'c1417',ro:'muu-gaw',tr:'takımadalar',en:'archipelago',tip:'',ctx:'',examples:[]},
    {id:'c1418',ro:'ma-haa-sa-mut',tr:'Arktik Okyanusu',en:'Arctic Ocean',tip:'',ctx:'',examples:[]},
    {id:'c1419',ro:'aa-jeen-dti-naa',tr:'Arjantin',en:'Argentina',tip:'',ctx:'',examples:[]},
    {id:'c1420',ro:'jat',tr:'düzenlemek',en:'arrange',tip:'',ctx:'',examples:[]},
    {id:'c1421',ro:'maa',tr:'varış',en:'arri e',tip:'',ctx:'',examples:[]},
    {id:'c1422',ro:'thfi-khiia-bu-rii',tr:'kül tablası',en:'ashtray',tip:'',ctx:'',examples:[]},
    {id:'c1423',ro:'maawp-maai',tr:'atamak',en:'assign',tip:'',ctx:'',examples:[]},
    {id:'c1425',ro:'khao',tr:'yaai bir derse katıl',en:'yaai attend a lecture',tip:'',ctx:'',examples:[]},
    {id:'c1426',ro:'haawng-dtai-lang-khaa',tr:'çatı katı',en:'attic',tip:'',ctx:'',examples:[]},
    {id:'c1427',ro:'bpra-dtuu',tr:'arka kapı',en:'back door',tip:'',ctx:'',examples:[]},
    {id:'c1428',ro:'suuan-lang-baan',tr:'arka bahçe',en:'backyard',tip:'',ctx:'',examples:[]},
    {id:'c1429',ro:'baet-min-dtan',tr:'badminton',en:'badminton',tip:'',ctx:'',examples:[]},
    {id:'c1430',ro:'ra-biiang',tr:'balkon',en:'balcony',tip:'',ctx:'',examples:[]},
    {id:'c1432',ro:'grung-theep',tr:'Bangkok',en:'Bangkok',tip:'',ctx:'',examples:[]},
    {id:'c1433',ro:'khaang-khaao',tr:'yarasa',en:'bat',tip:'',ctx:'',examples:[]},
    {id:'c1434',ro:'baet-dtooe-rfi',tr:'pil',en:'battery',tip:'',ctx:'',examples:[]},
    {id:'c1435',ro:'saai',tr:'yedi',en:'ate',tip:'',ctx:'',examples:[]},
    {id:'c1439',ro:'phaa-hom',tr:'battaniye',en:'blanket',tip:'',ctx:'',examples:[]},
    {id:'c1440',ro:'baan',tr:'çiçek açmak',en:'bloom',tip:'',ctx:'',examples:[]},
    {id:'c1442',ro:'brpa-dtuu',tr:'biniş kapısı',en:'oarding gate',tip:'',ctx:'',examples:[]},
    {id:'c1443',ro:'thfi-bpooet-khuuat',tr:'şişe açacağı',en:'bottle opener',tip:'',ctx:'',examples:[]},
    {id:'c1444',ro:'ging',tr:'dal',en:'branch',tip:'',ctx:'',examples:[]},
    {id:'c1445',ro:'braa-siu',tr:'Brezilya',en:'Brazil',tip:'',ctx:'',examples:[]},
    {id:'c1446',ro:'sa-phaan',tr:'köprü',en:'bridge',tip:'',ctx:'',examples:[]},
    {id:'c1447',ro:'baawn',tr:'İngiliz Sterlini',en:'British Pound',tip:'',ctx:'',examples:[]},
    {id:'c1448',ro:'bpraaeng',tr:'dişlerini fırçalamak',en:'brush one\'s teeth',tip:'',ctx:'',examples:[]},
    {id:'c1450',ro:'khwaai',tr:'manda',en:'buffalo',tip:'',ctx:'',examples:[]},
    {id:'c1451',ro:'ma-laaeng',tr:'böcek',en:'bug',tip:'',ctx:'',examples:[]},
  ]
};

LESSONS[40] = L40;
