// Ders 45 verisi — CORE 2000 (1743-1819)
const L45 = {
  words:[
    {id:'c1743',ro:'aa-jaan',tr:'profesör',en:'professor',tip:'',ctx:'',examples:[]},
    {id:'c1745',ro:'phuum-jai',tr:'gurur duymak',en:'proud',tip:'',ctx:'',examples:[]},
    {id:'c1747',ro:'gaan-gak-gan',tr:'karantina',en:'quarantine',tip:'',ctx:'',examples:[]},
    {id:'c1748',ro:'kham-thaam',tr:'soru',en:'question',tip:'',ctx:'',examples:[]},
    {id:'c1749',ro:'gaan',tr:'sınav',en:'quiz',tip:'',ctx:'',examples:[]},
    {id:'c1750',ro:'raek-khuun',tr:'rakun',en:'raccoon',tip:'',ctx:'',examples:[]},
    {id:'c1751',ro:'bai-a-nu-yaat-glap',tr:'khao-muueang yeniden giriş izni',en:'khao-muueang re-entry permit',tip:'',ctx:'',examples:[]},
    {id:'c1752',ro:'aan',tr:'yüksek sesle oku',en:'read aloud',tip:'',ctx:'',examples:[]},
    {id:'c1756',ro:'tai-daaeng',tr:'kırmızı ışık',en:'red light',tip:'',ctx:'',examples:[]},
    {id:'c1757',ro:'ruu-suek',tr:'rahat',en:'relaxed',tip:'',ctx:'',examples:[]},
    {id:'c1760',ro:'chao',tr:'kira',en:'rent',tip:'',ctx:'',examples:[]},
    {id:'c1761',ro:'sam',tr:'tekrarlamak',en:'repeat',tip:'',ctx:'',examples:[]},
    {id:'c1762',ro:'jaawng',tr:'rezerv',en:'reserve',tip:'',ctx:'',examples:[]},
    {id:'c1763',ro:'raaet',tr:'gergedan',en:'rhinoceros',tip:'',ctx:'',examples:[]},
    {id:'c1764',ro:'nang',tr:'sürmek',en:'ride',tip:'',ctx:'',examples:[]},
    {id:'c1765',ro:'lfiao',tr:'dönüş',en:'ghtturn',tip:'',ctx:'',examples:[]},
    {id:'c1766',ro:'phleeng',tr:'rock müzik',en:'rock music',tip:'',ctx:'',examples:[]},
    {id:'c1767',ro:'gao-fi',tr:'sallanan sandalye',en:'rocking chair',tip:'',ctx:'',examples:[]},
    {id:'c1768',ro:'maaen-dtik',tr:'romantik komedi',en:'romantic comedy',tip:'',ctx:'',examples:[]},
    {id:'c1769',ro:'gai',tr:'horoz',en:'rooster',tip:'',ctx:'',examples:[]},
    {id:'c1770',ro:'raak',tr:'kök',en:'root',tip:'',ctx:'',examples:[]},
    {id:'c1771',ro:'wong-wiian',tr:'dolambaçlı',en:'roundabout',tip:'',ctx:'',examples:[]},
    {id:'c1773',ro:'phrom',tr:'kilim',en:'rug',tip:'',ctx:'',examples:[]},
    {id:'c1774',ro:'wfng',tr:'koşmak',en:'run',tip:'',ctx:'',examples:[]},
    {id:'c1775',ro:'rat-siia',tr:'Rusya',en:'Russia',tip:'',ctx:'',examples:[]},
    {id:'c1776',ro:'pha-nak-ngaan-khaai',tr:'satış elemanı',en:'salesperson',tip:'',ctx:'',examples:[]},
    {id:'c1778',ro:'ruu-suek',tr:'korkmuş',en:'scared',tip:'',ctx:'',examples:[]},
    {id:'c1779',ro:'wan-yut',tr:'roong-riian okul tatili',en:'roong-riian school holiday',tip:'',ctx:'',examples:[]},
    {id:'c1780',ro:'bpii-gaan-suek-saa',tr:'okul yılı',en:'school year',tip:'',ctx:'',examples:[]},
    {id:'c1781',ro:'dta-bpuu-khuuang',tr:'vida',en:'screw',tip:'',ctx:'',examples:[]},
    {id:'c1782',ro:'khai-khuuang',tr:'tornavida',en:'screwdriver',tip:'',ctx:'',examples:[]},
    {id:'c1783',ro:'bot',tr:'senaryo',en:'script',tip:'',ctx:'',examples:[]},
    {id:'c1785',ro:'chaai-tha-lee',tr:'deniz kenarı',en:'seaside',tip:'',ctx:'',examples:[]},
    {id:'c1786',ro:'khem-khat-nf-ra-phai',tr:'emniyet kemeri',en:'seat belt',tip:'',ctx:'',examples:[]},
    {id:'c1787',ro:'maai-leek',tr:'koltuk numarası',en:'seat number',tip:'',ctx:'',examples:[]},
    {id:'c1788',ro:'ma-let',tr:'tohum',en:'seed',tip:'',ctx:'',examples:[]},
    {id:'c1789',ro:'raawp',tr:'yarı final',en:'semi-final',tip:'',ctx:'',examples:[]},
    {id:'c1790',ro:'aa',tr:'yaşlı vatandaş',en:'senior citizen',tip:'',ctx:'',examples:[]},
    {id:'c1794',ro:'groat-ngaai',tr:'çabuk sinirlenen',en:'short-tempered',tip:'',ctx:'',examples:[]},
    {id:'c1796',ro:'thaang-thaaa',tr:'kaldırım',en:'sidewalk',tip:'',ctx:'',examples:[]},
    {id:'c1804',ro:'mii',tr:'kurnaz',en:'sly',tip:'',ctx:'',examples:[]},
    {id:'c1805',ro:'baeng-yauy',tr:'küçük fatura',en:'small bill',tip:'',ctx:'',examples:[]},
    {id:'c1807',ro:'hai',tr:'bekliyorum Seni tuttuğum için özür dilerim',en:'waiting Sorry to keep you',tip:'',ctx:'',examples:[]},
    {id:'c1809',ro:'ma-haa-sa-mut-dtai',tr:'Güney Okyanusu',en:'Southern Ocean',tip:'',ctx:'',examples:[]},
    {id:'c1810',ro:'sa-bpeen',tr:'İspanya',en:'Spain',tip:'',ctx:'',examples:[]},
    {id:'c1811',ro:'khwaam-reo',tr:'Hız Limiti',en:'speed limit',tip:'',ctx:'',examples:[]},
    {id:'c1812',ro:'maaeng-mum',tr:'örümcek',en:'spider',tip:'',ctx:'',examples:[]},
    {id:'c1815',ro:'gii-laa',tr:'spor',en:'sports',tip:'',ctx:'',examples:[]},
    {id:'c1818',ro:'sa-dtaem',tr:'damga vurmak',en:'stamp',tip:'',ctx:'',examples:[]},
    {id:'c1819',ro:'daa-raa',tr:'yıldız',en:'star',tip:'',ctx:'',examples:[]},
  ]
};

LESSONS[45] = L45;
