// Ders 34 verisi — CORE 2000 (958-1035)
const L34 = {
  words:[
    {id:'c958',ro:'gaan-wf-jai',tr:'araştırma',en:'research',tip:'',ctx:'',examples:[]},
    {id:'c959',ro:'kham-khaaw',tr:'rica etmek',en:'request',tip:'',ctx:'',examples:[]},
    {id:'c960',ro:'jee-ra-jaa',tr:'müzakere etmek',en:'negotiate',tip:'',ctx:'',examples:[]},
    {id:'c962',ro:'gaae-khai',tr:'tekrar düzeltme yapmak',en:'revise',tip:'',ctx:'',examples:[]},
    {id:'c964',ro:'roong-ngaan',tr:'fabrika',en:'factory',tip:'',ctx:'',examples:[]},
    {id:'c966',ro:'raaeng-ngaan',tr:'işgücü',en:'workforce',tip:'',ctx:'',examples:[]},
    {id:'c967',ro:'wat-sa-du',tr:'malzeme',en:'material',tip:'',ctx:'',examples:[]},
    {id:'c968',ro:'chfn',tr:'parça',en:'part',tip:'',ctx:'',examples:[]},
    {id:'c972',ro:'gaaet',tr:'gaz',en:'gas',tip:'',ctx:'',examples:[]},
    {id:'c973',ro:'phaa',tr:'tekstil',en:'textile',tip:'',ctx:'',examples:[]},
    {id:'c974',ro:'fai-faa',tr:'elektrik',en:'electricity',tip:'',ctx:'',examples:[]},
    {id:'c975',ro:'gaan',tr:'giriş',en:'input',tip:'',ctx:'',examples:[]},
    {id:'c976',ro:'gaan-jap-bplaa',tr:'balıkçılık',en:'fishing',tip:'',ctx:'',examples:[]},
    {id:'c978',ro:'song-aawk',tr:'ihracat',en:'export',tip:'',ctx:'',examples:[]},
    {id:'c979',ro:'nam-khao',tr:'içe aktarmak',en:'import',tip:'',ctx:'',examples:[]},
    {id:'c982',ro:'nam-man',tr:'benzin',en:'gasoline',tip:'',ctx:'',examples:[]},
    {id:'c983',ro:'phaa-phan-khaaw',tr:'atkı',en:'scarf',tip:'',ctx:'',examples:[]},
    {id:'c986',ro:'phaa',tr:'kumaş',en:'cloth',tip:'',ctx:'',examples:[]},
    {id:'c990',ro:'chut-waawm',tr:'eşofman',en:'sweat suit',tip:'',ctx:'',examples:[]},
    {id:'c993',ro:'gaang-geeng-yiin',tr:'kot',en:'jeans',tip:'',ctx:'',examples:[]},
    {id:'c995',ro:'gra-bpao',tr:'cep',en:'pocket',tip:'',ctx:'',examples:[]},
    {id:'c996',ro:'gra-dum',tr:'düğme',en:'button',tip:'',ctx:'',examples:[]},
    {id:'c1002',ro:'suuam',tr:'giymek',en:'put on',tip:'',ctx:'',examples:[]},
    {id:'c1003',ro:'dtat-gan',tr:'çarpışma',en:'clash',tip:'',ctx:'',examples:[]},
    {id:'c1004',ro:'sak-phaa',tr:'çamaşır yıkamak',en:'wash clothes',tip:'',ctx:'',examples:[]},
    {id:'c1006',ro:'sawm',tr:'onarmak',en:'mend',tip:'',ctx:'',examples:[]},
    {id:'c1007',ro:'thak',tr:'örgü',en:'knit',tip:'',ctx:'',examples:[]},
    {id:'c1008',ro:'yaawm',tr:'boya',en:'dye',tip:'',ctx:'',examples:[]},
    {id:'c1009',ro:'wat-dtuua',tr:'bir giysi sığdırmak',en:'fit a garment',tip:'',ctx:'',examples:[]},
    {id:'c1010',ro:'mai-khiit',tr:'kibrit',en:'match',tip:'',ctx:'',examples:[]},
    {id:'c1011',ro:'san',tr:'kısa',en:'short',tip:'',ctx:'',examples:[]},
    {id:'c1012',ro:'khaawp-jai',tr:'Teşekkürler',en:'Thanks',tip:'',ctx:'',examples:[]},
    {id:'c1013',ro:'sai',tr:'boyut',en:'size',tip:'',ctx:'',examples:[]},
    {id:'c1014',ro:'sa-dtai',tr:'stil',en:'style',tip:'',ctx:'',examples:[]},
    {id:'c1015',ro:'bpen',tr:'moda',en:'fashionable',tip:'',ctx:'',examples:[]},
    {id:'c1017',ro:'khap',tr:'sıkı',en:'tight',tip:'',ctx:'',examples:[]},
    {id:'c1018',ro:'rfiap-raauy',tr:'düzenli',en:'neat',tip:'',ctx:'',examples:[]},
    {id:'c1020',ro:'glaang',tr:'orta',en:'medium',tip:'',ctx:'',examples:[]},
    {id:'c1021',ro:'yai',tr:'büyük',en:'large',tip:'',ctx:'',examples:[]},
    {id:'c1022',ro:'yai',tr:'ekstra Büyük',en:'extra Large',tip:'',ctx:'',examples:[]},
    {id:'c1023',ro:'tham-muue',tr:'el yapımı',en:'handmade',tip:'',ctx:'',examples:[]},
    {id:'c1024',ro:'taai',tr:'pamuk',en:'cotton',tip:'',ctx:'',examples:[]},
    {id:'c1025',ro:'khan-sat',tr:'yün',en:'wool',tip:'',ctx:'',examples:[]},
    {id:'c1027',ro:'chut-yaao',tr:'elbise',en:'gown',tip:'',ctx:'',examples:[]},
    {id:'c1028',ro:'chut-thak-sf-doo',tr:'smokin',en:'tuxedo',tip:'',ctx:'',examples:[]},
    {id:'c1029',ro:'raawng-thaao-dtae',tr:'sandalet',en:'sandal',tip:'',ctx:'',examples:[]},
    {id:'c1030',ro:'raawng-thaao',tr:'bot',en:'boot',tip:'',ctx:'',examples:[]},
    {id:'c1031',ro:'raawng-thaao-suuam',tr:'dooen-nai-baan terliği',en:'dooen-nai-baan slipper',tip:'',ctx:'',examples:[]},
    {id:'c1033',ro:'sa-dtik',tr:'ruj',en:'lipstick',tip:'',ctx:'',examples:[]},
    {id:'c1035',ro:'thfi-bpat-gaaem',tr:'kızarmak',en:'blush',tip:'',ctx:'',examples:[]},
  ]
};

LESSONS[34] = L34;
