// Ders 22 verisi — CORE 2000 (147-228)
const L22 = {
  words:[
    {id:'c147',ro:'chut-chan-nai',tr:'iç çamaşırı',en:'underwear',tip:'',ctx:'',examples:[]},
    {id:'c148',ro:'khui',tr:'konuşmak',en:'talk',tip:'',ctx:'',examples:[]},
    {id:'c149',ro:'hai',tr:'vermek',en:'give',tip:'',ctx:'',examples:[]},
    {id:'c150',ro:'dtam',tr:'Düşük',en:'low',tip:'',ctx:'',examples:[]},
    {id:'c153',ro:'bplaa-muek-yak',tr:'ahtapot',en:'octopus',tip:'',ctx:'',examples:[]},
    {id:'c154',ro:'bplaa-cha-laam',tr:'köpek balığı',en:'shark',tip:'',ctx:'',examples:[]},
    {id:'c155',ro:'bplaa-waan',tr:'balina',en:'whale',tip:'',ctx:'',examples:[]},
    {id:'c156',ro:'mii',tr:'bulutlu',en:'cloudy',tip:'',ctx:'',examples:[]},
    {id:'c157',ro:'yen',tr:'Serin',en:'cool',tip:'',ctx:'',examples:[]},
    {id:'c158',ro:'dtaaeng-gwaa',tr:'hantallık',en:'cumber',tip:'',ctx:'',examples:[]},
    {id:'c159',ro:'phrfk-yak',tr:'dolmalık biber',en:'bell pepper',tip:'',ctx:'',examples:[]},
    {id:'c160',ro:'brawk-khoo-lfi',tr:'brokoli',en:'broccoli',tip:'',ctx:'',examples:[]},
    {id:'c161',ro:'gluuai',tr:'muz',en:'banana',tip:'',ctx:'',examples:[]},
    {id:'c163',ro:'a-ngun',tr:'üzüm',en:'grape',tip:'',ctx:'',examples:[]},
    {id:'c164',ro:'dtaaeng-moo',tr:'karpuz',en:'watermelon',tip:'',ctx:'',examples:[]},
    {id:'c166',ro:'nuu',tr:'fare',en:'mouse',tip:'',ctx:'',examples:[]},
    {id:'c167',ro:'phra-aa-thft',tr:'güneş',en:'sun',tip:'',ctx:'',examples:[]},
    {id:'c168',ro:'sa-phaap',tr:'hava durumu',en:'weather',tip:'',ctx:'',examples:[]},
    {id:'c169',ro:'ong-saa',tr:'derece',en:'degree',tip:'',ctx:'',examples:[]},
    {id:'c172',ro:'faaen',tr:'arkadaşım',en:'rlfriend',tip:'',ctx:'',examples:[]},
    {id:'c173',ro:'taaen',tr:'erkek arkadaş',en:'boyfriend',tip:'',ctx:'',examples:[]},
    {id:'c177',ro:'thaaek-sfi',tr:'taksi',en:'taxi',tip:'',ctx:'',examples:[]},
    {id:'c180',ro:'u-bat-dti-heet',tr:'kaza',en:'accident',tip:'',ctx:'',examples:[]},
    {id:'c181',ro:'su-nak',tr:'köpek',en:'dog',tip:'',ctx:'',examples:[]},
    {id:'c182',ro:'maaeo',tr:'kedi',en:'cat',tip:'',ctx:'',examples:[]},
    {id:'c187',ro:'sa-dtraaw-booe-rfi',tr:'çilek',en:'strawberry',tip:'',ctx:'',examples:[]},
    {id:'c188',ro:'chooe-rfi',tr:'kiraz',en:'cherry',tip:'',ctx:'',examples:[]},
    {id:'c189',ro:'dek',tr:'çocuk',en:'child',tip:'',ctx:'',examples:[]},
    {id:'c192',ro:'jak-gra-yaan',tr:'bisiklet',en:'bicycle',tip:'',ctx:'',examples:[]},
    {id:'c194',ro:'maaw-dtooe-sai',tr:'motosiklet',en:'motorcycle',tip:'',ctx:'',examples:[]},
    {id:'c196',ro:'ruuea',tr:'bot',en:'boat',tip:'',ctx:'',examples:[]},
    {id:'c197',ro:'maaeng-ga-phrun',tr:'denizanası',en:'jellyfish',tip:'',ctx:'',examples:[]},
    {id:'c199',ro:'bpuu',tr:'yengeç',en:'crab',tip:'',ctx:'',examples:[]},
    {id:'c200',ro:'dtaa',tr:'kaplumbağa ct',en:'turtle ct',tip:'',ctx:'',examples:[]},
    {id:'c202',ro:'dam',tr:'siyah',en:'black',tip:'',ctx:'',examples:[]},
    {id:'c205',ro:'phak-phaawn',tr:'dinlenmek',en:'rest',tip:'',ctx:'',examples:[]},
    {id:'c206',ro:'daai-yin',tr:'duymak',en:'hear',tip:'',ctx:'',examples:[]},
    {id:'c209',ro:'sip-et',tr:'on bir',en:'eleven',tip:'',ctx:'',examples:[]},
    {id:'c210',ro:'sip-saawng',tr:'on iki',en:'twelve',tip:'',ctx:'',examples:[]},
    {id:'c211',ro:'sip-saam',tr:'on üç',en:'thirteen',tip:'',ctx:'',examples:[]},
    {id:'c212',ro:'ii-meeo',tr:'e-posta',en:'e-mail',tip:'',ctx:'',examples:[]},
    {id:'c214',ro:'ak-saawn',tr:'xt mesajı',en:'xt message',tip:'',ctx:'',examples:[]},
    {id:'c216',ro:'gaaem',tr:'yanak',en:'cheek',tip:'',ctx:'',examples:[]},
    {id:'c217',ro:'ja-muuk',tr:'burun',en:'nose',tip:'',ctx:'',examples:[]},
    {id:'c218',ro:'sa-mut-ban-thuek',tr:'not defteri',en:'notebook',tip:'',ctx:'',examples:[]},
    {id:'c219',ro:'din-saaw',tr:'kalem',en:'pencil',tip:'',ctx:'',examples:[]},
    {id:'c224',ro:'jop',tr:'sona ermek',en:'finish',tip:'',ctx:'',examples:[]},
    {id:'c226',ro:'glaai-bpen',tr:'haline gelmek',en:'become',tip:'',ctx:'',examples:[]},
    {id:'c227',ro:'sip-sii',tr:'on dört',en:'fourteen',tip:'',ctx:'',examples:[]},
    {id:'c228',ro:'sip-haa',tr:'on beş',en:'fteen',tip:'',ctx:'',examples:[]},
  ]
};

LESSONS[22] = L22;
