// Ders 37 verisi — CORE 2000 (1168-1244)
const L37 = {
  words:[
    {id:'c1168',ro:'taa-sai',tr:'açık gökyüzü',en:'clear sky',tip:'',ctx:'',examples:[]},
    {id:'c1171',ro:'khwaam-chuuen',tr:'nem',en:'humidity',tip:'',ctx:'',examples:[]},
    {id:'c1174',ro:'mii',tr:'buzlanmak',en:'ice over',tip:'',ctx:'',examples:[]},
    {id:'c1176',ro:'op-aao',tr:'bunaltıcı',en:'muggy',tip:'',ctx:'',examples:[]},
    {id:'c1177',ro:'dtam-gwaa',tr:'Khaeng donma noktasının altında',en:'khaeng below freezing',tip:'',ctx:'',examples:[]},
    {id:'c1178',ro:'khwaam-naao',tr:'Rüzgar soğukluğu',en:'wind chill',tip:'',ctx:'',examples:[]},
    {id:'c1179',ro:'dtam',tr:'sıfırın altında',en:'below zero',tip:'',ctx:'',examples:[]},
    {id:'c1180',ro:'sot-sai',tr:'temizlemek',en:'clear up',tip:'',ctx:'',examples:[]},
    {id:'c1181',ro:'khwaam-raawn',tr:'aşırı sıcaklık',en:'extreme heat',tip:'',ctx:'',examples:[]},
    {id:'c1182',ro:'nam-khaang-khaeng',tr:'don',en:'frost',tip:'',ctx:'',examples:[]},
    {id:'c1183',ro:'maak',tr:'bulutlu olmak',en:'become cloudy',tip:'',ctx:'',examples:[]},
    {id:'c1184',ro:'sai-khloon',tr:'siklon',en:'cyclone',tip:'',ctx:'',examples:[]},
    {id:'c1185',ro:'gaan',tr:'çizim',en:'drawing',tip:'',ctx:'',examples:[]},
    {id:'c1188',ro:'nak-sa-daaeng-chaai',tr:'aktör',en:'actor',tip:'',ctx:'',examples:[]},
    {id:'c1193',ro:'phleeng-bpawp',tr:'pop müzik',en:'pop music',tip:'',ctx:'',examples:[]},
    {id:'c1195',ro:'jaaet',tr:'caz',en:'jazz',tip:'',ctx:'',examples:[]},
    {id:'c1196',ro:'phleeng-khlaat-sik',tr:'klasik müzik',en:'classical music',tip:'',ctx:'',examples:[]},
    {id:'c1197',ro:'phleeng-raep',tr:'rap müzik',en:'rap music',tip:'',ctx:'',examples:[]},
    {id:'c1198',ro:'wong-don-dtrii',tr:'bant',en:'band',tip:'',ctx:'',examples:[]},
    {id:'c1199',ro:'huu-fang',tr:'kulaklık',en:'earphones',tip:'',ctx:'',examples:[]},
    {id:'c1203',ro:'nam',tr:'susuz',en:'thirsty',tip:'',ctx:'',examples:[]},
    {id:'c1205',ro:'gluuea',tr:'tuz',en:'salt',tip:'',ctx:'',examples:[]},
    {id:'c1206',ro:'nam-dtaan',tr:'şeker',en:'sugar',tip:'',ctx:'',examples:[]},
    {id:'c1208',ro:'nooei',tr:'tereyağı',en:'butter',tip:'',ctx:'',examples:[]},
    {id:'c1209',ro:'saawt-phrfk',tr:'acı sos',en:'hot sauce',tip:'',ctx:'',examples:[]},
    {id:'c1210',ro:'saawt-ma-khuuea-theet',tr:'ketçap',en:'ketchup',tip:'',ctx:'',examples:[]},
    {id:'c1211',ro:'mat',tr:'hardal',en:'mustard',tip:'',ctx:'',examples:[]},
    {id:'c1212',ro:'saawt',tr:'Tabasco sosu',en:'Tabasco sauce',tip:'',ctx:'',examples:[]},
    {id:'c1213',ro:'phrfk-thai',tr:'biber',en:'pepper',tip:'',ctx:'',examples:[]},
    {id:'c1214',ro:'aa-haan',tr:'deniz ürünleri',en:'seafood',tip:'',ctx:'',examples:[]},
    {id:'c1216',ro:'sooep',tr:'sert',en:'serve',tip:'',ctx:'',examples:[]},
    {id:'c1218',ro:'sap',tr:'kesmek',en:'chop',tip:'',ctx:'',examples:[]},
    {id:'c1219',ro:'bot',tr:'kıyma',en:'mince',tip:'',ctx:'',examples:[]},
    {id:'c1221',ro:'yaang',tr:'ızgara',en:'grill',tip:'',ctx:'',examples:[]},
    {id:'c1223',ro:'thaawt',tr:'yağda kızartmak',en:'fry',tip:'',ctx:'',examples:[]},
    {id:'c1224',ro:'yaang',tr:'haşlamak',en:'roast',tip:'',ctx:'',examples:[]},
    {id:'c1225',ro:'han',tr:'kesmek',en:'cut',tip:'',ctx:'',examples:[]},
    {id:'c1226',ro:'phat',tr:'sote',en:'saute',tip:'',ctx:'',examples:[]},
    {id:'c1230',ro:'hai',tr:'mai-khroo-weep mikrodalga fırın',en:'mai-khroo-weep microwave',tip:'',ctx:'',examples:[]},
    {id:'c1231',ro:'baa-bii-khiu',tr:'barbekü',en:'barbecue',tip:'',ctx:'',examples:[]},
    {id:'c1232',ro:'wit-gfi',tr:'viski',en:'whiskey',tip:'',ctx:'',examples:[]},
    {id:'c1233',ro:'nam',tr:'kaynar su',en:'boiling water',tip:'',ctx:'',examples:[]},
    {id:'c1234',ro:'nam',tr:'meyve suyu',en:'fruit juice',tip:'',ctx:'',examples:[]},
    {id:'c1235',ro:'chaa-dam',tr:'siyah çay',en:'black tea',tip:'',ctx:'',examples:[]},
    {id:'c1237',ro:'gaa-faae',tr:'kafe latte',en:'caffe latte',tip:'',ctx:'',examples:[]},
    {id:'c1239',ro:'up-bpa-gaawn',tr:'rap-bpra-thaan kap yemek aa-haan',en:'eating rap-bpra-thaan utensil aa-haan',tip:'',ctx:'',examples:[]},
    {id:'c1240',ro:'mfit',tr:'biftek bıçağı',en:'steak knife',tip:'',ctx:'',examples:[]},
    {id:'c1241',ro:'mfit',tr:'oyma bıçağı',en:'carving knife',tip:'',ctx:'',examples:[]},
    {id:'c1242',ro:'khem',tr:'tuzlu',en:'salty',tip:'',ctx:'',examples:[]},
    {id:'c1244',ro:'waan',tr:'tatlı',en:'sweet',tip:'',ctx:'',examples:[]},
  ]
};

LESSONS[37] = L37;
