// Ders 28 verisi — CORE 2000 (578-643)
const L28 = {
  words:[
    {id:'c578',ro:'saawng-raauy',tr:'iki yüz',en:'two hundred',tip:'',ctx:'',examples:[]},
    {id:'c579',ro:'saam-raauy',tr:'yüz',en:'hundred',tip:'',ctx:'',examples:[]},
    {id:'c580',ro:'hok-raauy',tr:'altı yüz',en:'six hundred',tip:'',ctx:'',examples:[]},
    {id:'c581',ro:'nam',tr:'Çıkarmak',en:'take out',tip:'',ctx:'',examples:[]},
    {id:'c582',ro:'pha-nak-ngaan-sooep',tr:'garson',en:'waiter',tip:'',ctx:'',examples:[]},
    {id:'c583',ro:'aa-gaat',tr:'hava durumu raporu',en:'weather report',tip:'',ctx:'',examples:[]},
    {id:'c584',ro:'seeo-sfiat',tr:'santigrat',en:'Celsius',tip:'',ctx:'',examples:[]},
    {id:'c585',ro:'raai-gaan',tr:'TV şovu',en:'TV show',tip:'',ctx:'',examples:[]},
    {id:'c587',ro:'aa-haan',tr:'Fast food',en:'fast food',tip:'',ctx:'',examples:[]},
    {id:'c590',ro:'bpaai',tr:'imza',en:'sign',tip:'',ctx:'',examples:[]},
    {id:'c592',ro:'sa-thaa-nii',tr:'tren istasyonu',en:'train station',tip:'',ctx:'',examples:[]},
    {id:'c593',ro:'haa-raauy',tr:'yüz',en:'ehundred',tip:'',ctx:'',examples:[]},
    {id:'c594',ro:'gao-raauy-gao-sip-gao',tr:'dokuz yüz doksan dokuz',en:'nine hundred ninety nine',tip:'',ctx:'',examples:[]},
    {id:'c595',ro:'nueng-raauy-et',tr:'yüz bir',en:'one hundred and one',tip:'',ctx:'',examples:[]},
    {id:'c596',ro:'sii-raauy',tr:'dört yüz',en:'four hundred',tip:'',ctx:'',examples:[]},
    {id:'c597',ro:'gao-raauy',tr:'dokuz yüz',en:'nine hundred',tip:'',ctx:'',examples:[]},
    {id:'c598',ro:'niu',tr:'inç',en:'inch',tip:'',ctx:'',examples:[]},
    {id:'c600',ro:'sen-dti-meet',tr:'santimetre',en:'centimeter',tip:'',ctx:'',examples:[]},
    {id:'c601',ro:'raan-aa-haan',tr:'restoran',en:'restaurant',tip:'',ctx:'',examples:[]},
    {id:'c602',ro:'khaa-fee',tr:'kafe',en:'cafe',tip:'',ctx:'',examples:[]},
    {id:'c603',ro:'raan',tr:'kahvehane',en:'coffee shop',tip:'',ctx:'',examples:[]},
    {id:'c604',ro:'baa',tr:'çubuk',en:'bar',tip:'',ctx:'',examples:[]},
    {id:'c606',ro:'sa-naam-yaa',tr:'çimen',en:'grass',tip:'',ctx:'',examples:[]},
    {id:'c608',ro:'din',tr:'kir',en:'dirt',tip:'',ctx:'',examples:[]},
    {id:'c611',ro:'tat-thf-dtao',tr:'Taoizm',en:'Taoism',tip:'',ctx:'',examples:[]},
    {id:'c612',ro:'kham-phii',tr:'İncil',en:'Bible',tip:'',ctx:'',examples:[]},
    {id:'c613',ro:'kham-phii',tr:'Kuran',en:'Quran',tip:'',ctx:'',examples:[]},
    {id:'c616',ro:'nueng-phan',tr:'bin',en:'one thousand',tip:'',ctx:'',examples:[]},
    {id:'c617',ro:'saawng-phan',tr:'iki bin',en:'two thousand',tip:'',ctx:'',examples:[]},
    {id:'c618',ro:'bpaaet-phan',tr:'sekiz bin',en:'eight thousand',tip:'',ctx:'',examples:[]},
    {id:'c619',ro:'nueng-muuen',tr:'on bin',en:'ten thousand',tip:'',ctx:'',examples:[]},
    {id:'c620',ro:'sii-phan',tr:'dört bin',en:'four thousand',tip:'',ctx:'',examples:[]},
    {id:'c622',ro:'haaw-phak',tr:'yatakhane',en:'dormitory',tip:'',ctx:'',examples:[]},
    {id:'c623',ro:'dtuek',tr:'apartman binası',en:'apartment building',tip:'',ctx:'',examples:[]},
    {id:'c625',ro:'faam',tr:'çiftlik',en:'farm',tip:'',ctx:'',examples:[]},
    {id:'c626',ro:'sue-naa-mf',tr:'tsunami',en:'tsunami',tip:'',ctx:'',examples:[]},
    {id:'c627',ro:'hi-ma',tr:'çığ',en:'avalanche',tip:'',ctx:'',examples:[]},
    {id:'c629',ro:'phaen-din-wai',tr:'deprem',en:'earthquake',tip:'',ctx:'',examples:[]},
    {id:'c630',ro:'phaa-yu-saai',tr:'kum fırtınası',en:'sandstorm',tip:'',ctx:'',examples:[]},
    {id:'c632',ro:'ram',tr:'şemsiye',en:'umbrella',tip:'',ctx:'',examples:[]},
    {id:'c633',ro:'muuak',tr:'şapka',en:'hat',tip:'',ctx:'',examples:[]},
    {id:'c634',ro:'khaaen-yaao',tr:'uzun kollu',en:'long-sleeved',tip:'',ctx:'',examples:[]},
    {id:'c635',ro:'khaaen-san',tr:'kısa kollu',en:'short-sleeved',tip:'',ctx:'',examples:[]},
    {id:'c636',ro:'jep-bpuuat',tr:'acı verici',en:'painful',tip:'',ctx:'',examples:[]},
    {id:'c637',ro:'khfi-aai',tr:'utangaç',en:'shy',tip:'',ctx:'',examples:[]},
    {id:'c638',ro:'bpra-maa',tr:'gergin',en:'nervous',tip:'',ctx:'',examples:[]},
    {id:'c639',ro:'dtuuen-dten',tr:'heyecanlı',en:'excited',tip:'',ctx:'',examples:[]},
    {id:'c640',ro:'ruu-suek',tr:'utanmış',en:'embarrassed',tip:'',ctx:'',examples:[]},
    {id:'c641',ro:'chon-na-bot',tr:'ülke',en:'country',tip:'',ctx:'',examples:[]},
    {id:'c643',ro:'muueang',tr:'şehir',en:'town',tip:'',ctx:'',examples:[]},
  ]
};

LESSONS[28] = L28;
