// Ders 35 verisi — CORE 2000 (1036-1105)
const L35 = {
  words:[
    {id:'c1036',ro:'yaa-thaa-lep',tr:'oje',en:'nail polish',tip:'',ctx:'',examples:[]},
    {id:'c1038',ro:'chut-naawn',tr:'gecelik',en:'nightgown',tip:'',ctx:'',examples:[]},
    {id:'c1039',ro:'gaang-geeng-nai',tr:'külot',en:'panties',tip:'',ctx:'',examples:[]},
    {id:'c1040',ro:'chut-waai-nam',tr:'takım elbise',en:'imsuit',tip:'',ctx:'',examples:[]},
    {id:'c1042',ro:'gra-bproong-san',tr:'mini etek',en:'mini-skirt',tip:'',ctx:'',examples:[]},
    {id:'c1043',ro:'wan',tr:'gün',en:'day',tip:'',ctx:'',examples:[]},
    {id:'c1044',ro:'duuean',tr:'ay',en:'month',tip:'',ctx:'',examples:[]},
    {id:'c1045',ro:'wan-yut',tr:'tatil',en:'holiday',tip:'',ctx:'',examples:[]},
    {id:'c1046',ro:'wan-ma-ruuen',tr:'yarından sonraki gün',en:'day after tomorrow',tip:'',ctx:'',examples:[]},
    {id:'c1048',ro:'thfiang-khuuen',tr:'Thfiang-wan AM',en:'thfiang-wan AM',tip:'',ctx:'',examples:[]},
    {id:'c1049',ro:'thfiang',tr:'öğlen',en:'noon',tip:'',ctx:'',examples:[]},
    {id:'c1050',ro:'thfiang-khuuen',tr:'gece yarısı',en:'midnight',tip:'',ctx:'',examples:[]},
    {id:'c1051',ro:'iik',tr:'çeyrek kala',en:'quarter to',tip:'',ctx:'',examples:[]},
    {id:'c1053',ro:'dtang-dtaae',tr:'Thfiang-khuuen Başbakanı',en:'thfiang-khuuen PM',tip:'',ctx:'',examples:[]},
    {id:'c1054',ro:'sip-haa-naa-thii',tr:'çeyrek sonra',en:'quarter after',tip:'',ctx:'',examples:[]},
    {id:'c1056',ro:'gluua',tr:'korku',en:'fear',tip:'',ctx:'',examples:[]},
    {id:'c1057',ro:'khlaai',tr:'benzemek',en:'resemble',tip:'',ctx:'',examples:[]},
    {id:'c1059',ro:'khaawp-khun',tr:'teşekkür etmek',en:'thank',tip:'',ctx:'',examples:[]},
    {id:'c1060',ro:'rak',tr:'Aşk',en:'love',tip:'',ctx:'',examples:[]},
    {id:'c1062',ro:'aan',tr:'Okumak',en:'read',tip:'',ctx:'',examples:[]},
    {id:'c1063',ro:'yuuen',tr:'durmak',en:'stand',tip:'',ctx:'',examples:[]},
    {id:'c1064',ro:'phtaat',tr:'kayıp',en:'miss',tip:'',ctx:'',examples:[]},
    {id:'c1065',ro:'khao',tr:'girmek',en:'enter',tip:'',ctx:'',examples:[]},
    {id:'c1067',ro:'gii-moong',tr:'saat kaç',en:'What time is',tip:'',ctx:'',examples:[]},
    {id:'c1070',ro:'chan',tr:'Beğendim',en:'I like it',tip:'',ctx:'',examples:[]},
    {id:'c1071',ro:'chan',tr:'hoşuma gitmedi',en:'I don\'t like it',tip:'',ctx:'',examples:[]},
    {id:'c1074',ro:'mai',tr:'Merak etme',en:'Don\'t worry',tip:'',ctx:'',examples:[]},
    {id:'c1075',ro:'mai',tr:'ah sorun',en:'o problem',tip:'',ctx:'',examples:[]},
    {id:'c1076',ro:'mai',tr:'Sorun değil',en:'It\'s okay',tip:'',ctx:'',examples:[]},
    {id:'c1078',ro:'ga-ru-naa',tr:'Lütfen',en:'Please',tip:'',ctx:'',examples:[]},
    {id:'c1079',ro:'chan',tr:'beni Affet lütfen',en:'Please forgive me',tip:'',ctx:'',examples:[]},
    {id:'c1080',ro:'chan',tr:'Ben isterim',en:'I\'d like',tip:'',ctx:'',examples:[]},
    {id:'c1081',ro:'jing',tr:'Doğru',en:'True',tip:'',ctx:'',examples:[]},
    {id:'c1082',ro:'mai',tr:'lse',en:'lse',tip:'',ctx:'',examples:[]},
    {id:'c1083',ro:'riian',tr:'çalışmak',en:'study',tip:'',ctx:'',examples:[]},
    {id:'c1084',ro:'tham',tr:'aşçı',en:'cook',tip:'',ctx:'',examples:[]},
    {id:'c1085',ro:'gaan',tr:'banyo',en:'bath',tip:'',ctx:'',examples:[]},
    {id:'c1088',ro:'nueng',tr:'bir yüz bin',en:'one I hundred thousand',tip:'',ctx:'',examples:[]},
    {id:'c1090',ro:'nueng',tr:'yüz milyar',en:'one hundred billion',tip:'',ctx:'',examples:[]},
    {id:'c1093',ro:'nueng',tr:'yüz trilyon',en:'one hundred trillion',tip:'',ctx:'',examples:[]},
    {id:'c1095',ro:'ruk',tr:'damalı',en:'checkered',tip:'',ctx:'',examples:[]},
    {id:'c1097',ro:'laai-thaang',tr:'ince çizgili',en:'pin-striped',tip:'',ctx:'',examples:[]},
    {id:'c1098',ro:'jut',tr:'nokta',en:'dot',tip:'',ctx:'',examples:[]},
    {id:'c1099',ro:'luuan',tr:'sağlam',en:'solid',tip:'',ctx:'',examples:[]},
    {id:'c1100',ro:'laai-khwaang',tr:'çizgili',en:'striped',tip:'',ctx:'',examples:[]},
    {id:'c1101',ro:'laai-sa-gawt',tr:'ekose',en:'plaid',tip:'',ctx:'',examples:[]},
    {id:'c1102',ro:'thfi',tr:'dalgalı',en:'wavy',tip:'',ctx:'',examples:[]},
    {id:'c1103',ro:'bat',tr:'yetkilendirme',en:'entification',tip:'',ctx:'',examples:[]},
    {id:'c1104',ro:'tham-mai',tr:'Neden',en:'why',tip:'',ctx:'',examples:[]},
    {id:'c1105',ro:'yaang-rai',tr:'Nasıl',en:'how',tip:'',ctx:'',examples:[]},
  ]
};

LESSONS[35] = L35;
