// Ders 41 verisi — CORE 2000 (1452-1536)
const L41 = {
  words:[
    {id:'c1452',ro:'dtuek',tr:'bina',en:'building',tip:'',ctx:'',examples:[]},
    {id:'c1455',ro:'nak-thu-ra-git',tr:'işadamı',en:'businessman',tip:'',ctx:'',examples:[]},
    {id:'c1456',ro:'haawng-dooi-saan',tr:'bin b\'W',en:'bin b\'W',tip:'',ctx:'',examples:[]},
    {id:'c1458',ro:'thoo-ra-sap-phit',tr:'yanlış numarayı aramak',en:'call a wrong number',tip:'',ctx:'',examples:[]},
    {id:'c1459',ro:'gaan',tr:'kaligrafi',en:'calligraphy',tip:'',ctx:'',examples:[]},
    {id:'c1460',ro:'thfi',tr:'konserve açacağı',en:'can opener',tip:'',ctx:'',examples:[]},
    {id:'c1461',ro:'khaae-naa-daa',tr:'Kanada',en:'Canada',tip:'',ctx:'',examples:[]},
    {id:'c1463',ro:'thiian',tr:'ndle',en:'ndle',tip:'',ctx:'',examples:[]},
    {id:'c1464',ro:'phrom',tr:'halı',en:'carpet',tip:'',ctx:'',examples:[]},
    {id:'c1465',ro:'gaa-dtuun',tr:'karikatür',en:'cartoon',tip:'',ctx:'',examples:[]},
    {id:'c1468',ro:'phee-daan',tr:'tavan',en:'ceiling',tip:'',ctx:'',examples:[]},
    {id:'c1469',ro:'phf-thii',tr:'tören',en:'ceremony',tip:'',ctx:'',examples:[]},
    {id:'c1470',ro:'jot-maai',tr:'taahhütlü posta',en:'certified mail',tip:'',ctx:'',examples:[]},
    {id:'c1471',ro:'chaawk',tr:'tebeşir',en:'chalk',tip:'',ctx:'',examples:[]},
    {id:'c1473',ro:'gaan-khaeng-khan',tr:'şampiyonluk yarışması',en:'championship contest',tip:'',ctx:'',examples:[]},
    {id:'c1481',ro:'chan-riian',tr:'sınıf',en:'class',tip:'',ctx:'',examples:[]},
    {id:'c1483',ro:'pha-nak-ngaan',tr:'katip',en:'clerk',tip:'',ctx:'',examples:[]},
    {id:'c1487',ro:'sa-dtaem',tr:'pulları topla',en:'collect stamps',tip:'',ctx:'',examples:[]},
    {id:'c1489',ro:'rf-sat',tr:'şirket çalışanı',en:'company worker',tip:'',ctx:'',examples:[]},
    {id:'c1490',ro:'gaan-khaeng-khan',tr:'yarışma',en:'competition',tip:'',ctx:'',examples:[]},
    {id:'c1492',ro:'yuuen-yan',tr:'onaylamak',en:'confirm',tip:'',ctx:'',examples:[]},
    {id:'c1493',ro:'yuet',tr:'el koymak',en:'confiscate',tip:'',ctx:'',examples:[]},
    {id:'c1496',ro:'khaawng',tr:'kaçak',en:'contraband',tip:'',ctx:'',examples:[]},
    {id:'c1497',ro:'bplaaeng',tr:'dönüştürmek',en:'convert',tip:'',ctx:'',examples:[]},
    {id:'c1499',ro:'thuuk-dtawng',tr:'doğru',en:'correct',tip:'',ctx:'',examples:[]},
    {id:'c1501',ro:'jfn',tr:'kriket',en:'cricket',tip:'',ctx:'',examples:[]},
    {id:'c1502',ro:'jaaw-ra-khee',tr:'timsah',en:'crocodile',tip:'',ctx:'',examples:[]},
    {id:'c1503',ro:'phuu-khon',tr:'kalabalık',en:'crowded',tip:'',ctx:'',examples:[]},
    {id:'c1506',ro:'gaan-laaek-bpliian',tr:'Theet döviz bozdurma',en:'theet currency exchange',tip:'',ctx:'',examples:[]},
    {id:'c1507',ro:'phaa-maan',tr:'perde',en:'curtain',tip:'',ctx:'',examples:[]},
    {id:'c1508',ro:'sun-la-gaa-gaawn',tr:'gümrük',en:'customs',tip:'',ctx:'',examples:[]},
    {id:'c1509',ro:'dten',tr:'dans',en:'dance',tip:'',ctx:'',examples:[]},
    {id:'c1511',ro:'bai-sam-daaeng-sam',tr:'beyan formu',en:'declaration form',tip:'',ctx:'',examples:[]},
    {id:'c1512',ro:'sam-daaeng',tr:'ilan etmek',en:'declare',tip:'',ctx:'',examples:[]},
    {id:'c1513',ro:'gwaang',tr:'geyik',en:'deer',tip:'',ctx:'',examples:[]},
    {id:'c1514',ro:'thaai',tr:'arınmak',en:'defecate',tip:'',ctx:'',examples:[]},
    {id:'c1515',ro:'ong-saa',tr:'derece',en:'degree',tip:'',ctx:'',examples:[]},
    {id:'c1516',ro:'chaa',tr:'gecikmiş',en:'delayed',tip:'',ctx:'',examples:[]},
    {id:'c1518',ro:'gaan',tr:'dikte',en:'dictation',tip:'',ctx:'',examples:[]},
    {id:'c1520',ro:'thft-thaang',tr:'yol tarifi',en:'directions',tip:'',ctx:'',examples:[]},
    {id:'c1522',ro:'mai',tr:'hoşlanmamak',en:'dislike',tip:'',ctx:'',examples:[]},
    {id:'c1523',ro:'kha-dii',tr:'belgesel',en:'documentary',tip:'',ctx:'',examples:[]},
    {id:'c1524',ro:'thaang-khao-aawk',tr:'kapı aralığı',en:'doorway',tip:'',ctx:'',examples:[]},
    {id:'c1528',ro:'duu-bai',tr:'Dubai',en:'Dubai',tip:'',ctx:'',examples:[]},
    {id:'c1529',ro:'thang',tr:'çöp konteynırı',en:'dumpster',tip:'',ctx:'',examples:[]},
    {id:'c1532',ro:'seet-tha-git',tr:'ekonomi',en:'economy',tip:'',ctx:'',examples:[]},
    {id:'c1533',ro:'ii-yip',tr:'Mısır',en:'Egypt',tip:'',ctx:'',examples:[]},
    {id:'c1534',ro:'cha-raa',tr:'yaşlı',en:'elderly',tip:'',ctx:'',examples:[]},
    {id:'c1535',ro:'bplak-fai',tr:'elektrik fişi',en:'electric plug',tip:'',ctx:'',examples:[]},
    {id:'c1536',ro:'faa',tr:'elektrikli pirinç pişirici',en:'electric rice cooker',tip:'',ctx:'',examples:[]},
  ]
};

LESSONS[41] = L41;
