// Ders 44 verisi — CORE 2000 (1665-1742)
const L44 = {
  words:[
    {id:'c1665',ro:'bu-rut-bprai-sa-nii',tr:'postacı',en:'mailman',tip:'',ctx:'',examples:[]},
    {id:'c1666',ro:'phaen-din-yai',tr:'boş arazi',en:'fainland',tip:'',ctx:'',examples:[]},
    {id:'c1667',ro:'dtaeng',tr:'yapmak',en:'make a',tip:'',ctx:'',examples:[]},
    {id:'c1668',ro:'baai',tr:'Kendini evinde gibi hisset',en:'Make yourself at home',tip:'',ctx:'',examples:[]},
    {id:'c1670',ro:'maa-raa-thaawn',tr:'maraton',en:'marathon',tip:'',ctx:'',examples:[]},
    {id:'c1671',ro:'bueng',tr:'bataklık',en:'marsh',tip:'',ctx:'',examples:[]},
    {id:'c1672',ro:'suuea',tr:'mat',en:'mat',tip:'',ctx:'',examples:[]},
    {id:'c1676',ro:'mek-sf-goo',tr:'Meksika',en:'Mexico',tip:'',ctx:'',examples:[]},
    {id:'c1677',ro:'mek-sf-goo',tr:'Meksika Şehri',en:'Mexico City',tip:'',ctx:'',examples:[]},
    {id:'c1679',ro:'ling',tr:'maymun',en:'monkey',tip:'',ctx:'',examples:[]},
    {id:'c1682',ro:'mat-sa-yft',tr:'cami',en:'mosque',tip:'',ctx:'',examples:[]},
    {id:'c1683',ro:'aa-gaan',tr:'hareket hastalığı',en:'motion sickness',tip:'',ctx:'',examples:[]},
    {id:'c1686',ro:'naai',tr:'Bay',en:'Mr',tip:'',ctx:'',examples:[]},
    {id:'c1687',ro:'naang',tr:'Bayan',en:'Mrs',tip:'',ctx:'',examples:[]},
    {id:'c1688',ro:'chan',tr:'Fynameis',en:'fynameis',tip:'',ctx:'',examples:[]},
    {id:'c1690',ro:'san-chaat',tr:'milliyet',en:'nationality',tip:'',ctx:'',examples:[]},
    {id:'c1692',ro:'mai-khooei',tr:'Asla',en:'never',tip:'',ctx:'',examples:[]},
    {id:'c1693',ro:'raaek-gooet',tr:'yeni doğmuş bebek',en:'newborn baby',tip:'',ctx:'',examples:[]},
    {id:'c1694',ro:'nfu',tr:'semender',en:'newt',tip:'',ctx:'',examples:[]},
    {id:'c1696',ro:'kham',tr:'isim',en:'noun',tip:'',ctx:'',examples:[]},
    {id:'c1698',ro:'fft',tr:'ofis çalışanı',en:'office worker',tip:'',ctx:'',examples:[]},
    {id:'c1699',ro:'phfi-chaai',tr:'ağabey',en:'older brother',tip:'',ctx:'',examples:[]},
    {id:'c1700',ro:'phfi-saao',tr:'abla',en:'older sister',tip:'',ctx:'',examples:[]},
    {id:'c1701',ro:'oo-lim-bpik',tr:'Olimpiyatlar',en:'Olympics',tip:'',ctx:'',examples:[]},
    {id:'c1702',ro:'iik',tr:'lütfen',en:'nce please',tip:'',ctx:'',examples:[]},
    {id:'c1703',ro:'thaang',tr:'Tek Yön',en:'one way',tip:'',ctx:'',examples:[]},
    {id:'c1704',ro:'doot-den',tr:'üstün',en:'outstanding',tip:'',ctx:'',examples:[]},
    {id:'c1705',ro:'dtao-op',tr:'fırın',en:'oven',tip:'',ctx:'',examples:[]},
    {id:'c1706',ro:'chaang-jao-gfi-jao-gaan',tr:'zorba',en:'overbearing',tip:'',ctx:'',examples:[]},
    {id:'c1708',ro:'thaang-dooen',tr:'sTi-sa havai yürüyüş yolu',en:'sTi-sa overhead walkway',tip:'',ctx:'',examples:[]},
    {id:'c1709',ro:'sa-phaan-khaam',tr:'üst geçit',en:'overpass',tip:'',ctx:'',examples:[]},
    {id:'c1712',ro:'wang',tr:'Saray',en:'palace',tip:'',ctx:'',examples:[]},
    {id:'c1713',ro:'phat-sa-du',tr:'parsel',en:'parcel',tip:'',ctx:'',examples:[]},
    {id:'c1715',ro:'phaan',tr:'testi geçmek',en:'pass a test',tip:'',ctx:'',examples:[]},
    {id:'c1718',ro:'jaai-ngoen',tr:'para öde',en:'pay money',tip:'',ctx:'',examples:[]},
    {id:'c1724',ro:'gaan',tr:'piknik',en:'picnic',tip:'',ctx:'',examples:[]},
    {id:'c1725',ro:'maawn',tr:'yastık',en:'pillow',tip:'',ctx:'',examples:[]},
    {id:'c1726',ro:'nak-bin',tr:'pilot',en:'pilot',tip:'',ctx:'',examples:[]},
    {id:'c1729',ro:'dtuua-dtun',tr:'ornitorenk',en:'platypus',tip:'',ctx:'',examples:[]},
    {id:'c1730',ro:'fen',tr:'bir müzik aleti',en:'a musical instrument',tip:'',ctx:'',examples:[]},
    {id:'c1731',ro:'fen',tr:'satranç oyna',en:'play chess',tip:'',ctx:'',examples:[]},
    {id:'c1733',ro:'nak-gii-faa',tr:'oyuncu',en:'player',tip:'',ctx:'',examples:[]},
    {id:'c1734',ro:'phai',tr:'poker',en:'poker',tip:'',ctx:'',examples:[]},
    {id:'c1735',ro:'su-phaap',tr:'kibar',en:'polite',tip:'',ctx:'',examples:[]},
    {id:'c1736',ro:'sa-nam',tr:'gölet',en:'pond',tip:'',ctx:'',examples:[]},
    {id:'c1737',ro:'bproo-dtu-geet',tr:'rtugal',en:'rtugal',tip:'',ctx:'',examples:[]},
    {id:'c1738',ro:'song',tr:'mektup göndermek',en:'post a letter',tip:'',ctx:'',examples:[]},
    {id:'c1739',ro:'dtao-jaai-tai',tr:'elektrik prizi',en:'power outlet',tip:'',ctx:'',examples:[]},
    {id:'c1740',ro:'tham',tr:'hazırlanmak',en:'prepare',tip:'',ctx:'',examples:[]},
    {id:'c1742',ro:'nak',tr:'profesyonel atlet',en:'professional athlete',tip:'',ctx:'',examples:[]},
  ]
};

LESSONS[44] = L44;
