// Ders 38 verisi — CORE 2000 (1246-1325)
const L38 = {
  words:[
    {id:'c1246',ro:'phet',tr:'baharatlı',en:'spicy',tip:'',ctx:'',examples:[]},
    {id:'c1247',ro:'bprfiao',tr:'ekşi',en:'sour',tip:'',ctx:'',examples:[]},
    {id:'c1251',ro:'nuuea',tr:'et',en:'meat',tip:'',ctx:'',examples:[]},
    {id:'c1254',ro:'greep-frut',tr:'greyfurt',en:'grapefruit',tip:'',ctx:'',examples:[]},
    {id:'c1255',ro:'khraaen-booe-rfi',tr:'kızılcık',en:'cranberry',tip:'',ctx:'',examples:[]},
    {id:'c1259',ro:'saawt',tr:'sos',en:'sauce',tip:'',ctx:'',examples:[]},
    {id:'c1261',ro:'nam-man-ngaa',tr:'susam yağı',en:'sesame oil',tip:'',ctx:'',examples:[]},
    {id:'c1263',ro:'bpaaeng',tr:'un',en:'flour',tip:'',ctx:'',examples:[]},
    {id:'c1264',ro:'nam-man',tr:'yemeklik yağ',en:'ooking oil',tip:'',ctx:'',examples:[]},
    {id:'c1269',ro:'gap-khaaa-baan',tr:'ev yemekleri',en:'home cooking',tip:'',ctx:'',examples:[]},
    {id:'c1270',ro:'khaawng-waang',tr:'atıştırmalık',en:'snack',tip:'',ctx:'',examples:[]},
    {id:'c1272',ro:'im',tr:'tam dolu',en:'full',tip:'',ctx:'',examples:[]},
    {id:'c1274',ro:'khaawt',tr:'kurs yemeği',en:'course meal',tip:'',ctx:'',examples:[]},
    {id:'c1275',ro:'bup-tee',tr:'büfe',en:'buffet',tip:'',ctx:'',examples:[]},
    {id:'c1276',ro:'thaan',tr:'yiyebildiğin kadar yiyebilirsin',en:'all-you-can-eat',tip:'',ctx:'',examples:[]},
    {id:'c1277',ro:'thuua',tr:'ceviz',en:'nut',tip:'',ctx:'',examples:[]},
    {id:'c1279',ro:'ma-phaan',tr:'kaju fıstığı',en:'cashew nut',tip:'',ctx:'',examples:[]},
    {id:'c1281',ro:'baaw-rf-gaan',tr:'self servis self servis',en:'self-service self-service',tip:'',ctx:'',examples:[]},
    {id:'c1282',ro:'yuueaknam',tr:'sürahi su',en:'pitcher of water',tip:'',ctx:'',examples:[]},
    {id:'c1283',ro:'sang',tr:'yemek sipariş et',en:'order food',tip:'',ctx:'',examples:[]},
    {id:'c1284',ro:'aa-haan-fa-rang',tr:'Batı yemeği',en:'Western food',tip:'',ctx:'',examples:[]},
    {id:'c1286',ro:'aa-haan-jiin',tr:'Çin yemeği',en:'Chinese food',tip:'',ctx:'',examples:[]},
    {id:'c1289',ro:'bplaa-saeo-mawn',tr:'somon',en:'salmon',tip:'',ctx:'',examples:[]},
    {id:'c1290',ro:'bplaa-thuu-naa',tr:'ton balığı',en:'tuna',tip:'',ctx:'',examples:[]},
    {id:'c1291',ro:'gra-buuai',tr:'kepçe',en:'ladle',tip:'',ctx:'',examples:[]},
    {id:'c1292',ro:'mai-jfm-tan',tr:'kürdan',en:'toothpick',tip:'',ctx:'',examples:[]},
    {id:'c1293',ro:'jaan',tr:'ş',en:'sh',tip:'',ctx:'',examples:[]},
    {id:'c1295',ro:'gaaeo-nam',tr:'bardak',en:'drinking glass',tip:'',ctx:'',examples:[]},
    {id:'c1296',ro:'thuuai',tr:'suung kahve baaep kupa mii huu-jap',en:'suung coffee baaep mug mii huu-jap',tip:'',ctx:'',examples:[]},
    {id:'c1298',ro:'yuueak',tr:'sürahi',en:'pitcher',tip:'',ctx:'',examples:[]},
    {id:'c1299',ro:'maaw-chaa',tr:'çaydanlık',en:'teapot',tip:'',ctx:'',examples:[]},
    {id:'c1300',ro:'gaaeo',tr:'ince cam',en:'fine glass',tip:'',ctx:'',examples:[]},
    {id:'c1301',ro:'maaw',tr:'cezve',en:'coffee pot',tip:'',ctx:'',examples:[]},
    {id:'c1304',ro:'dueng',tr:'çekmek',en:'pull',tip:'',ctx:'',examples:[]},
    {id:'c1305',ro:'nang',tr:'çömelmek',en:'squat',tip:'',ctx:'',examples:[]},
    {id:'c1306',ro:'sa-daaeng',tr:'jest yapmak',en:'gesture',tip:'',ctx:'',examples:[]},
    {id:'c1309',ro:'hauy',tr:'asmak',en:'hang',tip:'',ctx:'',examples:[]},
    {id:'c1310',ro:'khut',tr:'kazmak',en:'dig',tip:'',ctx:'',examples:[]},
    {id:'c1311',ro:'khen',tr:'itmek',en:'push',tip:'',ctx:'',examples:[]},
    {id:'c1312',ro:'bpiin',tr:'tırmanmak',en:'climb',tip:'',ctx:'',examples:[]},
    {id:'c1313',ro:'saai',tr:'başını sallamak',en:'shake one\'s head',tip:'',ctx:'',examples:[]},
    {id:'c1315',ro:'kwaa',tr:'yakalamak',en:'catch',tip:'',ctx:'',examples:[]},
    {id:'c1316',ro:'khroong-raang',tr:'inşa etmek',en:'build',tip:'',ctx:'',examples:[]},
    {id:'c1317',ro:'mii',tr:'sağlıklı',en:'ealthy',tip:'',ctx:'',examples:[]},
    {id:'c1318',ro:'phaawm',tr:'sıska',en:'skinny',tip:'',ctx:'',examples:[]},
    {id:'c1319',ro:'dtfia',tr:'kısa',en:'short',tip:'',ctx:'',examples:[]},
    {id:'c1321',ro:'phaawm',tr:'ince',en:'slim',tip:'',ctx:'',examples:[]},
    {id:'c1322',ro:'bpra-pheet',tr:'vücut tipi',en:'body type',tip:'',ctx:'',examples:[]},
    {id:'c1324',ro:'naa',tr:'kalın',en:'thick',tip:'',ctx:'',examples:[]},
    {id:'c1325',ro:'phaawm',tr:'ince',en:'thin',tip:'',ctx:'',examples:[]},
  ]
};

LESSONS[38] = L38;
