// Ders 42 verisi — CORE 2000 (1537-1597)
const L42 = {
  words:[
    {id:'c1537',ro:'nik',tr:'elektronik anahtar',en:'electronic key',tip:'',ctx:'',examples:[]},
    {id:'c1538',ro:'chaang',tr:'fil',en:'elephant',tip:'',ctx:'',examples:[]},
    {id:'c1539',ro:'lfp',tr:'asansör',en:'elevator',tip:'',ctx:'',examples:[]},
    {id:'c1542',ro:'ang-grit',tr:'İngiltere',en:'England',tip:'',ctx:'',examples:[]},
    {id:'c1543',ro:'gap',tr:'ngaan harika bir hobinin tadını çıkarıyor',en:'ngaan enjoy a a-di-reek hobby',tip:'',ctx:'',examples:[]},
    {id:'c1544',ro:'git-ja-gaan',tr:'girişim',en:'enterprise',tip:'',ctx:'',examples:[]},
    {id:'c1546',ro:'bat-khaa-khao',tr:'giriş kartı',en:'entry card',tip:'',ctx:'',examples:[]},
    {id:'c1549',ro:'yuu-roo',tr:'Euro',en:'Euro',tip:'',ctx:'',examples:[]},
    {id:'c1550',ro:'at-dtraa',tr:'Döviz kuru',en:'exchange rate',tip:'',ctx:'',examples:[]},
    {id:'c1551',ro:'bprai-sa-nii',tr:'ekspres posta',en:'express mail',tip:'',ctx:'',examples:[]},
    {id:'c1552',ro:'waen-saai-dtaa',tr:'gözlük',en:'eyeglasses',tip:'',ctx:'',examples:[]},
    {id:'c1553',ro:'pha-nak-ngaan',tr:'fabrika işçisi',en:'factory worker',tip:'',ctx:'',examples:[]},
    {id:'c1554',ro:'dtot',tr:'rt',en:'rt',tip:'',ctx:'',examples:[]},
    {id:'c1555',ro:'ruuea-khaam-faak',tr:'feribot',en:'ferry',tip:'',ctx:'',examples:[]},
    {id:'c1556',ro:'theet-sa-gaan',tr:'festival',en:'festival',tip:'',ctx:'',examples:[]},
    {id:'c1557',ro:'graawk',tr:'doldur',en:'fill out',tip:'',ctx:'',examples:[]},
    {id:'c1558',ro:'gaan-saawp',tr:'son',en:'final',tip:'',ctx:'',examples:[]},
    {id:'c1559',ro:'ngaan',tr:'işi bitirmek',en:'finish work',tip:'',ctx:'',examples:[]},
    {id:'c1561',ro:'dap-phlooeng',tr:'itfaiyeci',en:'firefighter',tip:'',ctx:'',examples:[]},
    {id:'c1562',ro:'hing-hauy',tr:'ateş böceği',en:'firefly',tip:'',ctx:'',examples:[]},
    {id:'c1563',ro:'chan-nueng',tr:'birinci sınıf',en:'first class',tip:'',ctx:'',examples:[]},
    {id:'c1564',ro:'chan',tr:'zemin',en:'floor',tip:'',ctx:'',examples:[]},
    {id:'c1565',ro:'up-bpa-gaawn',tr:'yüzdürme cihazı',en:'flotation device',tip:'',ctx:'',examples:[]},
    {id:'c1566',ro:'suuan',tr:'çiçek bahçesi',en:'flower garden',tip:'',ctx:'',examples:[]},
    {id:'c1567',ro:'ma-laaeng-wan',tr:'uçmak',en:'fly',tip:'',ctx:'',examples:[]},
    {id:'c1568',ro:'a-mee-rf-gan-fut-bawn',tr:'futbol',en:'football',tip:'',ctx:'',examples:[]},
    {id:'c1569',ro:'laaek-bpliian',tr:'dtaang-bpra-theet döviz kuru',en:'dtaang-bpra-theet foreign exchange',tip:'',ctx:'',examples:[]},
    {id:'c1570',ro:'su-nak-jfng-jaawk',tr:'tilki',en:'fox',tip:'',ctx:'',examples:[]},
    {id:'c1571',ro:'fa-rang-seet',tr:'Fransa',en:'France',tip:'',ctx:'',examples:[]},
    {id:'c1572',ro:'thfi',tr:'navlun',en:'freight',tip:'',ctx:'',examples:[]},
    {id:'c1573',ro:'maaeo-nam',tr:'kürk fok',en:'fur seal',tip:'',ctx:'',examples:[]},
    {id:'c1574',ro:'gaan-khaeng-khan',tr:'oyun',en:'game',tip:'',ctx:'',examples:[]},
    {id:'c1577',ro:'yii-raap',tr:'zürafa',en:'giraffe',tip:'',ctx:'',examples:[]},
    {id:'c1578',ro:'luk',tr:'bir koltuktan vazgeçmek',en:'give up a seat',tip:'',ctx:'',examples:[]},
    {id:'c1579',ro:'dtuua-rin',tr:'sivrisinek',en:'gnat',tip:'',ctx:'',examples:[]},
    {id:'c1580',ro:'khao-gan',tr:'birlikte gitmek',en:'go with',tip:'',ctx:'',examples:[]},
    {id:'c1581',ro:'phae',tr:'keçi',en:'goat',tip:'',ctx:'',examples:[]},
    {id:'c1582',ro:'sa-wat-dii',tr:'yemek öğleden sonra',en:'food afternoon',tip:'',ctx:'',examples:[]},
    {id:'c1583',ro:'sa-wat-dii',tr:'İyi akşamlar',en:'Good evening',tip:'',ctx:'',examples:[]},
    {id:'c1584',ro:'sa-wat-dii',tr:'Günaydın',en:'Good morning',tip:'',ctx:'',examples:[]},
    {id:'c1585',ro:'ling-gaaw-rin-laa',tr:'goril',en:'gorilla',tip:'',ctx:'',examples:[]},
    {id:'c1586',ro:'bpuu',tr:'büyükbaba',en:'grandfather',tip:'',ctx:'',examples:[]},
    {id:'c1587',ro:'yaa',tr:'büyükanne',en:'grandmother',tip:'',ctx:'',examples:[]},
    {id:'c1590',ro:'roong-gii-laa',tr:'spor salonu',en:'gym',tip:'',ctx:'',examples:[]},
    {id:'c1591',ro:'yim-naat-dtik',tr:'jimnastik',en:'gymnastics',tip:'',ctx:'',examples:[]},
    {id:'c1593',ro:'khaawn',tr:'çekiç',en:'hammer',tip:'',ctx:'',examples:[]},
    {id:'c1594',ro:'thii-nang',tr:'engelli oturma yeri',en:'handicapped seating',tip:'',ctx:'',examples:[]},
    {id:'c1595',ro:'roong-gep-khruueang-bin',tr:'hangar',en:'hangar',tip:'',ctx:'',examples:[]},
    {id:'c1596',ro:'wat-dii',tr:'MERHABA',en:'Hi',tip:'',ctx:'',examples:[]},
    {id:'c1597',ro:'nooen-khao',tr:'tepe',en:'hill',tip:'',ctx:'',examples:[]},
  ]
};

LESSONS[42] = L42;
