// Ders 46 verisi — CORE 2000 (1822-1888)
const L46 = {
  words:[
    {id:'c1822',ro:'bplaa-gra-been',tr:'vatoz',en:'stingray',tip:'',ctx:'',examples:[]},
    {id:'c1823',ro:'bpaai-hai-yut',tr:'dur işareti',en:'stop sign',tip:'',ctx:'',examples:[]},
    {id:'c1824',ro:'chawng-khaaep',tr:'boğaz',en:'strait',tip:'',ctx:'',examples:[]},
    {id:'c1826',ro:'khap-ban-chaa',tr:'ast',en:'subordinate',tip:'',ctx:'',examples:[]},
    {id:'c1828',ro:'roong-riian',tr:'duu-raawn yaz okulu',en:'duu-raawn summer school',tip:'',ctx:'',examples:[]},
    {id:'c1829',ro:'bpit-thooem',tr:'yaz tatili',en:'summer vacation',tip:'',ctx:'',examples:[]},
    {id:'c1832',ro:'thawng',tr:'internette gezinmek',en:'surf the net',tip:'',ctx:'',examples:[]},
    {id:'c1833',ro:'nang',tr:'gerilim',en:'suspense',tip:'',ctx:'',examples:[]},
    {id:'c1834',ro:'hong',tr:'kuğu',en:'swan',tip:'',ctx:'',examples:[]},
    {id:'c1835',ro:'waai-nam',tr:'yüzme',en:'swimming',tip:'',ctx:'',examples:[]},
    {id:'c1837',ro:'mut',tr:'raptiye',en:'tack',tip:'',ctx:'',examples:[]},
    {id:'c1838',ro:'thaai',tr:'fotoğraf çek',en:'take a picture',tip:'',ctx:'',examples:[]},
    {id:'c1839',ro:'saawp',tr:'teste gir',en:'take a test',tip:'',ctx:'',examples:[]},
    {id:'c1840',ro:'dta-lap-meet',tr:'mezura',en:'tape measure',tip:'',ctx:'',examples:[]},
    {id:'c1841',ro:'thfi',tr:'vergisiz',en:'tax-free',tip:'',ctx:'',examples:[]},
    {id:'c1842',ro:'thiim',tr:'takım',en:'team',tip:'',ctx:'',examples:[]},
    {id:'c1844',ro:'saan',tr:'terminal',en:'terminal',tip:'',ctx:'',examples:[]},
    {id:'c1845',ro:'khaawp-khun',tr:'Çok teşekkür ederim',en:'Thank you very much',tip:'',ctx:'',examples:[]},
    {id:'c1846',ro:'khaawp-khun',tr:'Teşekkür etmek',en:'Thank',tip:'',ctx:'',examples:[]},
    {id:'c1847',ro:'mai',tr:'Tamam',en:'That\'s all right',tip:'',ctx:'',examples:[]},
    {id:'c1848',ro:'nfi-khuue',tr:'Bu',en:'This is',tip:'',ctx:'',examples:[]},
    {id:'c1849',ro:'nfi',tr:'Bu sizin için',en:'This is for you',tip:'',ctx:'',examples:[]},
    {id:'c1850',ro:'chawng',tr:'Kepencere',en:'ketwindow',tip:'',ctx:'',examples:[]},
    {id:'c1851',ro:'suuea',tr:'kaplan',en:'tiger',tip:'',ctx:'',examples:[]},
    {id:'c1852',ro:'khwaam-dtaaek-dtaang',tr:'saat farkı',en:'time difference',tip:'',ctx:'',examples:[]},
    {id:'c1853',ro:'gra-daat',tr:'doku',en:'tissue',tip:'',ctx:'',examples:[]},
    {id:'c1855',ro:'gra-daat-cham-ra',tr:'tuvalet kağıdı',en:'toilet paper',tip:'',ctx:'',examples:[]},
    {id:'c1856',ro:'muue',tr:'alet kutusu',en:'toolbox',tip:'',ctx:'',examples:[]},
    {id:'c1858',ro:'thawng-thfiao',tr:'tur',en:'tour',tip:'',ctx:'',examples:[]},
    {id:'c1860',ro:'thfiao',tr:'turistik cazibe',en:'tourist attraction',tip:'',ctx:'',examples:[]},
    {id:'c1861',ro:'haaw',tr:'kule',en:'tower',tip:'',ctx:'',examples:[]},
    {id:'c1862',ro:'grii-thaa',tr:'atletizm',en:'track and field',tip:'',ctx:'',examples:[]},
    {id:'c1863',ro:'gaan',tr:'trafik sıkışıklığı',en:'traffic jam',tip:'',ctx:'',examples:[]},
    {id:'c1864',ro:'kha-buuan',tr:'numara değil',en:'ain number',tip:'',ctx:'',examples:[]},
    {id:'c1866',ro:'bpliian',tr:'aktarma',en:'transfer',tip:'',ctx:'',examples:[]},
    {id:'c1867',ro:'bplaae',tr:'tercüme etmek',en:'translate',tip:'',ctx:'',examples:[]},
    {id:'c1868',ro:'baaw-ri-sat',tr:'seyahat acentası',en:'travel agency',tip:'',ctx:'',examples:[]},
    {id:'c1869',ro:'chek-dooen-thaang',tr:'seyahat çeki',en:'traveler\'s check',tip:'',ctx:'',examples:[]},
    {id:'c1873',ro:'gai-nguuang',tr:'Türkiye',en:'turkey',tip:'',ctx:'',examples:[]},
    {id:'c1875',ro:'lfiao',tr:'köşeyi dön',en:'turn a corner',tip:'',ctx:'',examples:[]},
    {id:'c1876',ro:'khiit-sen-dtai',tr:'altı çizili',en:'underline',tip:'',ctx:'',examples:[]},
    {id:'c1878',ro:'sa-ha-rat',tr:'Amerika Birleşik Devletleri',en:'the America United States of',tip:'',ctx:'',examples:[]},
    {id:'c1879',ro:'mai',tr:'tatminsiz',en:'unsatisfied',tip:'',ctx:'',examples:[]},
    {id:'c1881',ro:'hauy-men',tr:'kestane',en:'urchin',tip:'',ctx:'',examples:[]},
    {id:'c1882',ro:'thaai',tr:'idrar yapmak',en:'urinate',tip:'',ctx:'',examples:[]},
    {id:'c1883',ro:'wan-yut',tr:'tatil',en:'vacation',tip:'',ctx:'',examples:[]},
    {id:'c1884',ro:'theep-wf-dii-oo',tr:'VCR',en:'VCR',tip:'',ctx:'',examples:[]},
    {id:'c1886',ro:'kham',tr:'fiil',en:'verb',tip:'',ctx:'',examples:[]},
    {id:'c1887',ro:'wii-saa',tr:'Visa',en:'visa',tip:'',ctx:'',examples:[]},
    {id:'c1888',ro:'yfiam-yaat',tr:'akrabaları ziyaret etmek',en:'visit relatives',tip:'',ctx:'',examples:[]},
  ]
};

LESSONS[46] = L46;
