// Ders 47 verisi — CORE 2000 (1889-1951)
const L47 = {
  words:[
    {id:'c1889',ro:'nak-phaak',tr:'seslendirme sanatçısı',en:'voice actor',tip:'',ctx:'',examples:[]},
    {id:'c1891',ro:'tao',tr:'bekleme odası',en:'waiting room',tip:'',ctx:'',examples:[]},
    {id:'c1892',ro:'gam-phaaeng',tr:'düşmek',en:'fall',tip:'',ctx:'',examples:[]},
    {id:'c1893',ro:'pha-nang',tr:'duvar saati',en:'wall clock',tip:'',ctx:'',examples:[]},
    {id:'c1895',ro:'thfi-din',tr:'çorak arazi',en:'wasteland',tip:'',ctx:'',examples:[]},
    {id:'c1896',ro:'nam-dtok',tr:'şelale',en:'waterfall',tip:'',ctx:'',examples:[]},
    {id:'c1897',ro:'wat-cha-phuuet',tr:'esrar',en:'weed',tip:'',ctx:'',examples:[]},
    {id:'c1898',ro:'yin-dii',tr:'Hoş geldin',en:'welcome',tip:'',ctx:'',examples:[]},
    {id:'c1899',ro:'man',tr:'Nedir',en:'What is',tip:'',ctx:'',examples:[]},
    {id:'c1900',ro:'nan',tr:'ne',en:'What\'s',tip:'',ctx:'',examples:[]},
    {id:'c1901',ro:'khaawng-khun',tr:'E-postan ne?',en:'What\'s a-rai your e-mail',tip:'',ctx:'',examples:[]},
    {id:'c1902',ro:'khun',tr:'seninki ne',en:'What\'s your',tip:'',ctx:'',examples:[]},
    {id:'c1903',ro:'khaawng-khun',tr:'a-rai telefonun nedir',en:'a-rai What\'s your phone',tip:'',ctx:'',examples:[]},
    {id:'c1904',ro:'khun',tr:'Neredesin',en:'Where are you',tip:'',ctx:'',examples:[]},
    {id:'c1905',ro:'khun',tr:'neredesin',en:'Where do you',tip:'',ctx:'',examples:[]},
    {id:'c1906',ro:'hawng-nam',tr:'nerede',en:'Where is the',tip:'',ctx:'',examples:[]},
    {id:'c1907',ro:'khrai',tr:'kim',en:'Who is',tip:'',ctx:'',examples:[]},
    {id:'c1908',ro:'nan',tr:'kim',en:'Who is',tip:'',ctx:'',examples:[]},
    {id:'c1909',ro:'phan-ra-yaa',tr:'eş',en:'wife',tip:'',ctx:'',examples:[]},
    {id:'c1911',ro:'sa-nun',tr:'söğüt ağacı',en:'willow tree',tip:'',ctx:'',examples:[]},
    {id:'c1912',ro:'hiiao',tr:'solgunluk',en:'wilt',tip:'',ctx:'',examples:[]},
    {id:'c1913',ro:'cha-na',tr:'kazanç',en:'win',tip:'',ctx:'',examples:[]},
    {id:'c1914',ro:'thfi-nang',tr:'pencere koltuğu',en:'window seat',tip:'',ctx:'',examples:[]},
    {id:'c1915',ro:'phuu-cha-na',tr:'kazanan',en:'winner',tip:'',ctx:'',examples:[]},
    {id:'c1917',ro:'wawm-baaet',tr:'vombat',en:'wombat',tip:'',ctx:'',examples:[]},
    {id:'c1918',ro:'kham',tr:'kelime',en:'word',tip:'',ctx:'',examples:[]},
    {id:'c1921',ro:'gang-won',tr:'endişelenmek',en:'worry',tip:'',ctx:'',examples:[]},
    {id:'c1922',ro:'jot-maai',tr:'bir mektup yaz',en:'write a letter',tip:'',ctx:'',examples:[]},
    {id:'c1925',ro:'sa-naam',tr:'bahçe',en:'yard',tip:'',ctx:'',examples:[]},
    {id:'c1926',ro:'chai',tr:'Evet',en:'yes',tip:'',ctx:'',examples:[]},
    {id:'c1927',ro:'khwaam-yin-dii',tr:'rica ederim',en:'ou\'re welcome',tip:'',ctx:'',examples:[]},
    {id:'c1928',ro:'naawng-chaai',tr:'Küçük kardeş',en:'younger brother',tip:'',ctx:'',examples:[]},
    {id:'c1929',ro:'naawng-saao',tr:'küçük kız kardeş',en:'younger sister',tip:'',ctx:'',examples:[]},
    {id:'c1930',ro:'yao-wa-chon',tr:'gençlik',en:'youth',tip:'',ctx:'',examples:[]},
    {id:'c1932',ro:'thai',tr:'Tayland',en:'Thailand',tip:'',ctx:'',examples:[]},
    {id:'c1933',ro:'wfiat-naam',tr:'Vietnam',en:'Vietnam',tip:'',ctx:'',examples:[]},
    {id:'c1935',ro:'gam-phuu-chaa',tr:'Kamboçya',en:'Cambodia',tip:'',ctx:'',examples:[]},
    {id:'c1936',ro:'pha-maa',tr:'Myanmar',en:'Myanmar',tip:'',ctx:'',examples:[]},
    {id:'c1938',ro:'in-doo-nii-siia',tr:'Endonezya',en:'Indonesia',tip:'',ctx:'',examples:[]},
    {id:'c1939',ro:'sa-ha-rat',tr:'Amerika Birleşik Devletleri',en:'the United States',tip:'',ctx:'',examples:[]},
    {id:'c1940',ro:'haa-naauy',tr:'Hanoi',en:'Hanoi',tip:'',ctx:'',examples:[]},
    {id:'c1941',ro:'guua-laa-lam-bpooe',tr:'uala Lumpur',en:'uala Lumpur',tip:'',ctx:'',examples:[]},
    {id:'c1942',ro:'pha-nom-bpeen',tr:'Phnom Penh',en:'Phnom Penh',tip:'',ctx:'',examples:[]},
    {id:'c1943',ro:'nee-bpyii-daaw',tr:'Nay Pyi Taw',en:'Nay Pyi Taw',tip:'',ctx:'',examples:[]},
    {id:'c1944',ro:'wiiang-jan',tr:'Vientiane',en:'Vientiane',tip:'',ctx:'',examples:[]},
    {id:'c1946',ro:'gaawn',tr:'Güle güle',en:'Bye',tip:'',ctx:'',examples:[]},
    {id:'c1947',ro:'mai',tr:'sorun değil',en:'It\'s alright',tip:'',ctx:'',examples:[]},
    {id:'c1949',ro:'thfi-yuu',tr:'e-posta adresi',en:'e-mail address',tip:'',ctx:'',examples:[]},
    {id:'c1950',ro:'ngaan',tr:'hobi',en:'hobby',tip:'',ctx:'',examples:[]},
    {id:'c1951',ro:'thai',tr:'Tay dili',en:'Thai',tip:'',ctx:'',examples:[]},
  ]
};

LESSONS[47] = L47;
