// Ders 24 verisi — CORE 2000 (301-367)
const L24 = {
  words:[
    {id:'c301',ro:'jao-naai',tr:'üst',en:'superior',tip:'',ctx:'',examples:[]},
    {id:'c302',ro:'baaw-ri-sat',tr:'şirket',en:'company',tip:'',ctx:'',examples:[]},
    {id:'c303',ro:'ngooen-duuean',tr:'maaş',en:'salary',tip:'',ctx:'',examples:[]},
    {id:'c304',ro:'wft-tha-yu',tr:'radyo',en:'radio',tip:'',ctx:'',examples:[]},
    {id:'c306',ro:'in-dtooe-net',tr:'internet',en:'Internet',tip:'',ctx:'',examples:[]},
    {id:'c307',ro:'nang-suue-phim',tr:'gazete',en:'newspaper',tip:'',ctx:'',examples:[]},
    {id:'c308',ro:'chaawng-khaao',tr:'haber kanalı',en:'news channel',tip:'',ctx:'',examples:[]},
    {id:'c310',ro:'phaap-waat',tr:'tablo',en:'painting',tip:'',ctx:'',examples:[]},
    {id:'c313',ro:'la-khaawn-oo-phee-raa',tr:'opera',en:'opera',tip:'',ctx:'',examples:[]},
    {id:'c314',ro:'phaawn-khlaai',tr:'rahatlamak',en:'relax',tip:'',ctx:'',examples:[]},
    {id:'c315',ro:'gra-daan-wai-baawt',tr:'beyaz tahta',en:'whiteboard',tip:'',ctx:'',examples:[]},
    {id:'c316',ro:'gra-daan-dam',tr:'yazı tahtası',en:'blackboard',tip:'',ctx:'',examples:[]},
    {id:'c317',ro:'khaaw-saawp',tr:'test',en:'test',tip:'',ctx:'',examples:[]},
    {id:'c320',ro:'ngaan',tr:'iş',en:'job',tip:'',ctx:'',examples:[]},
    {id:'c321',ro:'baaw-dii',tr:'başkan',en:'president',tip:'',ctx:'',examples:[]},
    {id:'c322',ro:'ut-saa-ha-gam',tr:'endüstri',en:'industry',tip:'',ctx:'',examples:[]},
    {id:'c323',ro:'khem-khat',tr:'kemer',en:'belt',tip:'',ctx:'',examples:[]},
    {id:'c325',ro:'ngoen',tr:'para',en:'money',tip:'',ctx:'',examples:[]},
    {id:'c327',ro:'bai-jaaeng-nfi',tr:'fatura',en:'bill',tip:'',ctx:'',examples:[]},
    {id:'c328',ro:'gaan-thaai-phaap',tr:'fotoğrafçılık',en:'photography',tip:'',ctx:'',examples:[]},
    {id:'c329',ro:'thaawt',tr:'çıkarmak',en:'take off',tip:'',ctx:'',examples:[]},
    {id:'c330',ro:'hawng-naawn',tr:'yatak odası',en:'bedroom',tip:'',ctx:'',examples:[]},
    {id:'c331',ro:'hawng-khruua',tr:'mutfak',en:'kitchen',tip:'',ctx:'',examples:[]},
    {id:'c332',ro:'hawng-aap-nam',tr:'banyo',en:'bathroom',tip:'',ctx:'',examples:[]},
    {id:'c334',ro:'naaeng',tr:'terfi',en:'promotion',tip:'',ctx:'',examples:[]},
    {id:'c336',ro:'ngaan-sop',tr:'cenaze',en:'funeral',tip:'',ctx:'',examples:[]},
    {id:'c337',ro:'ngaan-dtaaeng-ngaan',tr:'düğün',en:'wedding',tip:'',ctx:'',examples:[]},
    {id:'c338',ro:'a-thf-baai',tr:'açıklamak',en:'explain',tip:'',ctx:'',examples:[]},
    {id:'c339',ro:'daan-lang',tr:'geri',en:'back',tip:'',ctx:'',examples:[]},
    {id:'c341',ro:'nek-thai',tr:'kravat',en:'necktie',tip:'',ctx:'',examples:[]},
    {id:'c342',ro:'suut',tr:'uygun olmak',en:'suit',tip:'',ctx:'',examples:[]},
    {id:'c343',ro:'raawng-thao-phaa-bai',tr:'spor ayakkabı',en:'sneaker',tip:'',ctx:'',examples:[]},
    {id:'c344',ro:'yfi-sip-et',tr:'yirmi bir',en:'twenty-one',tip:'',ctx:'',examples:[]},
    {id:'c345',ro:'yfi-sip-saawng',tr:'yirmi iki',en:'twenty-two',tip:'',ctx:'',examples:[]},
    {id:'c346',ro:'saam-sip-saam',tr:'otuz üç',en:'thirty-three',tip:'',ctx:'',examples:[]},
    {id:'c348',ro:'haa-sip-haa',tr:'elli beş',en:'fifty-five',tip:'',ctx:'',examples:[]},
    {id:'c349',ro:'nak-riian',tr:'öğrenci',en:'student',tip:'',ctx:'',examples:[]},
    {id:'c350',ro:'duu',tr:'kol saati',en:'watch',tip:'',ctx:'',examples:[]},
    {id:'c351',ro:'hawng-riian',tr:'sınıf',en:'classroom',tip:'',ctx:'',examples:[]},
    {id:'c352',ro:'roong-riian',tr:'okul',en:'school',tip:'',ctx:'',examples:[]},
    {id:'c353',ro:'gao-fi-riian',tr:'okul sandalyesi',en:'school chair',tip:'',ctx:'',examples:[]},
    {id:'c355',ro:'len-in-dtooe-net',tr:'internette gezinmek',en:'surf the internet',tip:'',ctx:'',examples:[]},
    {id:'c357',ro:'glap',tr:'geri dönmek',en:'return',tip:'',ctx:'',examples:[]},
    {id:'c358',ro:'aap-naam',tr:'yıkanmak',en:'bathe',tip:'',ctx:'',examples:[]},
    {id:'c359',ro:'naawn',tr:'uyumak',en:'sleep',tip:'',ctx:'',examples:[]},
    {id:'c360',ro:'thft-dtai',tr:'güney',en:'south',tip:'',ctx:'',examples:[]},
    {id:'c363',ro:'dtuuen-naawn',tr:'uyanmak',en:'wake up',tip:'',ctx:'',examples:[]},
    {id:'c364',ro:'dooen-thaang',tr:'işe gidip gelmek',en:'commute',tip:'',ctx:'',examples:[]},
    {id:'c365',ro:'gin',tr:'yemek yemek',en:'eat',tip:'',ctx:'',examples:[]},
    {id:'c367',ro:'wan-na-gam',tr:'edebiyat',en:'literature',tip:'',ctx:'',examples:[]},
  ]
};

LESSONS[24] = L24;
