// Ders 20 verisi — CORE 2000
const L20 = {
  words:[
    {id:'c1',ro:'sa-wat-dii',tr:'Merhaba',en:'Hello',tip:'',ctx:'',examples:[{ro:'Phom phûut wâa \'sa-wat-dii\'',tr:'Ben \'Merhaba\' derim',bd:[{ro:'Phom',tr:'Ben',role:'S'},{ro:'phûut wâa',tr:'diyorum ki',role:'V'},{ro:'sa-wat-dii',tr:'Merhaba',role:'O'}]}]},
    {id:'c5',ro:'yin-dii',tr:'Tanıştığıma memnun oldum',en:'Nice to meet you',tip:'',ctx:'',examples:[{ro:'Nii khu yin-dii',tr:'Bu, Tanıştığıma memnun oldum',bd:[{ro:'Nii',tr:'Bu',role:'S'},{ro:'khu',tr:'demektir',role:'V'},{ro:'yin-dii',tr:'Tanıştığıma memnun oldum',role:'O'}]}]},
    {id:'c6',ro:'sa-baai',tr:'nasılsın',en:'How are',tip:'',ctx:'',examples:[{ro:'Khun tham sa-baai mâi?',tr:'nasılsın?',bd:[{ro:'Khun',tr:'Sen/Siz',role:'S'},{ro:'tham',tr:'yapıyorsun',role:'V'},{ro:'sa-baai',tr:'nasılsın',role:'O'},{ro:'mâi?',tr:'(soru eki)',role:'Soru (SONDA)'}]}]},
    {id:'c7',ro:'chai',tr:'Evet',en:'Yes',tip:'',ctx:'',examples:[{ro:'Nii khu chai',tr:'Bu, Evet',bd:[{ro:'Nii',tr:'Bu',role:'S'},{ro:'khu',tr:'demektir',role:'V'},{ro:'chai',tr:'Evet',role:'O'}]}]},
    {id:'c8',ro:'mai',tr:'HAYIR',en:'No',tip:'',ctx:'',examples:[{ro:'Nii khu mai',tr:'Bu, HAYIR',bd:[{ro:'Nii',tr:'Bu',role:'S'},{ro:'khu',tr:'demektir',role:'V'},{ro:'mai',tr:'HAYIR',role:'O'}]}]},
    {id:'c9',ro:'khaawp-khun',tr:'Teşekkür ederim',en:'Thank you',tip:'',ctx:'',examples:[{ro:'Phom phûut wâa \'khaawp-khun\'',tr:'Ben \'Teşekkür ederim\' derim',bd:[{ro:'Phom',tr:'Ben',role:'S'},{ro:'phûut wâa',tr:'diyorum ki',role:'V'},{ro:'khaawp-khun',tr:'Teşekkür ederim',role:'O'}]}]},
    {id:'c11',ro:'a-gaawn',tr:'elveda',en:'oodbye',tip:'',ctx:'',examples:[{ro:'Phom phûut wâa \'a-gaawn\'',tr:'Ben \'elveda\' derim',bd:[{ro:'Phom',tr:'Ben',role:'S'},{ro:'phûut wâa',tr:'diyorum ki',role:'V'},{ro:'a-gaawn',tr:'elveda',role:'O'}]}]},
    {id:'c12',ro:'mai-dii',tr:'kötü',en:'bad',tip:'',ctx:'',examples:[{ro:'Nii khu mai-dii',tr:'Bu, kötü',bd:[{ro:'Nii',tr:'Bu',role:'S'},{ro:'khu',tr:'demektir',role:'V'},{ro:'mai-dii',tr:'kötü',role:'O'}]}]},
    {id:'c13',ro:'dii',tr:'iyi',en:'good',tip:'',ctx:'',examples:[{ro:'Nii khu dii',tr:'Bu, iyi',bd:[{ro:'Nii',tr:'Bu',role:'S'},{ro:'khu',tr:'demektir',role:'V'},{ro:'dii',tr:'iyi',role:'O'}]}]},
    {id:'c16',ro:'ngaai',tr:'kolay',en:'easy',tip:'',ctx:'',examples:[{ro:'Nii khu ngaai',tr:'Bu, kolay',bd:[{ro:'Nii',tr:'Bu',role:'S'},{ro:'khu',tr:'demektir',role:'V'},{ro:'ngaai',tr:'kolay',role:'O'}]}]},
    {id:'c19',ro:'glai',tr:'uzak',en:'far',tip:'',ctx:'',examples:[{ro:'Nii khu glai',tr:'Bu, uzak',bd:[{ro:'Nii',tr:'Bu',role:'S'},{ro:'khu',tr:'demektir',role:'V'},{ro:'glai',tr:'uzak',role:'O'}]}]},
    {id:'c21',ro:'wan-nfi',tr:'Bugün',en:'today',tip:'',ctx:'',examples:[{ro:'Nii khu wan-nfi',tr:'Bu, Bugün',bd:[{ro:'Nii',tr:'Bu',role:'S'},{ro:'khu',tr:'demektir',role:'V'},{ro:'wan-nfi',tr:'Bugün',role:'O'}]}]},
    {id:'c24',ro:'sap-daa',tr:'hafta',en:'week',tip:'',ctx:'',examples:[{ro:'Nii khu sap-daa',tr:'Bu, hafta',bd:[{ro:'Nii',tr:'Bu',role:'S'},{ro:'khu',tr:'demektir',role:'V'},{ro:'sap-daa',tr:'hafta',role:'O'}]}]},
    {id:'c26',ro:'wf-naa-thii',tr:'ikinci',en:'second',tip:'',ctx:'',examples:[{ro:'Nii khu wf-naa-thii',tr:'Bu, ikinci',bd:[{ro:'Nii',tr:'Bu',role:'S'},{ro:'khu',tr:'demektir',role:'V'},{ro:'wf-naa-thii',tr:'ikinci',role:'O'}]}]},
    {id:'c27',ro:'naa-thii',tr:'dakika',en:'minute',tip:'',ctx:'',examples:[{ro:'Nii khu naa-thii',tr:'Bu, dakika',bd:[{ro:'Nii',tr:'Bu',role:'S'},{ro:'khu',tr:'demektir',role:'V'},{ro:'naa-thii',tr:'dakika',role:'O'}]}]},
    {id:'c31',ro:'bpa-dti-thin',tr:'takvim',en:'calendar',tip:'',ctx:'',examples:[{ro:'Nii khu bpa-dti-thin',tr:'Bu, takvim',bd:[{ro:'Nii',tr:'Bu',role:'S'},{ro:'khu',tr:'demektir',role:'V'},{ro:'bpa-dti-thin',tr:'takvim',role:'O'}]}]},
    {id:'c33',ro:'wan',tr:'Salı',en:'Tuesday',tip:'',ctx:'',examples:[{ro:'Nii khu wan',tr:'Bu, Salı',bd:[{ro:'Nii',tr:'Bu',role:'S'},{ro:'khu',tr:'demektir',role:'V'},{ro:'wan',tr:'Salı',role:'O'}]}]},
    {id:'c34',ro:'wan',tr:'Çarşamba',en:'Wednesday',tip:'',ctx:'',examples:[{ro:'Nii khu wan',tr:'Bu, Çarşamba',bd:[{ro:'Nii',tr:'Bu',role:'S'},{ro:'khu',tr:'demektir',role:'V'},{ro:'wan',tr:'Çarşamba',role:'O'}]}]},
    {id:'c35',ro:'baaw-dii',tr:'Perşembe',en:'Thursday',tip:'',ctx:'',examples:[{ro:'Nii khu baaw-dii',tr:'Bu, Perşembe',bd:[{ro:'Nii',tr:'Bu',role:'S'},{ro:'khu',tr:'demektir',role:'V'},{ro:'baaw-dii',tr:'Perşembe',role:'O'}]}]},
    {id:'c36',ro:'wan',tr:'Cuma',en:'Friday',tip:'',ctx:'',examples:[{ro:'Nii khu wan',tr:'Bu, Cuma',bd:[{ro:'Nii',tr:'Bu',role:'S'},{ro:'khu',tr:'demektir',role:'V'},{ro:'wan',tr:'Cuma',role:'O'}]}]},
    {id:'c37',ro:'wan',tr:'Cumartesi',en:'Saturday',tip:'',ctx:'',examples:[{ro:'Nii khu wan',tr:'Bu, Cumartesi',bd:[{ro:'Nii',tr:'Bu',role:'S'},{ro:'khu',tr:'demektir',role:'V'},{ro:'wan',tr:'Cumartesi',role:'O'}]}]},
    {id:'c38',ro:'wan',tr:'Pazar',en:'Sunday',tip:'',ctx:'',examples:[{ro:'Nii khu wan',tr:'Bu, Pazar',bd:[{ro:'Nii',tr:'Bu',role:'S'},{ro:'khu',tr:'demektir',role:'V'},{ro:'wan',tr:'Pazar',role:'O'}]}]},
    {id:'c40',ro:'bpai',tr:'Gitmek',en:'go',tip:'',ctx:'',examples:[{ro:'Phom bpai thuk wan',tr:'Ben her gün Gitmek',bd:[{ro:'Phom',tr:'Ben',role:'S'},{ro:'bpai',tr:'Gitmek',role:'V'},{ro:'thuk wan',tr:'her gün',role:'K'}]}]},
    {id:'c42',ro:'a-raauy',tr:'lezzetli',en:'delicious',tip:'',ctx:'',examples:[{ro:'Nii khu a-raauy',tr:'Bu, lezzetli',bd:[{ro:'Nii',tr:'Bu',role:'S'},{ro:'khu',tr:'demektir',role:'V'},{ro:'a-raauy',tr:'lezzetli',role:'O'}]}]},
    {id:'c43',ro:'nam',tr:'su',en:'water',tip:'',ctx:'',examples:[{ro:'Nii khu nam',tr:'Bu, su',bd:[{ro:'Nii',tr:'Bu',role:'S'},{ro:'khu',tr:'demektir',role:'V'},{ro:'nam',tr:'su',role:'O'}]}]},
    {id:'c44',ro:'chaa',tr:'çay',en:'tea',tip:'',ctx:'',examples:[{ro:'Nii khu chaa',tr:'Bu, çay',bd:[{ro:'Nii',tr:'Bu',role:'S'},{ro:'khu',tr:'demektir',role:'V'},{ro:'chaa',tr:'çay',role:'O'}]}]},
    {id:'c45',ro:'gaa-faae',tr:'Kahve',en:'coffee',tip:'',ctx:'',examples:[{ro:'Nii khu gaa-faae',tr:'Bu, Kahve',bd:[{ro:'Nii',tr:'Bu',role:'S'},{ro:'khu',tr:'demektir',role:'V'},{ro:'gaa-faae',tr:'Kahve',role:'O'}]}]},
    {id:'c47',ro:'waai',tr:'şarap',en:'wine',tip:'',ctx:'',examples:[{ro:'Nii khu waai',tr:'Bu, şarap',bd:[{ro:'Nii',tr:'Bu',role:'S'},{ro:'khu',tr:'demektir',role:'V'},{ro:'waai',tr:'şarap',role:'O'}]}]},
    {id:'c48',ro:'nuuea-wuua',tr:'biftek',en:'beef',tip:'',ctx:'',examples:[{ro:'Nii khu nuuea-wuua',tr:'Bu, biftek',bd:[{ro:'Nii',tr:'Bu',role:'S'},{ro:'khu',tr:'demektir',role:'V'},{ro:'nuuea-wuua',tr:'biftek',role:'O'}]}]},
    {id:'c49',ro:'gai',tr:'tavuk',en:'chicken',tip:'',ctx:'',examples:[{ro:'Nii khu gai',tr:'Bu, tavuk',bd:[{ro:'Nii',tr:'Bu',role:'S'},{ro:'khu',tr:'demektir',role:'V'},{ro:'gai',tr:'tavuk',role:'O'}]}]},
    {id:'c51',ro:'bplaa',tr:'balık',en:'fish',tip:'',ctx:'',examples:[{ro:'Nii khu bplaa',tr:'Bu, balık',bd:[{ro:'Nii',tr:'Bu',role:'S'},{ro:'khu',tr:'demektir',role:'V'},{ro:'bplaa',tr:'balık',role:'O'}]}]},
    {id:'c52',ro:'nuuea-gae',tr:'kuzu',en:'lamb',tip:'',ctx:'',examples:[{ro:'Nii khu nuuea-gae',tr:'Bu, kuzu',bd:[{ro:'Nii',tr:'Bu',role:'S'},{ro:'khu',tr:'demektir',role:'V'},{ro:'nuuea-gae',tr:'kuzu',role:'O'}]}]},
    {id:'c54',ro:'jao-naa-thfi-dtam-ruuat',tr:'polis memuru',en:'police officer',tip:'',ctx:'',examples:[{ro:'Nii khu jao-naa-thfi-dtam-ruuat',tr:'Bu, polis memuru',bd:[{ro:'Nii',tr:'Bu',role:'S'},{ro:'khu',tr:'demektir',role:'V'},{ro:'jao-naa-thfi-dtam-ruuat',tr:'polis memuru',role:'O'}]}]},
    {id:'c55',ro:'khruu',tr:'Öğretmen',en:'teacher',tip:'',ctx:'',examples:[{ro:'Nii khu khruu',tr:'Bu, Öğretmen',bd:[{ro:'Nii',tr:'Bu',role:'S'},{ro:'khu',tr:'demektir',role:'V'},{ro:'khruu',tr:'Öğretmen',role:'O'}]}]},
    {id:'c57',ro:'maa',tr:'Gelmek',en:'come',tip:'',ctx:'',examples:[{ro:'Phom maa thuk wan',tr:'Ben her gün Gelmek',bd:[{ro:'Phom',tr:'Ben',role:'S'},{ro:'maa',tr:'Gelmek',role:'V'},{ro:'thuk wan',tr:'her gün',role:'K'}]}]},
    {id:'c58',ro:'hen',tr:'Görmek',en:'see',tip:'',ctx:'',examples:[{ro:'Phom hen thuk wan',tr:'Ben her gün Görmek',bd:[{ro:'Phom',tr:'Ben',role:'S'},{ro:'hen',tr:'Görmek',role:'V'},{ro:'thuk wan',tr:'her gün',role:'K'}]}]},
    {id:'c61',ro:'saa-maat',tr:'olabilmek',en:'can',tip:'',ctx:'',examples:[{ro:'Phom saa-maat thuk wan',tr:'Ben her gün olabilmek',bd:[{ro:'Phom',tr:'Ben',role:'S'},{ro:'saa-maat',tr:'olabilmek',role:'V'},{ro:'thuk wan',tr:'her gün',role:'K'}]}]},
    {id:'c62',ro:'sewn',tr:'sıfır',en:'zero',tip:'',ctx:'',examples:[{ro:'Nii khu sewn',tr:'Bu, sıfır',bd:[{ro:'Nii',tr:'Bu',role:'S'},{ro:'khu',tr:'demektir',role:'V'},{ro:'sewn',tr:'sıfır',role:'O'}]}]},
    {id:'c63',ro:'nueng',tr:'bir',en:'one',tip:'',ctx:'',examples:[{ro:'Nii khu nueng',tr:'Bu, bir',bd:[{ro:'Nii',tr:'Bu',role:'S'},{ro:'khu',tr:'demektir',role:'V'},{ro:'nueng',tr:'bir',role:'O'}]}]},
    {id:'c64',ro:'saawng',tr:'iki',en:'two',tip:'',ctx:'',examples:[{ro:'Nii khu saawng',tr:'Bu, iki',bd:[{ro:'Nii',tr:'Bu',role:'S'},{ro:'khu',tr:'demektir',role:'V'},{ro:'saawng',tr:'iki',role:'O'}]}]},
    {id:'c65',ro:'saam',tr:'üç',en:'three',tip:'',ctx:'',examples:[{ro:'Nii khu saam',tr:'Bu, üç',bd:[{ro:'Nii',tr:'Bu',role:'S'},{ro:'khu',tr:'demektir',role:'V'},{ro:'saam',tr:'üç',role:'O'}]}]},
    {id:'c66',ro:'sii',tr:'dört',en:'four',tip:'',ctx:'',examples:[{ro:'Nii khu sii',tr:'Bu, dört',bd:[{ro:'Nii',tr:'Bu',role:'S'},{ro:'khu',tr:'demektir',role:'V'},{ro:'sii',tr:'dört',role:'O'}]}]},
    {id:'c68',ro:'hok',tr:'altı',en:'six',tip:'',ctx:'',examples:[{ro:'Nii khu hok',tr:'Bu, altı',bd:[{ro:'Nii',tr:'Bu',role:'S'},{ro:'khu',tr:'demektir',role:'V'},{ro:'hok',tr:'altı',role:'O'}]}]},
    {id:'c69',ro:'jet',tr:'Yedi',en:'seven',tip:'',ctx:'',examples:[{ro:'Nii khu jet',tr:'Bu, Yedi',bd:[{ro:'Nii',tr:'Bu',role:'S'},{ro:'khu',tr:'demektir',role:'V'},{ro:'jet',tr:'Yedi',role:'O'}]}]},
    {id:'c70',ro:'bpaaet',tr:'sekiz',en:'eight',tip:'',ctx:'',examples:[{ro:'Nii khu bpaaet',tr:'Bu, sekiz',bd:[{ro:'Nii',tr:'Bu',role:'S'},{ro:'khu',tr:'demektir',role:'V'},{ro:'bpaaet',tr:'sekiz',role:'O'}]}]},
    {id:'c71',ro:'gao',tr:'dokuz',en:'nine',tip:'',ctx:'',examples:[{ro:'Nii khu gao',tr:'Bu, dokuz',bd:[{ro:'Nii',tr:'Bu',role:'S'},{ro:'khu',tr:'demektir',role:'V'},{ro:'gao',tr:'dokuz',role:'O'}]}]},
    {id:'c72',ro:'sip',tr:'on',en:'ten',tip:'',ctx:'',examples:[{ro:'Nii khu sip',tr:'Bu, on',bd:[{ro:'Nii',tr:'Bu',role:'S'},{ro:'khu',tr:'demektir',role:'V'},{ro:'sip',tr:'on',role:'O'}]}]},
  ]
};
LESSONS[20] = L20;
