// === DERS12.JS START ===
// Ders 12 verisi — tayca-v3
// =================== VERİ: DERS 12 — Acil Durumlar ===================
const L12 = {
  tones:[],
  words:[
    {id:'w1',th:'ช่วยด้วย',ro:'chuay-duay',tr:'Imdat / Yardım edin',
     tip:'"Chuay" = yardım et, "duay" = de/da (pekiştirme). Beraber "imdat" anlamına gelir.',
     ctx:'Acil her durumda bağırarak kullanılır. Phuket\te en önemli acil kelime.',
     examples:[
       {th:'ช่วยด้วยครับ',ro:'chuay-duay khrap',tr:'Yardım edin!',bd:[{ro:'chuay-duay',tr:'yardım edin',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ช่วยด้วยครับ มีคนเป็นลม',ro:'chuay-duay khrap mii khon pen lom',tr:'Yardım edin, biri bayıldı.',bd:[{ro:'chuay-duay',tr:'yardım edin',role:'V - Yuklem'},{ro:'mii khon pen lom',tr:'biri bayıldı',role:'Kelime'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ช่วยผมด้วยครับ',ro:'chuay pom duay khrap',tr:'Bana yardım edin lütfen.',bd:[{ro:'chuay pom duay',tr:'bana yardım et',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ขอความช่วยเหลือหน่อยครับ',ro:'khor khwaam chuay-luea noi khrap',tr:'Biraz yardım istiyorum.',bd:[{ro:'khor khwaam chuay-luea noi',tr:'yardım istiyorum',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w2',th:'ตำรวจ',ro:'tam-ruat',tr:'Polis',
     tip:'"Tam-ruat" = polis. Acil: 191. Trafik polisi = "tam-ruat jra-jorn".',
     ctx:'Hırsızlık, saldırı, kaza gibi durumlarda. 191 Phuket polis acil hattı.',
     examples:[
       {th:'โทรเรียกตำรวจด้วยครับ',ro:'tho riak tam-ruat duay khrap',tr:'Polisi arayın lütfen.',bd:[{ro:'tho riak tam-ruat duay',tr:'polisi çağır lütfen',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ตำรวจอยู่ที่ไหนครับ',ro:'tam-ruat yuu thii-nai khrap',tr:'Polis nerede?',bd:[{ro:'tam-ruat yuu thii-nai',tr:'polis nerede',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ไปหาตำรวจครับ',ro:'pai haa tam-ruat khrap',tr:'Polise gidiyorum.',bd:[{ro:'pai haa tam-ruat',tr:'polise git',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ตำรวจกำลังมาครับ',ro:'tam-ruat gam-lang maa khrap',tr:'Polis geliyor.',bd:[{ro:'tam-ruat gam-lang maa',tr:'polis geliyor',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w3',th:'รถพยาบาล',ro:'rot-pha-yaa-baan',tr:'Ambulans',
     tip:'"Rot" = araç, "pha-yaa-baan" = hastane. Ambulans acil: 1669.',
     ctx:'Yaralanma veya ciddi hastalıkta. 1669 ulusal ambulans hattı.',
     examples:[
       {th:'เรียกรถพยาบาลด้วยครับ',ro:'riak rot-pha-yaa-baan duay khrap',tr:'Ambulans cagirin lutfen.',bd:[{ro:'riak rot-pha-yaa-baan duay',tr:'ambulans cagir',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'รถพยาบาลมาถึงแล้วครับ',ro:'rot-pha-yaa-baan maa thueng laeo khrap',tr:'Ambulans geldi.',bd:[{ro:'rot-pha-yaa-baan maa thueng laeo',tr:'ambulans geldi',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ต้องการรถพยาบาลครับ',ro:'tong-gaan rot-pha-yaa-baan khrap',tr:'Ambulansa ihtiyacim var.',bd:[{ro:'tong-gaan rot-pha-yaa-baan',tr:'ambulans gerekiyor',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w4',th:'อุบัติเหตุ',ro:'u-bat-ti-het',tr:'Kaza',
     tip:'Uzun ama kritik. "Mii u-bat-ti-het" = kaza var. Kisaltma "u-bat" da anlasilir.',
     ctx:'Trafik kazasi, dusme, carpma gibi durumlarda.',
     examples:[
       {th:'มีอุบัติเหตุครับ',ro:'mii u-bat-ti-het khrap',tr:'Kaza var.',bd:[{ro:'mii u-bat-ti-het',tr:'kaza var',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'เกิดอุบัติเหตุที่นี่ครับ',ro:'goet u-bat-ti-het thii-nii khrap',tr:'Burada kaza oldu.',bd:[{ro:'goet u-bat-ti-het thii-nii',tr:'burada kaza oldu',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ผมประสบอุบัติเหตุครับ',ro:'pom pra-sop u-bat-ti-het khrap',tr:'Kaza gecirdim.',bd:[{ro:'pom pra-sop u-bat-ti-het',tr:'kaza gecirdim',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'อุบัติเหตุไม่รุนแรงครับ',ro:'u-bat-ti-het mai run-raeng khrap',tr:'Kaza ciddi degil.',bd:[{ro:'u-bat-ti-het mai run-raeng',tr:'kaza ciddi degil',role:'Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w5',th:'หาย',ro:'haai',tr:'Kaybolmak / Kaybetmek',
     tip:'"Haai" = kayboldu. "Gra-pao haai" = cantam kayboldu. "Pom haai" = kayboldum.',
     ctx:'Esya kaybinda veya yol kaybinde kullanilir.',
     examples:[
       {th:'กระเป๋าหายครับ',ro:'gra-pao haai khrap',tr:'Cantam kayboldu.',bd:[{ro:'gra-pao haai',tr:'canta kayboldu',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ผมหลงทางครับ',ro:'pom long-thaang khrap',tr:'Kayboldum.',bd:[{ro:'pom long-thaang',tr:'yolu kaybettim',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'โทรศัพท์หายครับ',ro:'tho-ra-sap haai khrap',tr:'Telefonum kayboldu.',bd:[{ro:'tho-ra-sap haai',tr:'telefon kayboldu',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'กุญแจหายครับ',ro:'gun-jae haai khrap',tr:'Anahtarim kayboldu.',bd:[{ro:'gun-jae haai',tr:'anahtar kayboldu',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w6',th:'กระเป๋า',ro:'gra-pao',tr:'Canta',
     tip:'"Gra-pao" = canta (her turlu). "Gra-pao sataang" = para cantasi. "Gra-pao doen-thaang" = bavul.',
     ctx:'Hirsizlik veya kayip durumunda kritik kelime.',
     examples:[
       {th:'กระเป๋าถูกขโมยครับ',ro:'gra-pao thuuk kha-mooy khrap',tr:'Cantam caliindi.',bd:[{ro:'gra-pao thuuk kha-mooy',tr:'canta calindi',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'กระเป๋าอยู่ที่ไหนครับ',ro:'gra-pao yuu thii-nai khrap',tr:'Cantam nerede?',bd:[{ro:'gra-pao yuu thii-nai',tr:'canta nerede',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'กระเป๋าสีดำครับ',ro:'gra-pao sii-dam khrap',tr:'Canta siyah renkli.',bd:[{ro:'gra-pao sii-dam',tr:'siyah canta',role:'Kelime'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w7',th:'โรงพัก',ro:'rong-phak',tr:'Karakol / Polis istasyonu',
     tip:'"Rong-phak" = karakol. Resmi rapor icin buraya gidilir. Pasaport getir!',
     ctx:'Hirsizlik, kayip veya kaza raporlama icin. Sigorta icin rapor sarttir.',
     examples:[
       {th:'โรงพักอยู่ที่ไหนครับ',ro:'rong-phak yuu thii-nai khrap',tr:'Karakol nerede?',bd:[{ro:'rong-phak yuu thii-nai',tr:'karakol nerede',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ต้องไปโรงพักครับ',ro:'tong pai rong-phak khrap',tr:'Karakola gitmem lazim.',bd:[{ro:'tong pai rong-phak',tr:'karakola gitmeli',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ขอแจ้งความที่โรงพักครับ',ro:'khor jaeng-khwaam thii rong-phak khrap',tr:'Karakolda sikayet bildirmek istiyorum.',bd:[{ro:'khor jaeng-khwaam thii rong-phak',tr:'karakolda sikayet',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w8',th:'ไฟ',ro:'fai',tr:'Ates / Yangin',
     tip:'"Fai" = ates, isik. "Fai mai" = yangin. "Fai faa" = elektrik. Yangin acil: 199.',
     ctx:'Yangin durumunda bagirarak kullanilir. Phuket sicaginda yangin riski var.',
     examples:[
       {th:'ไฟไหม้ครับ',ro:'fai-mai khrap',tr:'Yangin var!',bd:[{ro:'fai-mai',tr:'yangin var',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'โทรดับเพลิงด้วยครับ',ro:'tho dap-ploeng duay khrap',tr:'Itfaiyeyi arayin lutfen.',bd:[{ro:'tho dap-ploeng duay',tr:'itfaiye ara lutfen',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ออกจากอาคารครับ',ro:'ok jaak aa-khaan khrap',tr:'Binadan cikın.',bd:[{ro:'ok jaak aa-khaan',tr:'binadan cik',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w9',th:'ขโมย',ro:'kha-mooy',tr:'Hirsiz / Calmak',
     tip:'"Kha-mooy" = hem hirsiz hem calmak. "Thuuk kha-mooy" = calindi (pasif).',
     ctx:'Phuket plajlarinda esya hirsizligi olabilir. Bu kelimeyi bilin!',
     examples:[
       {th:'มีขโมยครับ',ro:'mii kha-mooy khrap',tr:'Hirsiz var!',bd:[{ro:'mii kha-mooy',tr:'hirsiz var',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ของถูกขโมยครับ',ro:'khong thuuk kha-mooy khrap',tr:'Esyam calindi.',bd:[{ro:'khong thuuk kha-mooy',tr:'esya calindi',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'จับขโมยได้ไหมครับ',ro:'jap kha-mooy dai mai khrap',tr:'Hirsizi yakalayabilir misiniz?',bd:[{ro:'jap kha-mooy dai mai',tr:'hirsiz yakalanir mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ขโมยวิ่งไปทางนั้นครับ',ro:'kha-mooy wing pai thaang-nan khrap',tr:'Hirsiz o yona kacti.',bd:[{ro:'kha-mooy wing pai thaang-nan',tr:'hirsiz o yone kacti',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w10',th:'โทร',ro:'tho',tr:'Aramak (telefon)',
     tip:'"Tho" = telefon aramak. "Tho + numara" = numarayi ara. "Tho haa pom" = beni ara.',
     ctx:'Acil numaralar: 191 (polis), 1669 (ambulans), 199 (itfaiye).',
     examples:[
       {th:'โทร 191 เลยครับ',ro:'tho 191 loey khrap',tr:'Hemen 191\'i arayin.',bd:[{ro:'tho 191 loey',tr:'hemen 191 ara',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'โทรหาผมด้วยครับ',ro:'tho haa pom duay khrap',tr:'Beni arayin lutfen.',bd:[{ro:'tho haa pom duay',tr:'beni ara lutfen',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'โทรไม่ได้ครับ',ro:'tho mai-dai khrap',tr:'Arayamiyorum.',bd:[{ro:'tho mai-dai',tr:'arayamiyor',role:'Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'โทร 1669 ด้วยครับ',ro:'tho 1669 duay khrap',tr:'1669\'u da arayin.',bd:[{ro:'tho 1669 duay',tr:'1669 da ara',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
  ],
  grammar:[
    {
      title:'1. THO + [numara/kisi] = aramak',
      formula:'THO + [NUMARA veya KISi] = arayin / ara',
      explain:'"Tho" fiili her zaman nesnesinden once gelir. Acil numaralari ezberleyin: 191 polis, 1669 ambulans, 199 itfaiye.',
      tips:['tho 191 = polisi ara','tho 1669 = ambulansi ara','tho 199 = itfaiyeyi ara','tho haa [kisi] = birisini ara','tho glab = geri ara','tho mai-dai = arayamiyor'],
      examples:[
        {th:'โทร 191 ด้วยครับ',ro:'tho 191 duay khrap',tr:'191\'i arayin lutfen.',bd:[{ro:'tho 191 duay',tr:'191 ara lutfen',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
        {th:'โทรหาตำรวจครับ',ro:'tho haa tam-ruat khrap',tr:'Polisi arayin.',bd:[{ro:'tho haa tam-ruat',tr:'polisi ara',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
        {th:'โทรหาผมเมื่อถึงครับ',ro:'tho haa pom muea-thueng khrap',tr:'Varinca beni arayin.',bd:[{ro:'tho haa pom muea-thueng',tr:'varinca beni ara',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
        {th:'โทรไม่ได้ มีสัญญาณไหมครับ',ro:'tho mai-dai mii san-yaan mai khrap',tr:'Arayamiyorum, sinyal var mi?',bd:[{ro:'tho mai-dai',tr:'arayamiyor',role:'Olumsuz'},{ro:'mii san-yaan mai',tr:'sinyal var mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
      ]
    },
    {
      title:'2. [esya] HAAI = kayboldu / calindi',
      formula:'[ESYA] + HAAI = ... kayboldu',
      explain:'"Haai" = kaybolmak. Esya ismi + haai ile hizli acil durum bildirimi yapilir. "Thuuk kha-mooy" ile calindi anlaminda da kullanilabilir.',
      tips:['gra-pao haai = canta kayboldu','tho-ra-sap haai = telefon kayboldu','gun-jae haai = anahtar kayboldu','pom haai = kayboldum','long-thaang = yolu kaybettim','thuuk kha-mooy = calindi'],
      examples:[
        {th:'กระเป๋าหายครับ',ro:'gra-pao haai khrap',tr:'Cantam kayboldu.',bd:[{ro:'gra-pao haai',tr:'canta kayboldu',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
        {th:'โทรศัพท์หายครับ ช่วยด้วย',ro:'tho-ra-sap haai khrap chuay duay',tr:'Telefonum kayboldu, yardim edin.',bd:[{ro:'tho-ra-sap haai',tr:'telefon kayboldu',role:'V - Yuklem'},{ro:'chuay duay',tr:'yardim edin',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
        {th:'ของหายทั้งหมดเลยครับ',ro:'khong haai thang-mot loey khrap',tr:'Her sey kayboldu.',bd:[{ro:'khong haai thang-mot loey',tr:'her sey kayboldu',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
      ]
    },
    {
      title:'3. Acil Numaralar ve Hizli Ifadeler',
      formula:'CHUAY-DUAY! THO [NUMARA]! = Imdat! [numarayi] arayin!',
      explain:'Phuket\'te bilmeniz gereken acil numaralar ve hizli ifadeler. Sesli ve net soyleyin.',
      tips:['191 = polis (politat)','1669 = ambulans (ulusal)','199 = itfaiye','1155 = turist polis (ingilizce)','chuay-duay = imdat','fai-mai = yangin var'],
      examples:[
        {th:'ช่วยด้วยครับ โทร 1669',ro:'chuay-duay khrap tho 1669',tr:'Imdat! 1669\'u arayin.',bd:[{ro:'chuay-duay',tr:'imdat',role:'V - Yuklem'},{ro:'tho 1669',tr:'1669 arayin',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
        {th:'ไฟไหม้ครับ โทร 199',ro:'fai-mai khrap tho 199',tr:'Yangin var! 199\'u arayin.',bd:[{ro:'fai-mai',tr:'yangin var',role:'V - Yuklem'},{ro:'tho 199',tr:'199 arayin',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
      ]
    },
  ],
  speaking:[
    {task:'Imdat bagir',th:'ช่วยด้วยครับ',ro:'chuay-duay khrap',tr:'Yardim edin!',bd:[{ro:'chuay-duay',tr:'yardim edin',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Polisi ara',th:'โทร 191 เลยครับ',ro:'tho 191 loey khrap',tr:'Hemen 191 arayin.',bd:[{ro:'tho 191 loey',tr:'hemen 191 ara',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Ambulans cagir',th:'เรียกรถพยาบาลด้วยครับ',ro:'riak rot-pha-yaa-baan duay khrap',tr:'Ambulans cagirin.',bd:[{ro:'riak rot-pha-yaa-baan duay',tr:'ambulans cagir',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Kaza var bildir',th:'มีอุบัติเหตุครับ',ro:'mii u-bat-ti-het khrap',tr:'Kaza var.',bd:[{ro:'mii u-bat-ti-het',tr:'kaza var',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Cantam kayboldu',th:'กระเป๋าหายครับ',ro:'gra-pao haai khrap',tr:'Cantam kayboldu.',bd:[{ro:'gra-pao haai',tr:'canta kayboldu',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Hirsiz var bildir',th:'มีขโมยครับ',ro:'mii kha-mooy khrap',tr:'Hirsiz var!',bd:[{ro:'mii kha-mooy',tr:'hirsiz var',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Karakol nerede sor',th:'โรงพักอยู่ที่ไหนครับ',ro:'rong-phak yuu thii-nai khrap',tr:'Karakol nerede?',bd:[{ro:'rong-phak yuu thii-nai',tr:'karakol nerede',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Yangin var bagir',th:'ไฟไหม้ครับ',ro:'fai-mai khrap',tr:'Yangin var!',bd:[{ro:'fai-mai',tr:'yangin var',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Esyam calindi',th:'ของถูกขโมยครับ',ro:'khong thuuk kha-mooy khrap',tr:'Esyam calindi.',bd:[{ro:'khong thuuk kha-mooy',tr:'esya calindi',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Kayboldum',th:'ผมหลงทางครับ',ro:'pom long-thaang khrap',tr:'Kayboldum.',bd:[{ro:'pom long-thaang',tr:'yolu kaybettim',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Sikayet bildir',th:'ขอแจ้งความครับ',ro:'khor jaeng-khwaam khrap',tr:'Sikayet bildirmek istiyorum.',bd:[{ro:'khor jaeng-khwaam',tr:'sikayet bildir',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Turist polisi ara',th:'โทร 1155 ครับ',ro:'tho 1155 khrap',tr:'1155 turist polisi.',bd:[{ro:'tho 1155',tr:'1155 arayin',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
  ],
  dialogues:[
    {title:'🆘 Canta Hirsizligi',
     lines:[
       {s:'Tom',th:'ช่วยด้วยครับ กระเป๋าถูกขโมยครับ',ro:'chuay-duay khrap gra-pao thuuk kha-mooy khrap',tr:'Imdat! Cantam calindi!',bd:[{ro:'chuay-duay',tr:'imdat',role:'V - Yuklem'},{ro:'gra-pao thuuk kha-mooy',tr:'canta calindi',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {s:'Lucy',th:'เป็นยังไงบ้างคะ บาดเจ็บไหมคะ',ro:'pen yang-ngai baang kha baat-jep mai kha',tr:'Nasil siniz, yaralandiniz mi?',bd:[{ro:'pen yang-ngai baang',tr:'nasil',role:'Soru/Olumsuz'},{ro:'baat-jep mai',tr:'yaralandi mi',role:'Soru/Olumsuz'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
       {s:'Tom',th:'ไม่บาดเจ็บครับ แต่กระเป๋าหายครับ',ro:'mai baat-jep khrap tae gra-pao haai khrap',tr:'Yaralanmadim ama cantam kayboldu.',bd:[{ro:'mai baat-jep',tr:'yaralanmadi',role:'Olumsuz'},{ro:'tae gra-pao haai',tr:'ama canta kayboldu',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {s:'Lucy',th:'โทร 191 เลยนะคะ แล้วไปโรงพักค่ะ',ro:'tho 191 loey na kha laeo pai rong-phak kha',tr:'Hemen 191\'i arayin, sonra karakola gidin.',bd:[{ro:'tho 191 loey',tr:'hemen 191 ara',role:'V - Yuklem'},{ro:'pai rong-phak',tr:'karakola git',role:'V - Yuklem'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
       {s:'Tom',th:'โรงพักอยู่ที่ไหนครับ',ro:'rong-phak yuu thii-nai khrap',tr:'Karakol nerede?',bd:[{ro:'rong-phak yuu thii-nai',tr:'karakol nerede',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {s:'Lucy',th:'อยู่ใกล้ๆ ค่ะ เดินห้านาทีค่ะ',ro:'yuu glai-glai kha dern haa-naa-thii kha',tr:'Yakindir, yuruyerek 5 dakika.',bd:[{ro:'yuu glai-glai',tr:'yakin',role:'Kelime'},{ro:'dern haa-naa-thii',tr:'yuruyerek 5 dakika',role:'Kelime'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {title:'🚑 Kaza Yardimi',
     lines:[
       {s:'Tom',th:'มีอุบัติเหตุครับ ช่วยด้วยครับ',ro:'mii u-bat-ti-het khrap chuay duay khrap',tr:'Kaza var! Yardim edin!',bd:[{ro:'mii u-bat-ti-het',tr:'kaza var',role:'V - Yuklem'},{ro:'chuay duay',tr:'yardim edin',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {s:'Lucy',th:'โทร 1669 ด้วยนะคะ',ro:'tho 1669 duay na kha',tr:'1669\'u arayın.',bd:[{ro:'tho 1669 duay',tr:'1669 arayin',role:'V - Yuklem'},{ro:'na kha',tr:'onay eki',role:'Kibar'}]},
       {s:'Tom',th:'โทรไม่ได้ครับ สัญญาณไม่มีครับ',ro:'tho mai-dai khrap san-yaan mai-mii khrap',tr:'Arayamiyorum, sinyal yok.',bd:[{ro:'tho mai-dai',tr:'arayamiyor',role:'Olumsuz'},{ro:'san-yaan mai-mii',tr:'sinyal yok',role:'Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {s:'Lucy',th:'ให้คะ โทรให้เองค่ะ',ro:'hai kha tho hai eng kha',tr:'Tamam, ben ararım.',bd:[{ro:'tho hai eng',tr:'ben ararım',role:'V - Yuklem'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {title:'🔥 Yangin Durumu',
     lines:[
       {s:'Tom',th:'ไฟไหม้ครับ ออกจากอาคารครับ',ro:'fai-mai khrap ok jaak aa-khaan khrap',tr:'Yangin var! Binadan cikın!',bd:[{ro:'fai-mai',tr:'yangin var',role:'V - Yuklem'},{ro:'ok jaak aa-khaan',tr:'binadan cik',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {s:'Lucy',th:'จริงเหรอคะ โทร 199 เลยค่ะ',ro:'jing roe kha tho 199 loey kha',tr:'Gercekten mi? Hemen 199\'u arayin.',bd:[{ro:'jing roe',tr:'gercekten mi',role:'Soru/Olumsuz'},{ro:'tho 199 loey',tr:'hemen 199 ara',role:'V - Yuklem'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
       {s:'Tom',th:'ใช่ครับ ควันเยอะมากครับ',ro:'chai khrap khwan yoe maak khrap',tr:'Evet, cok duman var.',bd:[{ro:'chai',tr:'evet',role:'Kelime'},{ro:'khwan yoe maak',tr:'cok duman var',role:'Kelime'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {s:'Lucy',th:'รีบออกไปนะคะ อย่ารอค่ะ',ro:'riip ok pai na kha yaa ro kha',tr:'Hemen cikın, beklemeyın.',bd:[{ro:'riip ok pai',tr:'hemen cik',role:'V - Yuklem'},{ro:'yaa ro',tr:'bekleme',role:'Olumsuz'},{ro:'na kha',tr:'onay eki',role:'Kibar'}]},
     ]},
    {title:'🚓 Karakolda Sikayet',
     lines:[
       {s:'Tom',th:'ขอแจ้งความครับ กระเป๋าหายครับ',ro:'khor jaeng-khwaam khrap gra-pao haai khrap',tr:'Sikayet bildirmek istiyorum, cantam kayboldu.',bd:[{ro:'khor jaeng-khwaam',tr:'sikayet bildir',role:'V - Yuklem'},{ro:'gra-pao haai',tr:'canta kayboldu',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {s:'Lucy',th:'หายที่ไหนคะ',ro:'haai thii-nai kha',tr:'Nerede kayboldu?',bd:[{ro:'haai thii-nai',tr:'nerede kayboldu',role:'Soru/Olumsuz'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
       {s:'Tom',th:'ที่ชายหาดป่าตองครับ ขโมยเอาไปครับ',ro:'thii chaai-haat pa-tong khrap kha-mooy ao pai khrap',tr:'Patong plajinda, hirsiz aldi.',bd:[{ro:'thii chaai-haat pa-tong',tr:'patong plajinda',role:'Kelime'},{ro:'kha-mooy ao pai',tr:'hirsiz aldi',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {s:'Lucy',th:'มีพาสปอร์ตมาด้วยไหมคะ',ro:'mii paat-sa-pot maa duay mai kha',tr:'Pasaportunuz var mi?',bd:[{ro:'mii paat-sa-pot maa duay mai',tr:'pasaport var mi',role:'Soru/Olumsuz'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
     ]},
  ],
  listening:[
    {diff:'easy',th:'ช่วยด้วยครับ',q:'Ne soyleniyor?',opts:['Hosgeldiniz','Imdat / Yardim edin','Gule gule'],c:1},
    {diff:'easy',th:'ไฟไหม้ครับ',q:'Ne var?',opts:['Kaza var','Yangin var','Hirsiz var'],c:1},
    {diff:'easy',th:'กระเป๋าหายครับ',q:'Ne oldu?',opts:['Canta bulundu','Canta kayboldu','Canta dolu'],c:1},
    {diff:'easy',th:'มีขโมยครับ',q:'Ne var?',opts:['Polis var','Hirsiz var','Ambulans var'],c:1},
    {diff:'medium',th:'โทร 191 เลยครับ',q:'Hangi numara araniyor?',opts:['1669','199','191'],c:2},
    {diff:'medium',th:'โรงพักอยู่ที่ไหนครับ',q:'Ne soruluyor?',opts:['Hastane nerede','Karakol nerede','Otel nerede'],c:1},
    {diff:'medium',th:'ของถูกขโมยครับ',q:'Ne oldu?',opts:['Esya bulundu','Esya bozuldu','Esya calindi'],c:2},
    {diff:'medium',th:'เรียกรถพยาบาลด้วยครับ',q:'Ne isteniyor?',opts:['Taksi cagir','Ambulans cagir','Polis cagir'],c:1},
    {diff:'hard',th:'ขอแจ้งความที่โรงพักครับ',q:'Nerede ne yapilmak isteniyor?',opts:['Hastanede tedavi','Karakolda sikayet','Otelde sikayet'],c:1},
    {diff:'hard',th:'ไม่บาดเจ็บครับ แต่กระเป๋าหายครับ',q:'Ne soyleniyor?',opts:['Yaralandim, canta tamam','Yaralanmadim ama canta kayboldu','Her sey tamam'],c:1},
  ],
  quiz:[
    {q:'"chuay-duay" ne demek?',opts:['Hosgeldiniz','Imdat / Yardim edin','Gule gule','Saglikla'],c:1},
    {q:'"tam-ruat" ne demek?',opts:['Doktor','Itfaiyeci','Polis','Garson'],c:2},
    {q:'"rot-pha-yaa-baan" ne demek?',opts:['Polis arabasi','Ambulans','Taksi','Yangin arabasi'],c:1},
    {q:'"haai" ne demek?',opts:['Bulmak','Satmak','Kaybolmak','Vermek'],c:2},
    {q:'"gra-pao" ne demek?',opts:['Anahtar','Pasaport','Canta','Telefon'],c:2},
    {q:'"rong-phak" ne demek?',opts:['Hastane','Otel','Karakol','Okul'],c:2},
    {q:'"fai-mai" ne demek?',opts:['Elektrik kesildi','Yangin var','Isik yanmiyor','Fatura yuklu'],c:1},
    {q:'"kha-mooy" ne demek?',opts:['Garson','Doktor','Polis','Hirsiz'],c:3},
    {q:'Phuket polis acil hatti?',opts:['199','1669','191','1155'],c:2},
    {q:'Ulusal ambulans hatti?',opts:['191','1669','199','1155'],c:1},
    {q:'Itfaiye acil hatti?',opts:['191','1669','199','1155'],c:2},
    {q:'Turist polis hatti (Ingilizce)?',opts:['191','1669','199','1155'],c:3},
    {q:'"tho" ne demek?',opts:['Yazmak','Aramak (telefon)','Gormek','Duymak'],c:1},
    {q:'"thuuk kha-mooy" ne demek?',opts:['Hirsizi gormek','Calindi (pasif)','Hirsiza gitmek','Hirsizlik yapmak'],c:1},
    {q:'"mii u-bat-ti-het" ne anlama gelir?',opts:['Kaza geciyor','Kaza var','Kaza gecti','Kaza yok'],c:1},
    {q:'Tom nasil konusur?',opts:['ค่ะ/kha ile','ครับ/khrap ile','Her ikisiyle','Hicbiriyle'],c:1},
    {q:'"jaeng-khwaam" ne demek?',opts:['Konusmak','Sikayet bildirmek','Yardim istemek','Acil aramak'],c:1},
    {q:'"long-thaang" ne demek?',opts:['Yolu bulmak','Yolu kaybetmek','Yol sormak','Yol kapatmak'],c:1},
    {q:'"ok jaak aa-khaan" ne demek?',opts:['Binaya gir','Binadan cik','Binayi yak','Binaya bak'],c:1},
    {q:'"baat-jep" ne demek?',opts:['Hasta olmak','Yaralanmak','Olmek','Bayilmak'],c:1},
  ],
};

LESSONS[12] = L12;
